#nullable enable

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Rendering;

namespace HorrorGame.Gameplay.Player
{
    /// <summary>
    /// Decides what the person inside the rig sees of their own body.
    /// <para>
    /// §05 says it in one line — <b>"자기 몸은 안 보이므로 손만 있으면 된다"</b> — and both
    /// halves are requirements. The body is not drawn, because the model is parented under
    /// the rig and in first person its shoulders and chest sit across the near plane as a
    /// shape along the bottom of the screen. The hands <em>are</em> drawn, because a
    /// first-person game where nothing on screen belongs to you is a floating camera, and
    /// §03 asks the player to tell four states apart — empty hands, torch, loot, objective
    /// — with no HUD to read them off.
    /// </para>
    /// <para>
    /// <b>The shadow survives.</b> Everything hidden is set to
    /// <see cref="ShadowCastingMode.ShadowsOnly"/>, never disabled. In a game where §03
    /// makes a narrow beam the only light, a player's own shadow thrown down a corridor is
    /// free atmosphere and a cue for where the beam is pointing — and it is cast from the
    /// whole body, not from the arms alone, because the body still exists to the renderer.
    /// This is the property the fix that caused the defect got right and must not lose:
    /// the previous version set <em>every</em> renderer to ShadowsOnly, which solved the
    /// occlusion and took the arms with it.
    /// </para>
    /// <para>
    /// <b>Per owner, not per rig.</b> §13 makes the other three players visible to each
    /// other, so a remote copy of this model must be drawn whole. That is what
    /// <see cref="IsOwner"/> selects; call <see cref="Apply"/> after changing it. Until
    /// the network layer spawns remote bodies every rig built is the local one, which is
    /// why the default is true.
    /// </para>
    /// <para>
    /// <b>The hands are their own asset now (#83), and the old sentence has to be
    /// rewritten.</b> Hiding the body and keeping "the arms" worked while the arms were
    /// meshes of the same model — <c>Player.fbx</c> split into <c>Player_Body</c>,
    /// <c>Player_Arms</c> and <c>Player_Torch</c>, told apart by material slot. On
    /// <c>Runner.fbx</c> there is one mesh with five <c>Runner_*</c> slots, nothing
    /// classifies as arms, and this component has been hiding the entire rig and warning
    /// about it (B-017). Worse, it could not have worked even if it did classify: a
    /// third-person body seen from inside is a shape across the near plane, and the arms
    /// that would have been kept hang 22° below the bottom edge of an 80° frame.
    /// </para>
    /// <para>
    /// So the owner is shown <c>Assets/Models/Player/RunnerArms.fbx</c> — sleeves and
    /// gloves only, framed for this camera, generated by <c>gen_runner.py</c> from the
    /// body's own sleeve table and the body's own mocap. This file <em>finds or builds</em>
    /// it under the camera (<see cref="EnsureFirstPersonArms"/>), classifies everything
    /// under it as <see cref="PlayerRigPart.Arms"/> <b>by parentage rather than by
    /// material</b>, and hides it outright for anybody who is not the owner. Parentage,
    /// because the arms deliberately carry the same five <c>Runner_*</c> slots the body
    /// does — one material set, one importer case, one place a tint is applied — and
    /// <see cref="PlayerRigParts"/> keys on <c>Player_Skin</c>, which is a different
    /// model's vocabulary and not this component's to change.
    /// </para>
    /// </summary>
    [DisallowMultipleComponent]
    [DefaultExecutionOrder(-90)]
    public sealed class PlayerFirstPersonView : MonoBehaviour
    {
        /// <summary>
        /// What the first-person arms are called under the rig. Anything parented to a
        /// transform with this name reads as the owner's own hands, whatever it is made of.
        /// </summary>
        public const string FirstPersonArmsChildName = "FirstPersonArms";

        /// <summary>The asset <c>gen_runner.py</c> writes. Loaded in the editor only; a shipped rig has it serialised.</summary>
        public const string FirstPersonArmsModelPath = "Assets/Models/Player/RunnerArms.fbx";

        [Tooltip("Rig root to search for renderers. Left empty, this transform.")]
        [SerializeField]
        private Transform? _rigRoot;

        [Tooltip("The first-person arms under the camera. Found or built by EnsureFirstPersonArms.")]
        [SerializeField]
        private Transform? _firstPersonArms;

        [Tooltip("RunnerArms.fbx's clips, resolved at rig-build time so a player build needs no AssetDatabase. PlayerWorldArms plays them.")]
        [SerializeField]
        private AnimationClip[] _firstPersonArmClips = System.Array.Empty<AnimationClip>();

        [Tooltip("False stops this rig from ever growing first-person arms — for a test fixture, or a rig that is only ever seen from outside.")]
        [SerializeField]
        private bool _buildFirstPersonArms = true;

        [Tooltip("False for a remote player's body (§13): everything is drawn normally.")]
        [SerializeField]
        private bool _isOwner = true;

        [Tooltip("Log the classification once. A regenerated model that merged its meshes is otherwise silent.")]
        [SerializeField]
        private bool _report = true;

        private readonly List<SkinnedMeshRenderer> _bodyParts = new List<SkinnedMeshRenderer>();
        private readonly List<SkinnedMeshRenderer> _armParts = new List<SkinnedMeshRenderer>();
        private readonly List<SkinnedMeshRenderer> _viewModelArms = new List<SkinnedMeshRenderer>();
        private readonly List<SkinnedMeshRenderer> _handProps = new List<SkinnedMeshRenderer>();
        private bool _collected;
        private bool _armsSearched;
#if UNITY_EDITOR
        private bool _reportedNoAsset;
#endif

        // Stowed until something says otherwise. §10 makes switching the light on a
        // decision with a cost, and a rig that arrived with the torch already in the fist
        // would show the player they had made it before they had.
        private bool _handPropVisible;
        private bool _handPropApplied;

        /// <summary>
        /// Whether this rig belongs to the player looking through its camera. Setting it
        /// does not re-apply on its own — call <see cref="Apply"/>, so a spawner can set
        /// several fields and pay for one pass.
        /// </summary>
        public bool IsOwner
        {
            get { return _isOwner; }
            set
            {
                if (value && !_isOwner)
                {
                    // Becoming the owner is the one event that makes a second search
                    // worthwhile: a rig that had no viewmodel because nobody was looking
                    // through it now has somebody. Anything else — and in particular a
                    // failed load — must not be retried, or a rig with a camera and no
                    // asset hits AssetDatabase once per frame for the whole session.
                    _armsSearched = false;
                }

                _isOwner = value;
            }
        }

        /// <summary>
        /// The renderers riding a single hand — §05's flashlight today. Whoever owns the
        /// item's state decides whether it is in hand; see <see cref="PlayerFlashlight"/>.
        /// </summary>
        public IReadOnlyList<SkinnedMeshRenderer> HandProps
        {
            get
            {
                Collect();
                return _handProps;
            }
        }

        /// <summary>
        /// The first-person arms under this rig, or null when there are none — a rig with
        /// no camera, a remote body, or a checkout where <c>RunnerArms.fbx</c> has not been
        /// generated yet. <see cref="PlayerWorldArms"/> animates whatever this returns.
        /// </summary>
        public Transform? FirstPersonArms
        {
            get
            {
                EnsureFirstPersonArms();
                return _firstPersonArms;
            }
        }

        /// <summary>
        /// <c>RunnerArms.fbx</c>'s clips, in the order it exports them. Resolved once at
        /// rig-build time and serialised, because a player build has no
        /// <c>AssetDatabase</c> to ask and an FBX's sub-assets are reachable no other way.
        /// </summary>
        public IReadOnlyList<AnimationClip> FirstPersonArmClips
        {
            get { return _firstPersonArmClips; }
        }

        /// <summary>How many renderers were classified as the owner's own hands. Zero means §05 is not being met.</summary>
        public int ArmRendererCount
        {
            get
            {
                Collect();
                return _armParts.Count;
            }
        }

        /// <summary>
        /// The renderers that are the owner's own hands. Exposed for
        /// <see cref="PlayerHandFill"/>, which has to reach exactly this set and no other:
        /// it puts them on a rendering layer so a light can find them without finding the
        /// building.
        /// </summary>
        public IReadOnlyList<SkinnedMeshRenderer> ArmRenderers
        {
            get
            {
                Collect();
                return _armParts;
            }
        }

        /// <summary>
        /// Applies the policy to every renderer under the rig.
        /// <para>
        /// Public and idempotent because three different callers need it: the editor rig
        /// builder, which bakes the result into a scene; a future network spawner, which
        /// learns whose body this is a frame after it exists; and a shot rig, which has to
        /// photograph the same decision the player gets rather than a re-implementation of
        /// it.
        /// </para>
        /// </summary>
        public void Apply()
        {
            Collect();

            var hidden = _isOwner ? ShadowCastingMode.ShadowsOnly : ShadowCastingMode.On;
            for (var i = 0; i < _bodyParts.Count; i++)
            {
                _bodyParts[i].shadowCastingMode = hidden;
            }

            for (var i = 0; i < _armParts.Count; i++)
            {
                // Drawn and casting. The arms are part of the same silhouette on the
                // corridor wall as the body, and a shadow missing its arms reads as a
                // rendering fault rather than as a person.
                _armParts[i].shadowCastingMode = ShadowCastingMode.On;
            }

            for (var i = 0; i < _viewModelArms.Count; i++)
            {
                // And the VIEWMODEL arms cast nothing, which overrides the line above for
                // exactly this set. They are 0.38 m from the eye and the body behind them
                // is already throwing the whole silhouette down the corridor — a second
                // pair of arms in that shadow is two left arms on the wall, and at that
                // distance from a spot light their shadow is most of the frame.
                _viewModelArms[i].shadowCastingMode = ShadowCastingMode.Off;
            }

            if (_firstPersonArms != null)
            {
                // Off, not ShadowsOnly. Everything else here is hidden by shadow mode
                // because the body still owes the corridor a silhouette; a viewmodel owes
                // nothing to anybody but its owner, and on a remote body it would be a
                // second pair of forearms sticking out of someone's chest.
                _firstPersonArms.gameObject.SetActive(_isOwner);
            }

            for (var i = 0; i < _handProps.Count; i++)
            {
                // Off, not On: the spot light sits on FlashlightMount, a hand's width from
                // this mesh, and a 0.2 m object between a light and everything else throws
                // a shadow across the whole corridor. The body's shadow is the one that
                // carries the atmosphere; the torch's would only be a bug.
                _handProps[i].shadowCastingMode = ShadowCastingMode.Off;
            }

            // Whatever the item state is, pushed through the same path that maintains it.
            SetHandPropVisible(_handPropVisible);

            if (_report)
            {
                _report = false;
                Report();
            }
        }

        /// <summary>
        /// Shows or hides everything classified as a held item.
        /// <para>
        /// Separate from <see cref="Apply"/> because it changes many times a match and the
        /// classification does not. §03 takes the torch away the instant the objective is
        /// lifted ("양손을 쓴다 → 손전등을 들 수 없다") and §10 has the player switching it
        /// off whenever the monster might be looking, so this is the most-toggled thing on
        /// the rig.
        /// </para>
        /// </summary>
        /// <param name="visible">True while the item is in hand.</param>
        public void SetHandPropVisible(bool visible)
        {
            Collect();

            // Guarded rather than written blind: the caller polls a state every frame,
            // and assigning Renderer.enabled dirties the culling entry whether or not the
            // value changed.
            if (_handPropVisible == visible && _handPropApplied)
            {
                return;
            }

            _handPropVisible = visible;
            _handPropApplied = true;

            for (var i = 0; i < _handProps.Count; i++)
            {
                _handProps[i].enabled = visible;
            }
        }

        private void Awake()
        {
            Apply();
        }

        private void Reset()
        {
            _rigRoot = transform;
        }

        /// <summary>
        /// Finds the first-person arms under this rig, or builds them from
        /// <see cref="FirstPersonArmsModelPath"/>. Idempotent, and safe to call from
        /// anywhere — it returns null rather than doing anything surprising.
        /// <para>
        /// <b>Where it is parented, and why that is the whole wiring.</b> The arms go under
        /// the <em>camera</em> transform at identity. <c>RunnerArms.fbx</c> is authored with
        /// its origin AT THE EYE — <c>gen_runner.py</c>'s <c>EYE_HEIGHT</c>, which it reads
        /// back out of <c>PlayerFeelHarnessMenu</c> every run and fails on if it has moved
        /// — so there is no offset here for anybody to get wrong later. Under the camera
        /// rather than under <c>PitchPivot</c> because <c>PlayerViewMotion</c> writes the
        /// camera's local transform: arms hung off the pivot would sit still while the view
        /// bobbed around them, which is the one thing a viewmodel must never do.
        /// </para>
        /// <para>
        /// <b>Why a camera is the gate.</b> A rig with no camera under it is not a rig
        /// anybody is looking through — <c>NetRunnerBody</c> clones
        /// the <c>Visual</c> child alone and adds this component to the copy, and every
        /// PlayMode fixture builds a bare hierarchy. None of them should grow a viewmodel,
        /// and none of them has a camera, so the gate costs nothing and needs no flag.
        /// </para>
        /// <para>
        /// <b>Editor only.</b> <c>AssetDatabase</c> does not exist in a player, and an FBX
        /// under <c>Assets/</c> is not loadable at runtime by any other means. That is not
        /// a limitation in practice: the rig is assembled by <c>PlayerFeelHarnessMenu</c>
        /// and saved into the scene by <c>SoloPlaytest</c>, both editor code, so what ships
        /// is the serialised instance and the serialised clip list. In a player this
        /// method only ever <em>finds</em>.
        /// </para>
        /// </summary>
        /// <returns>The arms root, or null when this rig has none.</returns>
        public Transform? EnsureFirstPersonArms()
        {
            if (_firstPersonArms != null)
            {
                return _firstPersonArms;
            }

            if (_armsSearched)
            {
                return null;
            }

            var root = _rigRoot != null ? _rigRoot : transform;
            var found = PlayerRigBones.Find(root, FirstPersonArmsChildName);
            if (found != null)
            {
                _armsSearched = true;
                _firstPersonArms = found;
                return found;
            }

            if (!_buildFirstPersonArms || !_isOwner)
            {
                return null;
            }

            var eye = root.GetComponentInChildren<Camera>(includeInactive: true);
            if (eye == null)
            {
                return null;
            }

            // Whatever happens below, it happens once.
            _armsSearched = true;

#if UNITY_EDITOR
            var model = UnityEditor.AssetDatabase.LoadAssetAtPath<GameObject>(FirstPersonArmsModelPath);
            if (model == null)
            {
                if (!_reportedNoAsset)
                {
                    _reportedNoAsset = true;
                    Debug.LogWarning(
                        "[Player] " + FirstPersonArmsModelPath + " is missing, so the owner "
                        + "gets no hands. Run: blender --background --factory-startup "
                        + "--python tools/blender/gen_runner.py — it writes Runner.fbx and "
                        + "RunnerArms.fbx from the same build.",
                        this);
                }

                return null;
            }

            var instance = Application.isPlaying
                ? Instantiate(model)
                : (GameObject)UnityEditor.PrefabUtility.InstantiatePrefab(model);
            instance.name = FirstPersonArmsChildName;
            instance.transform.SetParent(eye.transform, worldPositionStays: false);
            instance.transform.localPosition = Vector3.zero;
            instance.transform.localRotation = Quaternion.identity;
            instance.transform.localScale = Vector3.one;
            _firstPersonArms = instance.transform;

            // The clips come across at the same moment and from the same file, so the
            // instance and the animation that drives it can never be from two different
            // builds of the asset.
            var clips = new List<AnimationClip>();
            foreach (var asset in UnityEditor.AssetDatabase.LoadAllAssetsAtPath(FirstPersonArmsModelPath))
            {
                if (asset is AnimationClip clip && !clip.name.StartsWith("__preview__"))
                {
                    clips.Add(clip);
                }
            }

            clips.Sort((a, b) => string.CompareOrdinal(a.name, b.name));
            _firstPersonArmClips = clips.ToArray();

            // New renderers exist, so the classification is stale. Cheaper than guarding
            // every reader, and Collect is idempotent.
            _collected = false;
            _bodyParts.Clear();
            _armParts.Clear();
            _viewModelArms.Clear();
            _handProps.Clear();
            return _firstPersonArms;
#else
            return null;
#endif
        }

        private void Collect()
        {
            if (_collected)
            {
                return;
            }

            EnsureFirstPersonArms();
            _collected = true;
            var root = _rigRoot != null ? _rigRoot : transform;

            foreach (var renderer in root.GetComponentsInChildren<SkinnedMeshRenderer>(includeInactive: true))
            {
                if (_firstPersonArms != null && renderer.transform.IsChildOf(_firstPersonArms))
                {
                    // By parentage, not by material. RunnerArms.fbx carries the body's own
                    // five Runner_* slots on purpose — one material set for the importer,
                    // for the texture manifest and for anything that tints slot 0 — and
                    // PlayerRigParts asks for Player_Skin, which belongs to a model this
                    // project no longer ships. Asking "is this under the viewmodel" is both
                    // cheaper and more honest than teaching the classifier a second
                    // vocabulary to describe a mesh whose whole identity is where it hangs.
                    _armParts.Add(renderer);
                    _viewModelArms.Add(renderer);
                    continue;
                }

                switch (PlayerRigParts.Classify(renderer))
                {
                    case PlayerRigPart.Arms:
                        _armParts.Add(renderer);
                        break;
                    case PlayerRigPart.HandProp:
                        _handProps.Add(renderer);
                        break;
                    default:
                        // Body and Unknown together. An unrecognised renderer is hidden
                        // rather than drawn: a chest across the near plane is a defect the
                        // player cannot play around, and a missing hand is one they can.
                        _bodyParts.Add(renderer);
                        break;
                }
            }
        }

        private void Report()
        {
            // The per-renderer breakdown is in both the warning and the ordinary log on
            // purpose. When this goes wrong it goes wrong at the import — a mesh that
            // arrived bound to more bones than it is weighted to, or a split that was lost
            // — and the only cheap way to tell those apart is to see what the importer
            // actually produced.
            var detail = new System.Text.StringBuilder();
            Describe(detail, "arms", _armParts);
            Describe(detail, "hidden", _bodyParts);
            Describe(detail, "held", _handProps);

            if (_armParts.Count == 0)
            {
                Debug.LogWarning(
                    "[Player] No renderer under this rig reads as the owner's hands, so they will "
                    + "see nothing of themselves. §05 asks for 손. Since #83 the hands are their "
                    + "own asset — " + FirstPersonArmsModelPath + ", instantiated under the "
                    + "camera as '" + FirstPersonArmsChildName + "' by EnsureFirstPersonArms — so "
                    + "there are exactly three ways to be here: the rig has no Camera under it "
                    + "(a remote body or a bare test fixture, and then this is correct), the FBX "
                    + "has not been generated (run tools/blender/gen_runner.py), or the rig was "
                    + "assembled in a player build where AssetDatabase cannot reach it and the "
                    + "scene was never re-saved by SoloPlaytest. Runner.fbx itself contributes "
                    + "nothing here and is not supposed to: its one mesh is all Runner_*, no "
                    + "Player_Skin, and a third-person body seen from inside was never the "
                    + "answer." + detail,
                    this);
                return;
            }

            Debug.Log(
                "[Player] first-person view: " + _armParts.Count + " arm renderer(s) drawn ("
                + _viewModelArms.Count + " of them the RunnerArms viewmodel), "
                + _bodyParts.Count + " hidden but still casting, " + _handProps.Count
                + " hand prop(s), " + _firstPersonArmClips.Length + " arm clip(s). Owner="
                + _isOwner + "." + detail,
                this);
        }

        private static void Describe(
            System.Text.StringBuilder into, string label, List<SkinnedMeshRenderer> renderers)
        {
            for (var i = 0; i < renderers.Count; i++)
            {
                var renderer = renderers[i];
                into.Append("\n  ").Append(label).Append(": ").Append(renderer.name)
                    .Append(" bones=").Append(renderer.bones.Length)
                    .Append(" weighted=").Append(PlayerRigParts.DescribeBinding(renderer))
                    .Append(" materials=").Append(renderer.sharedMaterials.Length);
            }
        }
    }
}
