#nullable enable

using UnityEngine;
using UnityEngine.Animations;
using UnityEngine.Playables;

namespace HorrorGame.Gameplay.Player
{
    /// <summary>
    /// Owns both readings of a runner's arms: the viewmodel the owner sees, and the
    /// correction applied to the body everybody else sees.
    /// <para>
    /// <b>The problem this was written for.</b> §05 promises the owner sees their own
    /// hands, and at the 80° vertical FOV §05 specifies an arm hanging at hip height puts
    /// the fist 22° below the bottom edge of the frame. So <c>gen_player_model</c>'s
    /// <c>FREE_ARM</c> and <c>FLASHLIGHT_ARM</c> held both forearms up across the chest in
    /// every clip. That is correct for the one person inside the model and wrong for the
    /// three looking at it: from outside, the figure stands with both elbows flared and
    /// its hands up, permanently, doing nothing. This component rotated them back down,
    /// after the Animator, on rigs that are not the local player's.
    /// </para>
    /// <para>
    /// <b>#83 removes the disagreement instead of arbitrating it.</b> The first person is
    /// served by its own asset now — <c>RunnerArms.fbx</c>, sleeves and gloves cut at the
    /// shoulder, framed for this camera, generated by <c>gen_runner.py</c> from the body's
    /// own sleeve table and the body's own mocap. <c>Runner.fbx</c>'s clips are unedited
    /// motion capture and are posed for nobody. So there are two jobs here now:
    /// </para>
    /// <list type="number">
    /// <item><description><b>Play the viewmodel.</b> The arms carry their own eight clips,
    /// named exactly as the body's, and nothing else in the project plays them:
    /// <c>PlayerAnimatorDriver</c> owns one <c>Animator</c> and it is the body's. So this
    /// runs a second, much smaller Playables graph on the arms' own Animator and mirrors
    /// the driver's <see cref="PlayerAnimatorDriver.State"/> onto it — same state, same
    /// crossfade length, same playback scaling by ground speed. The clips it plays are
    /// the ones <see cref="PlayerFirstPersonView.FirstPersonArmClips"/> resolved out of
    /// the FBX at rig-build time, so the mesh and the motion are from one file.</description></item>
    /// <item><description><b>Keep the drop for remote bodies.</b> The correction stays,
    /// unchanged in behaviour and in default, because it is not this task's to retire: it
    /// is aimed at a shared clip set that holds the forearms up, and whether the shipped
    /// clips still do is a measurement on <c>Runner.fbx</c>, not an assumption. On mocap
    /// clips it should be dialled to zero — <see cref="Weight"/> is a serialised field
    /// exactly so a scene can say so without a code change — and until somebody measures
    /// it, changing the default here would move every remote body in nine saved scenes on
    /// the strength of an argument rather than a number.</description></item>
    /// </list>
    /// <para>
    /// Both halves read ownership from the same switch,
    /// <see cref="PlayerFirstPersonView.IsOwner"/>, so the arms the owner is given and the
    /// arms everybody else is given cannot disagree about whose body this is. That is also
    /// what makes third person work for free: <c>ThirdPersonCamera</c> flips that one flag
    /// and the viewmodel goes away while the body's arms come back.
    /// </para>
    /// </summary>
    [DisallowMultipleComponent]
    [RequireComponent(typeof(PlayerFirstPersonView))]
    [DefaultExecutionOrder(120)]
    public sealed class PlayerWorldArms : MonoBehaviour
    {
        /// <summary>Humanoid bone names this reaches. Left and right are handled together.</summary>
        public static readonly string[] ArmBones =
        {
            "LeftShoulder", "LeftUpperArm", "LeftLowerArm", "LeftHand",
            "RightShoulder", "RightUpperArm", "RightLowerArm", "RightHand",
        };

        [Tooltip("Rig root searched for the arm bones. Left empty, this transform.")]
        [SerializeField]
        private Transform? _rigRoot;

        [Tooltip("Degrees the upper arm is rotated down toward hanging. The clip's own swing is kept on top of this.")]
        [SerializeField]
        private float _upperArmDrop = 46f;

        [Tooltip("Degrees the forearm is unfolded. FREE_ARM's lo_down is -46, i.e. 46 degrees ABOVE horizontal — this is what takes it back down.")]
        [SerializeField]
        private float _forearmDrop = 62f;

        [Tooltip("0 leaves the clip pose alone, 1 applies the full drop. A dial rather than a bool so a pose that wants the arms up can keep them there. On Runner.fbx's unedited mocap the right value is 0 — nothing holds the forearms up any more — but that is a per-scene measurement, not a default to change here.")]
        [Range(0f, 1f)]
        [SerializeField]
        private float _weight = 1f;

        [Tooltip("Crossfade length for the first-person arms, seconds. The body's own default, so the hands and the body change pose over the same interval.")]
        [SerializeField]
        private float _blendSeconds = PlayerAnimatorDriver.DefaultBlendSeconds;

        private PlayerFirstPersonView? _view;
        private readonly Transform?[] _bones = new Transform?[8];
        private bool _found;

        private const int StateCount = 9;

        private PlayerAnimatorDriver? _driver;
        private PlayerMotor? _motor;
        private Animator? _armsAnimator;
        private PlayableGraph _graph;
        private AnimationMixerPlayable _mixer;
        private readonly AnimationClipPlayable[] _armClips = new AnimationClipPlayable[StateCount];
        private readonly bool[] _hasArmClip = new bool[StateCount];
        private readonly float[] _armWeights = new float[StateCount];
        private bool _armsGraphBuilt;
        private bool _driverSearched;
        private bool _reportedNoArmClips;

        /// <summary>How much of the drop is applied, 0~1. A carry state can dial it down.</summary>
        public float Weight
        {
            get { return _weight; }
            set { _weight = Mathf.Clamp01(value); }
        }

        /// <summary>True when every arm bone was found. False means this is doing nothing.</summary>
        public bool Bound
        {
            get
            {
                Collect();
                for (var i = 0; i < _bones.Length; i++)
                {
                    if (_bones[i] == null)
                    {
                        return false;
                    }
                }

                return true;
            }
        }

        /// <summary>
        /// True once the viewmodel's own animation graph is running. False means the arms
        /// are standing in their bind pose — which is the framed carry, not a T-pose, so
        /// the failure is "the hands do not move" and never "the hands are not there".
        /// </summary>
        public bool ArmsAnimated
        {
            get { return _armsGraphBuilt; }
        }

        /// <summary>
        /// Poses the viewmodel at one moment of one clip, without a graph.
        /// <para>
        /// Public for the same reason <see cref="Apply"/> is: <c>LateUpdate</c> does not
        /// run outside play mode, and the shot rigs pose the skeleton by sampling clips in
        /// the editor. <c>FirstPersonHandsShot</c> photographs what the owner sees; without
        /// this it would photograph the owner's hands frozen in the bind pose while the
        /// body behind them was mid-stride, which is a picture of nothing that happens.
        /// </para>
        /// </summary>
        /// <param name="state">The pose to sample, matched to the arms clip of the same name.</param>
        /// <param name="normalisedTime">Where in the clip, 0~1.</param>
        /// <returns>True when a clip for that state existed and was sampled.</returns>
        public bool SampleFirstPersonArms(PlayerAnimationState state, float normalisedTime)
        {
            var arms = ResolveArms();
            if (arms == null)
            {
                return false;
            }

            var clip = ArmClipFor(state);
            if (clip == null)
            {
                return false;
            }

            clip.SampleAnimation(arms.gameObject, Mathf.Repeat(normalisedTime, 1f) * clip.length);
            return true;
        }

        private void Start()
        {
            // Start, not Awake: PlayerFirstPersonView instantiates the arms from its own
            // Awake at order -90, and a graph built at order 120 in the same Awake pass
            // would still be racing it on a rig assembled by AddComponent at runtime.
            BuildArmsGraph();
        }

        private void OnDisable()
        {
            DestroyArmsGraph();
        }

        private void OnDestroy()
        {
            DestroyArmsGraph();
        }

        private void LateUpdate()
        {
            // After the Animator, which is the whole point: it has to overwrite a pose
            // that has already been written this frame, and DefaultExecutionOrder(120)
            // is what puts it there.
            Apply();
            DriveArms(Time.deltaTime);
        }

        /// <summary>
        /// Applies the drop once, over whatever pose is on the rig right now.
        /// <para>
        /// Public because <c>LateUpdate</c> does not run outside play mode and the film
        /// and shot rigs pose the skeleton by sampling clips in the editor. A tool that
        /// photographed the un-dropped arms would be photographing a pose no player ever
        /// sees, which is the class of mistake this whole component exists to end.
        /// </para>
        /// </summary>
        public void Apply()
        {
            Collect();

            _view ??= GetComponent<PlayerFirstPersonView>();
            if (_view == null || _view.IsOwner || _weight <= 0f)
            {
                return;
            }

            for (var side = 0; side < 2; side++)
            {
                // +1 on the left, −1 on the right. The arms leave the shoulders along ±X,
                // so the same world rotation drops one and raises the other; the sign is
                // what makes "down" mean down on both.
                var sign = side == 0 ? 1f : -1f;
                Drop(_bones[side * 4], _upperArmDrop * 0.18f, sign);   // shoulder
                Drop(_bones[side * 4 + 1], _upperArmDrop, sign);       // upper arm
                Drop(_bones[side * 4 + 2], _forearmDrop, sign);        // forearm
            }
        }

        /// <summary>
        /// Rotates one bone toward hanging, in world space.
        /// <para>
        /// World space rather than local on purpose: these bones are authored along ±X
        /// with per-bone rest orientations, and a local-space delta means a different
        /// direction on each one. Writing <c>Transform.rotation</c> lets Unity do the
        /// parent conversion, so what this file has to get right is one axis and one
        /// sign rather than eight rest frames.
        /// </para>
        /// <para>
        /// It composes with whatever the Animator wrote rather than replacing it, which
        /// is what keeps the walk's swing and the carry's strain.
        /// </para>
        /// </summary>
        private void Drop(Transform? bone, float degrees, float sign)
        {
            if (bone == null || degrees == 0f)
            {
                return;
            }

            // Rotating +X about +forward by +90° gives +up, so a NEGATIVE angle is the
            // one that takes the left arm down. The right arm points −X and needs the
            // opposite, which is the sign.
            var delta = Quaternion.AngleAxis(-degrees * _weight * sign, transform.forward);
            bone.rotation = delta * bone.rotation;
        }

        private void Collect()
        {
            if (_found)
            {
                return;
            }

            _found = true;
            var root = _rigRoot != null ? _rigRoot : transform;
            _view ??= GetComponent<PlayerFirstPersonView>();
            var arms = _view != null ? _view.FirstPersonArms : null;
            for (var i = 0; i < ArmBones.Length; i++)
            {
                _bones[i] = FindOutsideViewmodel(root, ArmBones[i], arms);
            }
        }

        /// <summary>
        /// <see cref="PlayerRigBones.Find"/>, with the viewmodel's subtree walled off.
        /// <para>
        /// <b>The rig has two <c>RightLowerArm</c>s now and that is not a mistake.</b> #83
        /// requires the arms asset to keep the body's bone names — everything on the C#
        /// side reaches a bone by string, and a second vocabulary would be a second thing
        /// to keep in sync — so <c>Runner.fbx</c>'s skeleton and <c>RunnerArms.fbx</c>'s
        /// share four names under one rig root. A depth-first search from that root
        /// currently returns the body's, because <c>PlayerFeelHarnessMenu.BuildRig</c>
        /// creates <c>Visual</c> before <c>PitchPivot</c> and the viewmodel hangs off the
        /// camera under the latter. That is a sibling ORDER, not a rule, and this component
        /// is the one whose whole job is to rotate those four bones — so it is not left
        /// resting on it. The drop belongs to the body somebody else is looking at, and
        /// applying it to the viewmodel would rotate the owner's own hands out of frame.
        /// </para>
        /// <para>
        /// Two other callers reach the same names from the same root and are left as they
        /// are, because they are not this file's to change: <c>RunnerGun.Mount</c> looks up
        /// <c>RightLowerArm</c> to hang <c>Gun_Held</c>, and its <c>MountOffset</c> then
        /// walks <c>Head</c> up to <c>Spine</c> — the arms rig has a <c>Spine</c> and no
        /// <c>Head</c>, so a mixed resolution would fall through to <c>Vector3.zero</c> and
        /// put the revolver at the elbow. Both are safe on today's hierarchy for the reason
        /// above; both would be safer pointed at the <c>Visual</c> child.
        /// </para>
        /// </summary>
        private static Transform? FindOutsideViewmodel(Transform? root, string bone, Transform? arms)
        {
            if (root == null || (arms != null && root == arms))
            {
                return null;
            }

            if (root.name == bone)
            {
                return root;
            }

            for (var i = 0; i < root.childCount; i++)
            {
                var found = FindOutsideViewmodel(root.GetChild(i), bone, arms);
                if (found != null)
                {
                    return found;
                }
            }

            return null;
        }

        /// <summary>The viewmodel's own Animator, or null on a rig that has no viewmodel.</summary>
        private Animator? ResolveArms()
        {
            if (_armsAnimator != null)
            {
                return _armsAnimator;
            }

            _view ??= GetComponent<PlayerFirstPersonView>();
            var arms = _view != null ? _view.FirstPersonArms : null;
            if (arms == null)
            {
                return null;
            }

            _armsAnimator = arms.GetComponentInChildren<Animator>(includeInactive: true);
            return _armsAnimator;
        }

        /// <summary>
        /// The arms clip for one pose, matched by NAME against the body's own clip names.
        /// <para>
        /// By name and not by index, for <c>PlayerFeelHarnessMenu.AssignClips</c>'s reason:
        /// an importer's order is not a contract, and <c>gen_runner.py</c>'s
        /// <c>verify_takes</c> asserts the eight names in the FBX rather than their
        /// positions. The two assets export the same eight names by construction —
        /// <c>CLIP_NAMES</c> is one tuple with two consumers — so a state that resolves to
        /// <c>Walk</c> on the body resolves to <c>Walk</c> here or to nothing at all.
        /// </para>
        /// </summary>
        private AnimationClip? ArmClipFor(PlayerAnimationState state)
        {
            _view ??= GetComponent<PlayerFirstPersonView>();
            if (_view == null)
            {
                return null;
            }

            var wanted = NameOf(state);
            var clips = _view.FirstPersonArmClips;
            for (var i = 0; i < clips.Count; i++)
            {
                AnimationClip? clip = clips[i];
                if (clip != null && string.Equals(clip.name, wanted, System.StringComparison.Ordinal))
                {
                    return clip;
                }
            }

            return null;
        }

        private static string NameOf(PlayerAnimationState state)
        {
            switch (state)
            {
                case PlayerAnimationState.Idle: return "Idle";
                case PlayerAnimationState.Walk: return "Walk";
                case PlayerAnimationState.Run: return "Run";
                case PlayerAnimationState.Crouch: return "Crouch";
                case PlayerAnimationState.CrouchWalk: return "CrouchWalk";
                case PlayerAnimationState.GunIdle: return "GunIdle";
                case PlayerAnimationState.GunWalk: return "GunWalk";
                case PlayerAnimationState.Death: return "Death";
                default: return string.Empty;
            }
        }

        /// <summary>
        /// Builds the viewmodel's mixer. A copy of <see cref="PlayerAnimatorDriver"/>'s
        /// shape and deliberately so — one input per <c>PlayerAnimationState</c>, indexed
        /// by the enum, so the two graphs cannot disagree about which slot is which pose
        /// and neither has to translate.
        /// </summary>
        private void BuildArmsGraph()
        {
            if (_armsGraphBuilt)
            {
                return;
            }

            var animator = ResolveArms();
            if (animator == null)
            {
                return;
            }

            var clips = _view != null ? _view.FirstPersonArmClips : null;
            if (clips == null || clips.Count == 0)
            {
                if (!_reportedNoArmClips)
                {
                    _reportedNoArmClips = true;
                    Debug.LogWarning(
                        "[Player] the first-person arms are in the scene but carry no clips, so "
                        + "they will hold their bind pose. That pose is the framed carry rather "
                        + "than a rest pose, so it is survivable — but nothing will move. The "
                        + "clips are resolved out of " + PlayerFirstPersonView.FirstPersonArmsModelPath
                        + " by PlayerFirstPersonView.EnsureFirstPersonArms and serialised with the "
                        + "rig; a scene saved before the asset existed has to be rebuilt.",
                        this);
                }

                return;
            }

            // Root motion off, for PlayerAnimatorDriver's reason twice over: the arms are
            // parented to the camera, so a clip that moved their root would drive the
            // viewmodel away from the eye it is authored around.
            animator.applyRootMotion = false;

            _graph = PlayableGraph.Create("FirstPersonArms:" + name);
            _graph.SetTimeUpdateMode(DirectorUpdateMode.GameTime);
            _mixer = AnimationMixerPlayable.Create(_graph, StateCount);

            for (var state = 0; state < StateCount; state++)
            {
                var clip = ArmClipFor((PlayerAnimationState)state);
                if (clip == null)
                {
                    continue;
                }

                _armClips[state] = AnimationClipPlayable.Create(_graph, clip);
                _armClips[state].SetApplyFootIK(false);
                _graph.Connect(_armClips[state], 0, _mixer, state);
                _mixer.SetInputWeight(state, 0f);
                _hasArmClip[state] = true;
            }

            var output = AnimationPlayableOutput.Create(_graph, "FirstPersonArms", animator);
            output.SetSourcePlayable(_mixer);

            var idle = (int)PlayerAnimationState.Idle;
            if (_hasArmClip[idle])
            {
                _armWeights[idle] = 1f;
                _mixer.SetInputWeight(idle, 1f);
            }

            _graph.Play();
            _armsGraphBuilt = true;
        }

        private void DestroyArmsGraph()
        {
            if (!_armsGraphBuilt)
            {
                return;
            }

            if (_graph.IsValid())
            {
                _graph.Destroy();
            }

            for (var i = 0; i < StateCount; i++)
            {
                _hasArmClip[i] = false;
                _armWeights[i] = 0f;
            }

            _armsGraphBuilt = false;
        }

        /// <summary>
        /// Mirrors the body's pose onto the viewmodel: same state, same crossfade, same
        /// playback scaling by ground speed.
        /// <para>
        /// The <em>state</em> is mirrored rather than the clip time, and the difference is
        /// worth being honest about. <c>PlayerAnimatorDriver</c> keeps its clip times
        /// private and there is no public way to read one, so the two graphs run their own
        /// cycles and a walk can be half a stride apart between the body and the hands.
        /// Nobody can see that: the two are never on screen together — the body is
        /// <c>ShadowsOnly</c> for its owner, and the viewmodel is switched off for
        /// everybody else — and both are driven from one state at one speed, so they start
        /// and stop together, which is the part a player can feel. What agrees exactly is
        /// the thing that had to: the arms' clips ARE the body's clips, retargeted from the
        /// same mixamo source at the same phase in the same run of the generator, damped
        /// about each clip's own mean. <c>gen_runner.py</c>'s <c>ARMS_MOTION_MATCH</c>
        /// measures that per bone per frame.
        /// </para>
        /// </summary>
        private void DriveArms(float deltaTime)
        {
            if (!_armsGraphBuilt)
            {
                BuildArmsGraph();
                if (!_armsGraphBuilt)
                {
                    return;
                }
            }

            if (!_driverSearched)
            {
                _driverSearched = true;
                _driver = GetComponent<PlayerAnimatorDriver>()
                    ?? GetComponentInChildren<PlayerAnimatorDriver>();
            }

            var state = _driver != null ? _driver.State : PlayerAnimationState.Idle;
            var index = (int)state;
            if (!_hasArmClip[index])
            {
                // No clip for the pose the body is in. Hold whatever the arms are already
                // blended to rather than snapping to nothing: a viewmodel that vanishes
                // mid-frame is worse than one that lags a state behind.
                return;
            }

            var step = _blendSeconds > 0f ? deltaTime / _blendSeconds : 1f;
            var total = 0f;
            for (var i = 0; i < StateCount; i++)
            {
                if (!_hasArmClip[i])
                {
                    continue;
                }

                var target = i == index ? 1f : 0f;
                _armWeights[i] = Mathf.MoveTowards(_armWeights[i], target, step);
                total += _armWeights[i];
            }

            if (total <= 0f)
            {
                return;
            }

            for (var i = 0; i < StateCount; i++)
            {
                if (_hasArmClip[i])
                {
                    _mixer.SetInputWeight(i, _armWeights[i] / total);
                }
            }

            // The same rule the body plays by: a locomotion clip is authored at one speed
            // and scaled to the speed actually being travelled, or the hands swing at a
            // cadence the feet are not keeping.
            _motor ??= GetComponent<PlayerMotor>();
            var ground = _motor != null ? _motor.GroundSpeed : 0f;
            var reference = PlayerAnimatorDriver.ReferenceSpeed(state);
            var speed = reference > 0f ? ground / reference : 1f;
            _armClips[index].SetSpeed(speed > 0f ? speed : 0f);
        }
    }
}
