#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using HorrorGame.Core;
using HorrorGame.Core.Threat;
using HorrorGame.Rendering;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;

namespace HorrorGame.EditorTools.Rendering
{
    /// <summary>
    /// Turns the render pipeline into the one this game needs: linear lighting, a
    /// Forward+ path, flashlight shadows, and a graded, fogged, vignetted frame.
    /// <para>
    /// <see cref="RenderPipelineSetup"/> made URP the active pipeline, which is
    /// necessary and not nearly sufficient. A freshly created
    /// <see cref="UniversalRendererData"/> ships with <c>postProcessData</c> null,
    /// and URP reads that as "post processing is disabled" — every Volume in the
    /// project is then silently ignored. It also ships with additional-light
    /// shadows off, which means the flashlight, a spot light, casts none: §03
    /// builds the whole game on a beam, and a beam that passes through a crate is
    /// the fastest way to tell a player they are looking at a tech demo.
    /// </para>
    /// <para>
    /// Written against serialized property names rather than the C# API because
    /// most of these fields are get-only or internal-set on
    /// <see cref="UniversalRenderPipelineAsset"/>; the alternative is asking a
    /// human to click through the inspector, which is not a thing a repository can
    /// verify.
    /// </para>
    /// </summary>
    public static class AtmosphereSetup
    {
        private const string SettingsFolder = "Assets/Settings";
        private const string PipelineAssetPath = SettingsFolder + "/HorrorGame_URP.asset";
        private const string RendererDataPath = SettingsFolder + "/HorrorGame_URP_Renderer.asset";
        private const string VolumeProfilePath = SettingsFolder + "/HorrorGame_Volume.asset";
        private const string NightSkyPath = SettingsFolder + "/HorrorGame_NightSky.mat";

        private const string PostProcessDataPath =
            "Packages/com.unity.render-pipelines.universal/Runtime/Data/PostProcessData.asset";

        /// <summary>
        /// Configures pipeline, renderer, grade and project colour space, then
        /// writes the 초저녁 environment into every map scene.
        /// </summary>
        [MenuItem("Horror/Setup/Configure Atmosphere", priority = 15)]
        public static void Configure()
        {
            var log = new List<string>();

            log.Add(ConfigureColorSpace());
            log.Add(ConfigurePipeline());
            log.Add(ConfigureRenderer());
            log.Add(ConfigureVolumeProfile());
            log.Add(ConfigureNightSky());

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            Debug.Log("[Atmosphere] " + string.Join("\n  ", log));
        }

        /// <summary>
        /// Batch entry point.
        /// <code>
        /// Unity -batchmode -quit -projectPath . -executeMethod HorrorGame.EditorTools.Rendering.AtmosphereSetup.Batch [-atmoTier 0]
        /// </code>
        /// </summary>
        public static void Batch()
        {
            try
            {
                Configure();
                ApplyEnvironmentToMapScenes(TierArg());
                EditorApplication.Exit(0);
            }
            catch (Exception ex)
            {
                Debug.LogError("[Atmosphere] " + ex);
                EditorApplication.Exit(1);
            }
        }

        /// <summary>
        /// Renders review shots of one §07 row without writing to any scene.
        /// <code>
        /// Unity -batchmode -quit -projectPath . -executeMethod HorrorGame.EditorTools.Rendering.AtmosphereSetup.ShotBatch -shotScene &lt;path&gt; -shotTag &lt;tag&gt; -atmoTier 0
        /// </code>
        /// <para>
        /// Exists because the map is regenerated by another tool that writes its
        /// own placeholder ambience, so a shot taken straight after a regeneration
        /// shows neither the old atmosphere nor the new one reliably. Applying the
        /// environment in memory first makes a render reproducible, and skipping
        /// the save means iterating on the grade never touches the map asset.
        /// It also renders a specific §07 tier, which is the only way to review
        /// "the night gets worse" as a picture rather than as a table.
        /// </para>
        /// </summary>
        public static void ShotBatch()
        {
            try
            {
                var scenePath = ArgValue("-shotScene") ?? "Assets/Scenes/Map_FirstSketch.unity";
                var tag = ArgValue("-shotTag") ?? "atmo";
                var tier = TierArg();

                var scene = EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);
                NightAtmosphere.ApplyEnvironment(NightAtmosphere.ForTier(tier));
                ApplySkybox();
                WindClockTo(tier);

                var shots = SceneShot.Capture(scene, tag);
                Debug.Log("[Atmosphere] §07 tier " + tier + ": wrote " + shots.Count + " shot(s).");
                EditorApplication.Exit(0);
            }
            catch (Exception ex)
            {
                Debug.LogError("[Atmosphere] " + ex);
                EditorApplication.Exit(1);
            }
        }

        /// <summary>
        /// Bakes one §07 row's ambient and fog into every scene under
        /// <c>Assets/Scenes</c> whose name starts with <c>Map_</c>, and puts a
        /// <see cref="ThreatAtmosphereDirector"/> in each.
        /// <para>
        /// Ambient and fog are scene state — URP has no fog Volume override and
        /// ambient is a lighting setting — so unlike the grade they cannot be set
        /// once for the project. Re-run this after regenerating a map: the
        /// generator writes its own placeholder ambience and this replaces it.
        /// </para>
        /// </summary>
        public static void ApplyEnvironmentToMapScenes(int tierIndex)
        {
            var settings = NightAtmosphere.ForTier(tierIndex);
            var touched = new List<string>();

            foreach (var guid in AssetDatabase.FindAssets("t:Scene", new[] { "Assets/Scenes" }))
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                if (!System.IO.Path.GetFileName(path).StartsWith("Map_", StringComparison.Ordinal))
                {
                    continue;
                }

                var scene = EditorSceneManager.OpenScene(path, OpenSceneMode.Single);
                NightAtmosphere.ApplyEnvironment(settings);
                ApplySkybox();
                EnsureDirector();
                EditorSceneManager.MarkSceneDirty(scene);
                EditorSceneManager.SaveScene(scene);
                touched.Add(path);
            }

            Debug.Log("[Atmosphere] §07 tier " + tierIndex + " environment written to " + touched.Count
                + " scene(s):\n  " + string.Join("\n  ", touched)
                + "\n  fog exp2 density " + settings.FogDensity.ToString("0.0000")
                + " (half-visibility at " + GameConstants.LineOfSightBreakSpacingMax.ToString("0") + " m ×"
                + (settings.FogDensity / NightAtmosphere.FogDensityEarlyEvening).ToString("0.00") + ")");
        }

        /// <summary>
        /// Builds the night sky the courtyard sees.
        /// <para>
        /// Unity's default procedural sky is a clear daytime atmosphere, and fog
        /// does not touch the skybox, so an open zone got a clean bright gradient
        /// above dark brick — the frame read as dusk outdoors rather than as a
        /// building at night, and the sky was reliably the brightest thing on
        /// screen. §12 puts open space next to maze space on purpose ("두 성격의
        /// 공간이 인접해야 한다"), so the courtyard is not a corner case to ignore.
        /// </para>
        /// <para>
        /// Dark, but deliberately not black: the roof line has to silhouette
        /// against something or the open zone loses the one depth cue it has that
        /// the corridors do not. No sun disk — §07's night has no moon in it and a
        /// disk would put a hard shadow direction on a building lit only by
        /// flashlights.
        /// </para>
        /// </summary>
        private static string ConfigureNightSky()
        {
            var shader = Shader.Find("Skybox/Procedural");
            if (shader == null)
            {
                return "night sky: Skybox/Procedural not found, left alone.";
            }

            var material = AssetDatabase.LoadAssetAtPath<Material>(NightSkyPath);
            if (material == null)
            {
                material = new Material(shader);
                AssetDatabase.CreateAsset(material, NightSkyPath);
            }

            material.shader = shader;
            material.SetFloat("_SunDisk", 0f);
            material.SetFloat("_SunSize", 0f);
            material.SetFloat("_AtmosphereThickness", 0.35f);
            material.SetColor("_SkyTint", new Color(0.32f, 0.38f, 0.52f));
            material.SetColor("_GroundColor", new Color(0.02f, 0.02f, 0.028f));
            material.SetFloat("_Exposure", 0.22f);

            EditorUtility.SetDirty(material);
            return "night sky: " + NightSkyPath;
        }

        /// <summary>
        /// Moves the open scene's <see cref="ThreatAtmosphereDirector"/> to the
        /// moment §07 row <paramref name="tierIndex"/> begins.
        /// <para>
        /// Without this a tier-4 review shot was a lie by omission: the
        /// environment was 동트기 전 but the director, still sitting at zero
        /// seconds, was pushing the 초저녁 grade over the top of it at a higher
        /// priority. The comparison showed a fifth of the real difference, which
        /// is exactly how a feature gets declared working and shipped broken.
        /// </para>
        /// </summary>
        private static void WindClockTo(int tierIndex)
        {
            var director = UnityEngine.Object.FindFirstObjectByType<ThreatAtmosphereDirector>(FindObjectsInactive.Include);
            if (director != null)
            {
                director.ElapsedSeconds = ThreatCurve.Tier(tierIndex).StartSeconds;
            }
        }

        /// <summary>Points the open scene at the night sky, if one has been built.</summary>
        private static void ApplySkybox()
        {
            var material = AssetDatabase.LoadAssetAtPath<Material>(NightSkyPath);
            if (material != null)
            {
                RenderSettings.skybox = material;
            }
        }

        /// <summary>
        /// Puts a <see cref="ThreatAtmosphereDirector"/> in the open scene if it
        /// has none.
        /// <para>
        /// Without one the map renders permanently at 초저녁, because the default
        /// Volume profile is the only thing grading it. §07's night would then be
        /// invisible in play — the grade would be correct and static, which is the
        /// hardest kind of missing feature to notice.
        /// </para>
        /// </summary>
        private static void EnsureDirector()
        {
            if (UnityEngine.Object.FindFirstObjectByType<ThreatAtmosphereDirector>(FindObjectsInactive.Include) != null)
            {
                return;
            }

            var go = new GameObject("[Atmosphere]");
            go.AddComponent<ThreatAtmosphereDirector>();
        }

        // ====================================================================
        // Colour space.
        // ====================================================================

        /// <summary>
        /// Forces linear colour space.
        /// <para>
        /// Not a preference. In gamma space Unity adds light in gamma-encoded
        /// units, so a beam at half brightness lands nowhere near half the energy
        /// and falloff over §03's 12 m cone comes out flat and plastic. Worse for
        /// this job specifically: a tonemapper is a curve applied to *linear*
        /// radiance, so ACES or Neutral in gamma space grades an already-encoded
        /// image and returns the washed, milky look people mistake for "the
        /// tonemapper is wrong". Every value below — exposure, fog, ambient — was
        /// tuned expecting linear, and none of them mean anything without it.
        /// </para>
        /// </summary>
        private static string ConfigureColorSpace()
        {
            if (PlayerSettings.colorSpace == ColorSpace.Linear)
            {
                return "colour space: already Linear.";
            }

            PlayerSettings.colorSpace = ColorSpace.Linear;
            return "colour space: Gamma → Linear (forces a texture reimport; expected).";
        }

        // ====================================================================
        // Pipeline asset.
        // ====================================================================

        private static string ConfigurePipeline()
        {
            var asset = AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(PipelineAssetPath);
            if (asset == null)
            {
                RenderPipelineSetup.Configure();
                asset = AssetDatabase.LoadAssetAtPath<UniversalRenderPipelineAsset>(PipelineAssetPath);
            }

            if (asset == null)
            {
                throw new InvalidOperationException("No pipeline asset at " + PipelineAssetPath
                    + ". Run Horror ▸ Setup ▸ Configure URP Render Pipeline first.");
            }

            var so = new SerializedObject(asset);
            var missing = new List<string>();

            SetBool(so, "m_SupportsHDR", true, missing);
            SetInt(so, "m_MSAA", 4, missing);
            SetInt(so, "m_ColorGradingMode", 1, missing);          // HighDynamicRange
            SetInt(so, "m_ColorGradingLutSize", 32, missing);

            // §03's flashlight is a spot light, which URP counts as an "additional"
            // light. With this off it lights the scene and casts nothing — the beam
            // goes through crates, doors and players. This single flag is the
            // difference between a light and a torch.
            SetBool(so, "m_AdditionalLightShadowsSupported", true, missing);
            SetInt(so, "m_AdditionalLightsShadowmapResolution", 4096, missing);
            SetInt(so, "m_AdditionalLightsShadowResolutionTierLow", 512, missing);
            SetInt(so, "m_AdditionalLightsShadowResolutionTierMedium", 1024, missing);
            SetInt(so, "m_AdditionalLightsShadowResolutionTierHigh", 2048, missing);

            SetBool(so, "m_SoftShadowsSupported", true, missing);
            SetInt(so, "m_SoftShadowQuality", 2, missing);         // Medium

            // §12 sizes the world: a zone's diagonal runs to
            // ZoneDiagonalMax, and a zone light (ZoneLightRadius) at one corner of
            // an open hall must still throw a correct shadow at the other. Past
            // that distance the fog has taken most of the contrast anyway, so
            // shadow map resolution spent there buys nothing.
            SetFloat(so, "m_ShadowDistance", GameConstants.ZoneDiagonalMax, missing);
            SetInt(so, "m_ShadowCascadeCount", 2, missing);
            SetFloat(so, "m_Cascade2Split", 0.25f, missing);
            SetFloat(so, "m_ShadowDepthBias", 0.9f, missing);
            SetFloat(so, "m_ShadowNormalBias", 0.7f, missing);

            // Forward+ is the reason §13 chose URP, and until now the renderer was
            // on plain Forward — see ConfigureRenderer. Under Forward+ this limit
            // is ignored entirely; it is raised anyway so the fallback path does
            // not drop lights the moment four players stand in one corridor with a
            // flare burning (§03's light sources are cumulative by design).
            SetInt(so, "m_AdditionalLightsPerObjectLimit", 8, missing);
            SetInt(so, "m_AdditionalLightsRenderingMode", 1, missing);   // PerPixel

            // Rendering layers cost nothing while every light and renderer stays on
            // the default layer, and they are the only lever that can later stop a
            // Flare from re-lighting a zone two rooms away. Enabled now so the
            // shader variants exist before anyone needs them.
            SetBool(so, "m_SupportsLightLayers", true, missing);
            SetBool(so, "m_SupportsLightCookies", true, missing);

            so.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(asset);

            return "pipeline: HDR, MSAA 4, HDR grading, additional-light soft shadows on, shadow distance "
                + GameConstants.ZoneDiagonalMax.ToString("0") + " m (§12 zone diagonal)"
                + (missing.Count > 0 ? "  [unknown fields: " + string.Join(", ", missing) + "]" : string.Empty);
        }

        // ====================================================================
        // Renderer data.
        // ====================================================================

        private static string ConfigureRenderer()
        {
            var data = AssetDatabase.LoadAssetAtPath<UniversalRendererData>(RendererDataPath);
            if (data == null)
            {
                throw new InvalidOperationException("No renderer data at " + RendererDataPath + ".");
            }

            var postProcess = AssetDatabase.LoadAssetAtPath<PostProcessData>(PostProcessDataPath);
            if (postProcess == null)
            {
                throw new InvalidOperationException(
                    "URP's PostProcessData is not at " + PostProcessDataPath
                    + ". Without it URP disables post processing outright and every Volume in the project does nothing.");
            }

            var so = new SerializedObject(data);
            var missing = new List<string>();

            // RenderingMode.ForwardPlus == 2. Classic Forward caps how many lights
            // can touch one object; §03 routinely has four flashlights, a zone
            // light and a flare live at once, and the cap does not fail loudly — it
            // just drops the lights furthest from each object's centre, so lighting
            // pops as players walk. Forward+ clusters instead and has no cap.
            SetInt(so, "m_RenderingMode", 2, missing);
            SetObject(so, "postProcessData", postProcess, missing);

            so.ApplyModifiedPropertiesWithoutUndo();

            var ssao = EnsureAmbientOcclusion(data);

            EditorUtility.SetDirty(data);

            return "renderer: Forward+, post-process resources assigned, " + ssao
                + (missing.Count > 0 ? "  [unknown fields: " + string.Join(", ", missing) + "]" : string.Empty);
        }

        /// <summary>
        /// Adds screen-space ambient occlusion if it is not already there.
        /// <para>
        /// The ambient term is what lets a player read shape outside the beam
        /// (§03), and a flat ambient term is exactly what makes a corridor look
        /// like a diagram — every surface returns the same value regardless of how
        /// enclosed it is. AO puts that value back under control: corners, the
        /// join between wall and floor, and the underside of anything resting on
        /// the ground go dark, which is most of what "believable basement" means
        /// before a single texture exists.
        /// </para>
        /// </summary>
        private static string EnsureAmbientOcclusion(UniversalRendererData data)
        {
            var existing = data.rendererFeatures
                .FirstOrDefault(f => f != null && f is ScreenSpaceAmbientOcclusion) as ScreenSpaceAmbientOcclusion;

            if (existing == null)
            {
                var feature = ScriptableObject.CreateInstance<ScreenSpaceAmbientOcclusion>();
                feature.name = "ScreenSpaceAmbientOcclusion";
                AssetDatabase.AddObjectToAsset(feature, data);
                AssetDatabase.SaveAssets();

                var so = new SerializedObject(data);
                var features = so.FindProperty("m_RendererFeatures");
                var map = so.FindProperty("m_RendererFeatureMap");
                var index = features.arraySize;

                features.InsertArrayElementAtIndex(index);
                features.GetArrayElementAtIndex(index).objectReferenceValue = feature;

                // The map holds each feature's local file id. URP validates the two
                // lists against each other on load and quietly disables features it
                // cannot match, which looks exactly like "AO does nothing".
                map.InsertArrayElementAtIndex(index);
                if (AssetDatabase.TryGetGUIDAndLocalFileIdentifier(feature, out _, out long localId))
                {
                    map.GetArrayElementAtIndex(index).longValue = localId;
                }

                so.ApplyModifiedPropertiesWithoutUndo();
                existing = feature;
            }

            TuneAmbientOcclusion(existing);
            return "SSAO on";
        }

        private static void TuneAmbientOcclusion(ScriptableRendererFeature feature)
        {
            var so = new SerializedObject(feature);
            var missing = new List<string>();

            SetInt(so, "m_Settings.AOMethod", 1, missing);            // Interleaved gradient — cheaper, stable
            SetInt(so, "m_Settings.Source", 1, missing);              // DepthNormals
            SetInt(so, "m_Settings.NormalSamples", 1, missing);       // Medium
            SetFloat(so, "m_Settings.Intensity", 1.6f, missing);
            SetFloat(so, "m_Settings.DirectLightingStrength", 0.15f, missing);
            SetFloat(so, "m_Settings.Radius", 0.28f, missing);
            SetFloat(so, "m_Settings.Falloff", 40f, missing);
            SetInt(so, "m_Settings.Samples", 1, missing);             // Medium
            SetInt(so, "m_Settings.BlurQuality", 0, missing);         // High
            SetBool(so, "m_Settings.Downsample", false, missing);
            SetBool(so, "m_Settings.AfterOpaque", false, missing);

            so.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(feature);
        }

        // ====================================================================
        // The grade.
        // ====================================================================

        /// <summary>
        /// Builds the project's default Volume profile and points URP at it.
        /// <para>
        /// The default profile, not a Volume in the map scene: a Volume lives in
        /// one scene and the lobby, the map and anything generated later all need
        /// the same film stock. It carries only what is constant all night —
        /// <see cref="ThreatAtmosphereDirector"/> layers §07's exposure,
        /// temperature, saturation and vignette on top of it at a higher priority.
        /// </para>
        /// <para>
        /// The tier-0 values here and the ones that component pushes come from the
        /// same <see cref="NightAtmosphere"/> table, so a scene with no director in
        /// it still looks like 초저녁 rather than like nothing.
        /// </para>
        /// </summary>
        private static string ConfigureVolumeProfile()
        {
            var profile = AssetDatabase.LoadAssetAtPath<VolumeProfile>(VolumeProfilePath);
            if (profile == null)
            {
                profile = ScriptableObject.CreateInstance<VolumeProfile>();
                AssetDatabase.CreateAsset(profile, VolumeProfilePath);
            }
            else
            {
                // Rebuild in place rather than deleting the asset: the GUID is
                // referenced from Graphics Settings, and a new one there is a
                // silent "no default profile" on someone else's machine.
                foreach (var component in profile.components.ToArray())
                {
                    if (component != null)
                    {
                        AssetDatabase.RemoveObjectFromAsset(component);
                        UnityEngine.Object.DestroyImmediate(component, allowDestroyingAssets: true);
                    }
                }

                profile.components.Clear();
            }

            var night = NightAtmosphere.ForTier(0);

            // Neutral, not ACES. ACES is the safer default for a bright game and
            // the wrong one here: its toe crushes everything below about 2% into
            // identical black, and 2% is where this entire game lives — the whole
            // brief is that a player must read shape *outside* the beam. Neutral
            // keeps the low end separable and still rolls the beam's hot core off
            // instead of clipping it to white.
            var tonemapping = Add<Tonemapping>(profile);
            tonemapping.mode.value = TonemappingMode.Neutral;

            var colour = Add<ColorAdjustments>(profile);
            colour.postExposure.value = night.PostExposure;
            colour.contrast.value = night.Contrast;
            colour.saturation.value = night.Saturation;
            colour.colorFilter.value = new Color(0.90f, 0.95f, 1.0f);

            // §03 hangs the game on a warm torch in a cold building, and that
            // reading only exists if the two are different temperatures. Cooling
            // the whole frame is what makes the unchanged beam read as warm — a
            // cheaper and steadier trick than tinting the light itself, which
            // would tint whatever it hits and lose the contrast at the edges.
            var whiteBalance = Add<WhiteBalance>(profile);
            whiteBalance.temperature.value = night.Temperature;
            whiteBalance.tint.value = -6f;

            // The same idea split by luminance, and this is the override that
            // actually delivers §03's reading. Everything dark goes blue and
            // everything bright goes amber, so the only warm thing on screen is
            // whatever the beam is touching. Doing it here rather than by tinting
            // the flashlight matters: a warm light tints the surface it hits and
            // then the surrounding falloff is warm too, which loses the edge. A
            // luminance split keeps the boundary exactly at the edge of the pool.
            var smh = Add<ShadowsMidtonesHighlights>(profile);
            smh.shadows.value = new Vector4(0.86f, 0.93f, 1.14f, 0f);
            smh.midtones.value = new Vector4(0.98f, 1.0f, 1.04f, 0f);
            smh.highlights.value = new Vector4(1.20f, 1.05f, 0.80f, 0f);
            smh.shadowsStart.value = 0f;
            smh.shadowsEnd.value = 0.30f;
            smh.highlightsStart.value = 0.45f;
            smh.highlightsEnd.value = 1.0f;

            // Restraint on purpose. Bloom exists so the entrance lamp and the beam
            // hitting a wall glow slightly, which is what a real lens does in a
            // dark room; the threshold keeps it off everything else. Overdone
            // bloom in a dark game reads as fog on the lens, and we already have
            // fog. The threshold has to sit below where the graded beam lands or
            // bloom silently does nothing at all — which it did until the exposure
            // was set properly.
            var bloom = Add<Bloom>(profile);
            bloom.threshold.value = 0.55f;
            bloom.intensity.value = 0.65f;
            bloom.scatter.value = 0.68f;
            bloom.tint.value = new Color(1f, 0.95f, 0.88f);
            bloom.highQualityFiltering.value = true;

            var vignette = Add<Vignette>(profile);
            vignette.color.value = Color.black;
            vignette.intensity.value = night.VignetteIntensity;
            vignette.smoothness.value = 0.45f;
            vignette.rounded.value = false;

            // Grain does real work here rather than being a nostalgia filter: an
            // 8-bit frame this dark bands visibly across a fog gradient, and grain
            // dithers the banding away. Response is high so it stays in the
            // shadows and leaves the beam clean.
            var grain = Add<FilmGrain>(profile);
            grain.type.value = FilmGrainLookup.Medium1;
            grain.intensity.value = 0.22f;
            grain.response.value = 0.85f;

            // Small enough to be deniable. §05 puts the player in a helmet-narrow
            // view; a little edge fringing sells a cheap lens. Anything stronger
            // and it reads as a filter someone switched on.
            var aberration = Add<ChromaticAberration>(profile);
            aberration.intensity.value = 0.09f;

            EditorUtility.SetDirty(profile);
            AssetDatabase.SaveAssets();

            AssignDefaultProfile(profile);

            return "grade: " + profile.components.Count + " overrides in " + VolumeProfilePath
                + " (Neutral tonemap, exposure " + night.PostExposure.ToString("0.00")
                + " EV, saturation " + night.Saturation.ToString("0") + ")";
        }

        /// <summary>Adds one override with every parameter live — a default profile is the base state, so nothing in it may be left unset.</summary>
        private static T Add<T>(VolumeProfile profile)
            where T : VolumeComponent
        {
            var component = profile.Add<T>(overrides: true);
            component.name = typeof(T).Name;
            component.hideFlags = HideFlags.HideInHierarchy | HideFlags.HideInInspector;
            AssetDatabase.AddObjectToAsset(component, profile);
            return component;
        }

        private static void AssignDefaultProfile(VolumeProfile profile)
        {
            var settings = GraphicsSettings.GetRenderPipelineSettings<URPDefaultVolumeProfileSettings>();
            if (settings == null)
            {
                Debug.LogWarning("[Atmosphere] URP is not the active pipeline, so the default Volume profile was not assigned.");
                return;
            }

            settings.volumeProfile = profile;

            var globals = GraphicsSettings.GetSettingsForRenderPipeline<UniversalRenderPipeline>();
            if (globals != null)
            {
                EditorUtility.SetDirty(globals);
            }
        }

        // ====================================================================
        // Serialized-property helpers.
        // ====================================================================

        private static int TierArg() =>
            int.TryParse(ArgValue("-atmoTier"), out var tier) ? tier : 0;

        private static string? ArgValue(string flag)
        {
            var args = Environment.GetCommandLineArgs();
            for (var i = 0; i < args.Length - 1; i++)
            {
                if (string.Equals(args[i], flag, StringComparison.Ordinal))
                {
                    return args[i + 1];
                }
            }

            return null;
        }

        private static void SetBool(SerializedObject so, string path, bool value, List<string> missing)
        {
            var property = so.FindProperty(path);
            if (property == null)
            {
                missing.Add(path);
                return;
            }

            property.boolValue = value;
        }

        private static void SetInt(SerializedObject so, string path, int value, List<string> missing)
        {
            var property = so.FindProperty(path);
            if (property == null)
            {
                missing.Add(path);
                return;
            }

            property.intValue = value;
        }

        private static void SetFloat(SerializedObject so, string path, float value, List<string> missing)
        {
            var property = so.FindProperty(path);
            if (property == null)
            {
                missing.Add(path);
                return;
            }

            property.floatValue = value;
        }

        private static void SetObject(SerializedObject so, string path, UnityEngine.Object value, List<string> missing)
        {
            var property = so.FindProperty(path);
            if (property == null)
            {
                missing.Add(path);
                return;
            }

            property.objectReferenceValue = value;
        }
    }
}
