#nullable enable

using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;

namespace HorrorGame.UI
{
    /// <summary>
    /// Builds every widget the interface uses, in code.
    /// <para>
    /// There are no UI prefabs in this project and that is deliberate. The scenes
    /// are generated by the Editor layer, and a prefab reference is a thing that can
    /// go missing between a scene generator and a screen — a HUD that silently fails
    /// to show a battery is worse than no HUD at all, because the player only finds
    /// out in the dark. Constructing the hierarchy here means the only way a readout
    /// can be absent is for this code not to run.
    /// </para>
    /// <para>
    /// uGUI rather than UI Toolkit: <c>com.unity.ugui</c> is the package the project
    /// already carries, and world-anchored elements (a clue's progress ring sitting
    /// on the mark) are a <c>Canvas</c> away rather than a bridge away.
    /// </para>
    /// </summary>
    public static class UiFactory
    {
        private static Font? _fallbackFont;

        /// <summary>
        /// The font to draw with.
        /// <para>
        /// Prefers whatever the caller was given, so a scene can supply a face that
        /// carries the Korean the design document is written in. Falls back to the
        /// engine's built-in face, which always resolves in a player build — the HUD
        /// coming up in the wrong typeface is recoverable; the HUD not coming up is
        /// not.
        /// </para>
        /// </summary>
        public static Font? ResolveFont(Font? preferred)
        {
            if (preferred != null)
            {
                return preferred;
            }

            if (_fallbackFont == null)
            {
                // Renamed in Unity 2022.2; the older name is tried second so this keeps
                // working if the project is ever opened on an earlier editor.
                _fallbackFont = Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf")
                    ?? Resources.GetBuiltinResource<Font>("Arial.ttf");
            }

            return _fallbackFont;
        }

        /// <summary>
        /// A screen-space canvas that scales against <see cref="UiStyle.ReferenceResolution"/>.
        /// </summary>
        /// <param name="name">Object name, so a generated scene is readable in the hierarchy.</param>
        /// <param name="sortOrder">One of the <c>UiStyle.SortOrder*</c> values.</param>
        /// <param name="interactive">
        /// Whether the canvas accepts clicks. False for the HUD and the clue overlay:
        /// they are things the player reads while playing, and a raycaster on them
        /// would quietly eat clicks meant for the world.
        /// </param>
        public static Canvas CreateCanvas(string name, int sortOrder, bool interactive)
        {
            var go = new GameObject(name, typeof(RectTransform), typeof(Canvas), typeof(CanvasScaler));
            var canvas = go.GetComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvas.sortingOrder = sortOrder;

            var scaler = go.GetComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = UiStyle.ReferenceResolution;
            scaler.screenMatchMode = CanvasScaler.ScreenMatchMode.MatchWidthOrHeight;
            scaler.matchWidthOrHeight = 0.5f;

            if (interactive)
            {
                go.AddComponent<GraphicRaycaster>();
            }

            return canvas;
        }

        /// <summary>An empty positioned rectangle.</summary>
        public static RectTransform CreateRect(string name, Transform parent)
        {
            var go = new GameObject(name, typeof(RectTransform));
            var rect = (RectTransform)go.transform;
            rect.SetParent(parent, false);
            return rect;
        }

        /// <summary>Makes a rectangle fill its parent.</summary>
        public static RectTransform Stretch(RectTransform rect)
        {
            rect.anchorMin = Vector2.zero;
            rect.anchorMax = Vector2.one;
            rect.offsetMin = Vector2.zero;
            rect.offsetMax = Vector2.zero;
            return rect;
        }

        /// <summary>Pins a rectangle to one anchor point with an explicit size.</summary>
        public static RectTransform Place(RectTransform rect, Vector2 anchor, Vector2 pivot, Vector2 position, Vector2 size)
        {
            rect.anchorMin = anchor;
            rect.anchorMax = anchor;
            rect.pivot = pivot;
            rect.anchoredPosition = position;
            rect.sizeDelta = size;
            return rect;
        }

        /// <summary>A flat coloured rectangle. <paramref name="raycastTarget"/> is false unless something is meant to be clicked.</summary>
        public static Image CreateImage(string name, Transform parent, Color color, bool raycastTarget = false)
        {
            var go = new GameObject(name, typeof(RectTransform), typeof(CanvasRenderer), typeof(Image));
            go.transform.SetParent(parent, false);
            var image = go.GetComponent<Image>();
            image.color = color;
            image.raycastTarget = raycastTarget;
            return image;
        }

        /// <summary>A line of text. Never a raycast target — labels are read, not pressed.</summary>
        public static Text CreateText(
            string name,
            Transform parent,
            Font? font,
            string value,
            int size,
            Color color,
            TextAnchor anchor)
        {
            var go = new GameObject(name, typeof(RectTransform), typeof(CanvasRenderer), typeof(Text));
            go.transform.SetParent(parent, false);
            var text = go.GetComponent<Text>();
            text.font = ResolveFont(font);
            text.text = value;
            text.fontSize = size;
            text.color = color;
            text.alignment = anchor;
            text.raycastTarget = false;
            text.horizontalOverflow = HorizontalWrapMode.Overflow;
            text.verticalOverflow = VerticalWrapMode.Overflow;
            return text;
        }

        /// <summary>A bed with a horizontal fill over it. See <see cref="UiBar"/> for why every meter is this shape.</summary>
        public static UiBar CreateBar(string name, Transform parent, float width = UiStyle.BarWidth, float height = UiStyle.BarHeight)
        {
            var root = CreateRect(name, parent);
            root.sizeDelta = new Vector2(width, height);

            var bed = CreateImage("Bed", root, UiStyle.BarBed);
            Stretch((RectTransform)bed.transform);

            // Anchor-driven, not Image.fillAmount.
            //
            // An Image with type Filled and NO SPRITE ignores fillAmount entirely:
            // Image.OnPopulateMesh falls through to Graphic's, which emits the whole
            // rect. Every meter in this game was built that way and therefore drew full
            // at every value — §03's battery, §06's twelve seconds of stamina, §03's
            // read progress. Nothing errored and each bar looked plausible, because a
            // full bar is what most of them show most of the time.
            //
            // Giving the Image a sprite would fix it and would add a runtime sprite
            // allocation to a layer that deliberately loads no assets. Moving the
            // fraction onto the RectTransform costs nothing, needs no sprite, and cannot
            // be silently disabled by a property somebody changes later.
            var fill = CreateImage("Fill", root, UiStyle.Calm);
            var fillRect = Stretch((RectTransform)fill.transform);
            fillRect.pivot = new Vector2(0f, 0.5f);

            return new UiBar(root, fill, fillRect);
        }

        /// <summary>
        /// A clickable row: a background image, a label, and a handler.
        /// <para>
        /// The caller keeps the returned <see cref="Button"/> so it can recolour the
        /// row and toggle <see cref="Selectable.interactable"/> — a shop row the team
        /// cannot afford stays visible and unpressable, because §08's negotiation
        /// happens over prices the team can see and not over a menu that hides them.
        /// </para>
        /// </summary>
        public static Button CreateButton(string name, Transform parent, Color background, UnityAction onClick)
        {
            var image = CreateImage(name, parent, background, true);
            var button = image.gameObject.AddComponent<Button>();
            button.targetGraphic = image;
            button.transition = Selectable.Transition.ColorTint;

            var colors = button.colors;
            colors.normalColor = Color.white;
            colors.highlightedColor = new Color(1.25f, 1.25f, 1.25f, 1f);
            colors.pressedColor = new Color(0.75f, 0.75f, 0.75f, 1f);
            colors.disabledColor = new Color(0.6f, 0.6f, 0.6f, 0.8f);
            button.colors = colors;

            button.onClick.AddListener(onClick);
            return button;
        }

        /// <summary>
        /// Makes sure clicks can reach a canvas built by <see cref="CreateCanvas"/>.
        /// <para>
        /// Guarded on the legacy input define because the module that reads the mouse
        /// depends on which input backend the project is configured for, and that
        /// setting belongs to the gameplay layer rather than to this one. With the new
        /// backend the scene supplies its own module and this does nothing.
        /// </para>
        /// </summary>
        public static void EnsureEventSystem()
        {
#if ENABLE_LEGACY_INPUT_MANAGER
            if (UnityEngine.EventSystems.EventSystem.current != null)
            {
                return;
            }

            var go = new GameObject("EventSystem", typeof(UnityEngine.EventSystems.EventSystem));
            go.AddComponent<UnityEngine.EventSystems.StandaloneInputModule>();
#endif
        }
    }
}
