#!/usr/bin/env python3
"""Turns an AI-generated base sculpt into a shippable monster: mesh, rig, clips.

Run headless::

    /Applications/Blender.app/Contents/MacOS/Blender --background --factory-startup \\
        --python tools/blender/gen_monster_ai.py

Writes ``Assets/Models/Characters/Monster.fbx`` — **the creature the game loads** —
with ``Monster.glb``, ``Monster.clips.json`` and ``Assets/Textures/Monster.textures.json``
alongside it. Those four names are the whole contract: ``MonsterRig.cs`` and
``MonsterSkin.cs`` hardcode them, so this generator is now the one that feeds them and
``gen_monster_model.py`` no longer writes a shipping asset.

Add ``-- --vessel`` to also build the human-shaped variant. It is deliberately NOT
written into ``Assets/``: it goes to ``artifacts/monster_variants/`` so it can be
looked at without becoming a second monster nobody is sure about. See VARIANTS.

WHY THIS EXISTS ALONGSIDE gen_monster_model.py
----------------------------------------------
``gen_monster_model.py`` builds its monster out of convex hulls and tubes. That is
reproducible and cheap to retune, and it is why the asset shipped at all — but it
cannot make a concave form. No sunken flank, no hollow between two ribs, no socket
where an eye is missing. Everything it produces is an assembly of bulges, and past a
certain distance that is exactly what it reads as.

So the base shape here is not built, it is **imported**: a sculpt generated by
Hyper3D Rodin from a text description of §01/§06's creature, committed under
``tools/blender/source/`` because that generation is not reproducible. Everything
downstream of the sculpt *is* reproducible, and that is what this file is:

    sculpt → decimate to budget → measure → fit the 29-bone rig → skin →
    grade the textures to §03's albedo policy → author the seven §06 clips → export

WHAT THE SCULPT DOES NOT ARRIVE WITH, AND WHY IT IS ADDED HERE
--------------------------------------------------------------
Rodin returns one closed surface and one material. The game does not render "one
surface" — it renders three channels that three different pieces of code drive, and a
sculpt dropped in with its single ``Monster_Hide`` silently disconnects two of them:

* ``MonsterSkin.EyeGlow`` lights whatever material is called ``Monster_Eyes``. That
  pair of lenses is §04's entire 관측자 channel at 15 m, where the body is forty pixels
  of smudge and two separated points are the only thing that still reads as a *facing*.
  With one material there is nowhere to put it, and lighting the one material lights
  the whole creature — which is §03's lock on progress handed back to the player.
* ``MonsterAcquireTell`` lights whatever material is called ``Monster_Maw`` when §06
  enters 추격. On a one-material creature that write either does nothing or turns the
  whole animal into a lantern.

So this file grows the lenses (``add_eyes``, placed by ray-casting the sculpt's own
head) and splits out the maw (``maw_polygons``, taken as the faces the ``Jaw`` bone
actually moves). Both are *derived from the sculpt*, because the previous attempt at
eyes on the hull monster used hand-written coordinates, put one lens 15 cm inside the
head, and the only symptom was that a brightness sweep from 1.5 to 12 moved the
measured frame by 0.0003.

WHAT IS LOAD-BEARING, AND WHY IT IS NOT NEGOTIABLE
--------------------------------------------------
The rig is a contract with code that already exists, not a free choice:

* ``MonsterAcquireTell.cs`` rotates ``Crest1..3`` and ``Jaw`` — that is §06's Alert
  tell, the thing §04's 관측자 is supposed to read at range. Bones alone are not
  enough: a crest bone with no crest on it animates nothing anybody can see, so this
  generator **adds crest geometry** to the sculpt rather than dropping the bones.
* ``MonsterRig.cs`` masks the Locomotion layer by bone name, ``Hips`` included.
* ``AssetImportValidator.cs`` asserts the rig is Generic and carries ``Jaw``,
  ``Crest1..3``, ``LeftScapulaSpur`` and ``Left/RightForearmExtra``, with the forearm
  extras *inside* the arm chain (UpperArm → LowerArm → ForearmExtra → Hand).
* ``AssetImportPolicy.MonsterHeightMetres`` pins the height at 2.336 m.

All 29 bone names therefore survive verbatim. What changes is where they sit: they
are fitted to whatever the sculpt actually is, by ``monster_fit.measure``.

THE ALBEDO POLICY IS THE OTHER CONTRACT
---------------------------------------
``Monster.textures.json`` records the rule the previous asset was tuned to, and it is
the least obvious and most important number here: the hide's mean albedo is **0.17
linear, deliberately under the 0.21 of the darkest wall in a §12 corridor**. A
creature brighter than its corridor announces itself, and §06 depends on you noticing
it too late. Rodin returns a sculpt lit for a turntable — bright, mid-grey, made to
look good on a white background. Shipping that unchanged would undo the whole policy,
so the maps are re-graded here and the result is asserted, not hoped for.
"""

from __future__ import annotations

import json
import math
import os
import sys
import traceback

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import bmesh  # noqa: E402
import bpy  # noqa: E402
import numpy as np  # noqa: E402
from mathutils import Matrix, Vector  # noqa: E402

import blendkit  # noqa: E402
import monster_fit  # noqa: E402
from blendkit import BoneSpec  # noqa: E402


FPS = 30
TARGET_HEIGHT = 2.336      # AssetImportPolicy.MonsterHeightMetres
TRI_BUDGET = 50000         # PC-only on Steam; see docs/ART.md — the old 6000 was a mobile number
TRI_TARGET = 46000         # headroom, because the crest is added after decimation
TEX_RES = 2048             # the monster's own allowance — docs/ART.md caps every set at
                           # 1024² "2048² only for the monster". The procedural dressing
                           # (craquelure, cavity wetness) is authored at this res and is
                           # what needs it; the baked 512² base is bilinear underneath.
CORRIDOR_DARKEST = 0.21    # linear albedo of the darkest §12 wall
ALBEDO_MEAN = 0.17         # what the hide must sit at: under the corridor, not over
ALBEDO_MAX = 0.2016
SHOULDER_LIMIT = 0.98      # §12 corridors — a hard constraint, not taste

# The pair is asymmetric on purpose — the 2026-08 shot review's first finding was
# that two equal round lenses on a smooth skull read as a cartoon robot, "almost
# cute". Production horror eyes are unequal: one sunken hooded socket, one hot
# pinpoint. §04 still gets its two separated points (the merge rule below holds
# them ≥5 cm apart); what dies is the symmetry.
SOCKET_RADIUS = 0.024      # creature's left: a shallow cap sunk into the face
PIN_RADIUS = 0.010         # creature's right: a bead, barely proud, reads as a point
EYE_MERGE_MIN = 0.05       # under 5 cm of separation the pair reads as one light

SOURCE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "source")

ARTIFACT_DIR = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "artifacts", "monster_variants")
"""Where a variant that is not the shipped monster goes. Outside Assets/ on purpose."""


EYE_MATERIAL = "Monster_Eyes"
"""``MonsterSkin.EyeMaterialName``. A contract, not a label — the constant emission
§04 reads the creature's facing from is applied to whatever material matches it."""

MAW_MATERIAL = "Monster_Maw"
"""``MonsterAcquireTell._mawMaterialName``. Same: §06's acquisition flare fires
``_EmissionColor`` on this slot and on no other, which is what keeps it from lighting
the whole creature."""


def material_names(variant: dict) -> dict:
    """The three material names this variant's mesh carries.

    Only the hide is per-variant. The lens and the jaw skin are the same on either
    sculpt, and the two names are fixed because Unity matches on them.
    """
    return {"hide": variant["material"], "eyes": EYE_MATERIAL, "maw": MAW_MATERIAL}

VARIANTS = (
    {
        "key": "creature",
        "source": "monster_creature_base.glb",
        # "Monster", not "Monster_Creature". The sculpt has been adopted, so it takes
        # the name every consumer already hardcodes — MonsterRig.ModelPath,
        # MonsterSkin.ManifestPath, AssetImportPolicy.ExpectedAnimationClipCount and
        # AssetImportPolicy.ResolveModelCategory's Generic-rig exception all say
        # "Monster". Shipping under a second name and repointing them would leave two
        # plausible monsters in Assets/Models/Characters and a reader with no way to
        # tell which one the game loads; that ambiguity is the thing being removed.
        "asset": "Monster",
        "ships": True,
        "material": "Monster_Hide",
        "crest": True,
        "note": "The §01 creature: clawed, digitigrade, nothing to make eye contact with.",
    },
    {
        "key": "vessel",
        "source": "monster_vessel_base.glb",
        "asset": "Monster_Vessel",
        # Not built unless asked for, and never into Assets/. It was the alternative
        # that was not chosen, and an unchosen asset sitting in the project is not
        # free: AssetImportValidator graded it against the humanoid player policy and
        # reported two failures on it on every single run, which is how a validator
        # stops being read. The sculpt and the code that fits it both survive here —
        # `--vessel` builds it into artifacts/ for eyeballing.
        "ships": False,
        "material": "Monster_Vessel_Hide",
        "crest": True,
        "note": "The human-shaped variant: it reads as something that used to be a person.",
    },
)


# ── Base mesh ───────────────────────────────────────────────────────────────


def load_base(path: str) -> bpy.types.Object:
    """Imports the sculpt, drops the importer's debris and normalises the transform.

    glTF import leaves a bone-display icosphere behind and parents the mesh under an
    empty. Both are stripped so what comes back is a single mesh at the origin with
    an identity matrix — every measurement downstream assumes that.
    """
    before = set(bpy.data.objects)
    bpy.ops.import_scene.gltf(filepath=path)
    added = [o for o in bpy.data.objects if o not in before]

    meshes = [o for o in added if o.type == "MESH" and not o.name.startswith("Icosphere")]
    if not meshes:
        blendkit.fail(f"{os.path.basename(path)} contains no mesh")
    obj = max(meshes, key=lambda o: len(o.data.vertices))

    for junk in added:
        if junk is not obj:
            bpy.data.objects.remove(junk, do_unlink=True)

    obj.matrix_world = Matrix.Identity(4)
    obj.parent = None
    return obj


def normalise(obj: bpy.types.Object) -> float:
    """Scales to the pinned height and plants the sculpt at the origin, feet on Z=0.

    Returns the scale factor it applied, so a caller that measured the mesh before a
    later normalise can bring its measurements forward.

    Works on mesh data rather than the object transform on purpose: ``transform_apply``
    is an operator, and operators silently do nothing when the context has no 3D view —
    which is exactly the case under ``--background``. A scale that quietly failed to
    apply would leave the asset at Rodin's normalised size and every measurement here
    would then be taken in the wrong units.
    """
    me = obj.data

    def bounds():
        lo = Vector((1e9,) * 3)
        hi = Vector((-1e9,) * 3)
        for v in me.vertices:
            for i in range(3):
                lo[i] = min(lo[i], v.co[i])
                hi[i] = max(hi[i], v.co[i])
        return lo, hi

    lo, hi = bounds()
    span = hi - lo
    if span.z < max(span.x, span.y):
        # Rodin returns Y-up. Everything here is Z-up, so stand it up first.
        me.transform(Matrix.Rotation(math.radians(90.0), 4, "X"))
        lo, hi = bounds()

    scale = TARGET_HEIGHT / (hi.z - lo.z)
    me.transform(Matrix.Scale(scale, 4))
    lo, hi = bounds()
    me.transform(Matrix.Translation(Vector((-(lo.x + hi.x) / 2.0,
                                            -(lo.y + hi.y) / 2.0,
                                            -lo.z))))
    me.update()
    return scale


def mesh_bounds(obj: bpy.types.Object) -> tuple[Vector, Vector]:
    """World-space bounds of what will actually be exported.

    The size assertions run off this rather than off the landmark dict. The landmarks
    are measured before decimation and before the crest is welded on, so they describe
    the sculpt that was analysed, not the asset that ships — and the height they carry
    would pass a check the exported mesh fails.
    """
    lo = Vector((1e9,) * 3)
    hi = Vector((-1e9,) * 3)
    for v in obj.data.vertices:
        w = obj.matrix_world @ v.co
        for i in range(3):
            lo[i] = min(lo[i], w[i])
            hi[i] = max(hi[i], w[i])
    return lo, hi


def triangles(obj: bpy.types.Object) -> int:
    obj.data.calc_loop_triangles()
    return len(obj.data.loop_triangles)


def decimate(obj: bpy.types.Object, target: int) -> None:
    """Collapses the sculpt down to the triangle budget, keeping the UV layout.

    Collapse rather than un-subdivide or planar: it is the only mode that treats the
    silhouette as the thing worth spending vertices on, and the silhouette is all this
    asset has in a dark corridor. UVs survive because Rodin's maps are baked to them —
    losing them would mean re-unwrapping and re-baking a sculpt this file did not make.
    """
    have = triangles(obj)
    if have <= target:
        return
    mod = obj.modifiers.new("Budget", "DECIMATE")
    mod.decimate_type = "COLLAPSE"
    mod.ratio = target / have
    mod.use_collapse_triangulate = True

    depsgraph = bpy.context.evaluated_depsgraph_get()
    baked = bpy.data.meshes.new_from_object(obj.evaluated_get(depsgraph))
    old = obj.data
    obj.data = baked
    obj.modifiers.remove(mod)
    bpy.data.meshes.remove(old)


# ── Rig ─────────────────────────────────────────────────────────────────────


def _lerp(a, b, t):
    return a + (b - a) * t


def _p(x, y, z):
    return (float(x), float(y), float(z))


def fit_bones(m: dict) -> list[BoneSpec]:
    """Places the 29 contractual bones on whatever the sculpt turned out to be.

    Every height comes from ``monster_fit.measure``; nothing is a fraction of the
    total height, because the two sculpts have genuinely different proportions — the
    creature's crotch sits 19 cm higher than the vessel's on the same 2.336 m frame,
    and a ratio tuned to either one dislocates the other.

    The four-segment arm is the one place geometry is invented rather than measured.
    ``AssetImportValidator`` requires ForearmExtra *inside* the chain, and a sculpt has
    one forearm, so the forearm is split in half: LowerArm takes the upper half,
    ForearmExtra the lower. Both lie along real geometry, which is what auto-weights
    need; the extra joint is free to bend where a person's cannot, which is the point.
    """
    crotch = m["crotch"]
    shoulder = m["shoulder"]
    neck = m["neck"]
    top = m["top"]
    height = m["height"]

    # The hip pivot rides above the crotch — that is where a femur head actually sits,
    # and putting Hips on the crotch itself makes the pelvis collapse when it rotates.
    hips_z = crotch + (shoulder - crotch) * 0.11
    chest_z = _lerp(hips_z, shoulder, 0.52)
    upper_chest_z = _lerp(hips_z, shoulder, 0.80)
    spine_z = _lerp(hips_z, chest_z, 0.45)
    head_z = _lerp(neck, top, 0.35)

    back = m["back_y"]
    front = m["front_y"]

    specs = [
        BoneSpec("Hips", _p(0, 0, hips_z), _p(0, 0, hips_z + height * 0.04)),
        BoneSpec("Spine", _p(0, 0, spine_z), _p(0, 0, chest_z), "Hips"),
        BoneSpec("Chest", _p(0, 0, chest_z), _p(0, 0, upper_chest_z), "Spine", True),
        BoneSpec("UpperChest", _p(0, 0, upper_chest_z), _p(0, 0, neck), "Chest", True),
        BoneSpec("Neck", _p(0, 0, neck), _p(0, m["head_y"] * 0.5, head_z), "UpperChest"),
        BoneSpec("Head", _p(0, m["head_y"] * 0.5, head_z), _p(0, m["head_y"], top), "Neck", True),
        # Points down and forward, so swinging it forward gapes the maw rather than
        # dropping a chin — the sculpt has no hinge, so the bone supplies the motion.
        BoneSpec("Jaw", _p(0, m["head_y"] * 0.8, head_z),
                 _p(0, front * 0.5, _lerp(neck, head_z, 0.15)), "Head"),
    ]

    # The dorsal crest: three chained blades rising off the back above the shoulders.
    # Their geometry is added by `add_crest`, which reads these same numbers.
    # Rooted between the shoulder blades, not on the skull. Run up by the head and the
    # fan ends up beside it, where the skull hides most of it from the front — and the
    # front is where §06 has the creature coming at you. From the upper back it clears
    # the silhouette on every side.
    c0 = (0.0, back * 0.70, _lerp(chest_z, upper_chest_z, 0.35))
    c1 = (0.0, back * 1.00, upper_chest_z + (neck - upper_chest_z) * 0.45)
    c2 = (0.0, back * 1.12, _lerp(neck, top, 0.18))
    c3 = (0.0, back * 1.18, _lerp(neck, top, 0.44))
    specs += [
        BoneSpec("Crest1", _p(*c0), _p(*c1), "UpperChest"),
        BoneSpec("Crest2", _p(*c1), _p(*c2), "Crest1", True),
        BoneSpec("Crest3", _p(*c2), _p(*c3), "Crest2", True),
        BoneSpec("LeftScapulaSpur",
                 _p(m["arm_x_shoulder"] * 0.62, back * 0.35, shoulder - height * 0.02),
                 _p(m["arm_x_shoulder"] * 0.95, back * 0.95, shoulder + height * 0.06),
                 "UpperChest"),
    ]

    elbow, wrist, tip = m["elbow"], m["wrist"], m["fingertip"]
    mid_forearm = _lerp(elbow, wrist, 0.5)
    ax_sh, ax_el, ax_wr = m["arm_x_shoulder"], m["arm_x_elbow"], m["arm_x_wrist"]
    ay_sh, ay_wr = m["arm_y_shoulder"], m["arm_y_wrist"]
    ax_mid = _lerp(ax_el, ax_wr, 0.5)

    knee, ankle = m["knee"], m["ankle"]
    lx_hip, lx_knee, lx_ank = m["leg_x_hip"], m["leg_x_knee"], m["leg_x_ankle"]
    heel_y, toe_y = m["heel_y"], m["toe_y"]
    ankle_y = _lerp(heel_y, toe_y, 0.32)
    ball_y = _lerp(heel_y, toe_y, 0.82)

    for side in (1, -1):
        s = "Left" if side > 0 else "Right"
        x = float(side)
        specs += [
            BoneSpec(f"{s}Shoulder", _p(x * ax_sh * 0.24, 0.0, shoulder),
                     _p(x * ax_sh, ay_sh, shoulder), "UpperChest"),
            BoneSpec(f"{s}UpperArm", _p(x * ax_sh, ay_sh, shoulder),
                     _p(x * ax_el, _lerp(ay_sh, ay_wr, 0.5), elbow), f"{s}Shoulder", True),
            BoneSpec(f"{s}LowerArm", _p(x * ax_el, _lerp(ay_sh, ay_wr, 0.5), elbow),
                     _p(x * ax_mid, _lerp(ay_sh, ay_wr, 0.75), mid_forearm),
                     f"{s}UpperArm", True),
            BoneSpec(f"{s}ForearmExtra",
                     _p(x * ax_mid, _lerp(ay_sh, ay_wr, 0.75), mid_forearm),
                     _p(x * ax_wr, ay_wr, wrist), f"{s}LowerArm", True),
            BoneSpec(f"{s}Hand", _p(x * ax_wr, ay_wr, wrist),
                     _p(x * ax_wr, ay_wr, tip), f"{s}ForearmExtra", True),
            BoneSpec(f"{s}UpperLeg", _p(x * lx_hip, 0.0, hips_z),
                     _p(x * lx_knee, 0.0, knee), "Hips"),
            BoneSpec(f"{s}LowerLeg", _p(x * lx_knee, 0.0, knee),
                     _p(x * lx_ank, ankle_y, ankle), f"{s}UpperLeg", True),
            BoneSpec(f"{s}Foot", _p(x * lx_ank, ankle_y, ankle),
                     _p(x * lx_ank, ball_y, ankle * 0.22), f"{s}LowerLeg", True),
            BoneSpec(f"{s}Toes", _p(x * lx_ank, ball_y, ankle * 0.22),
                     _p(x * lx_ank, toe_y, ankle * 0.10), f"{s}Foot", True),
        ]
    return specs


def add_crest(obj: bpy.types.Object, m: dict, specs: list[BoneSpec]) -> list[tuple]:
    """Grows a dorsal crest along the Crest1..3 bones and welds it onto the sculpt.

    §06's Alert state is the only moment the creature shows intent, and
    ``MonsterAcquireTell.cs`` shows it by flaring these three bones. A sculpt has no
    crest, so animating those bones would move nothing — the tell would exist in code
    and be invisible in play, which is worse than not having one, because the design
    then believes the player was warned.

    Built as a fan rather than a single fin: a fin disappears at the yaw the player
    almost always sees the creature from, and a tell nobody can see is decoration.
    Returns the (vertex-range, bone) pairs so the caller can weight them rigidly —
    auto-weights would bleed the crest onto the spine and it would stop reading.
    """
    by_name = {s.name: s for s in specs}
    me = obj.data
    ranges = []

    bm = bmesh.new()
    bm.from_mesh(me)
    bm.verts.ensure_lookup_table()

    # Anchored to the sculpt's actual back, sampled per height. Placing the blades at
    # a fraction of the torso's deepest point instead put them in mid-air behind the
    # neck — the back tapers between the shoulders and the skull, so one number taken
    # at the ribcage does not describe it. A crest that does not touch the creature
    # reads as a prop lying on it.
    verts_world = [obj.matrix_world @ v.co for v in obj.data.vertices]
    unit = m["height"]

    def back_at(z):
        band = [c.y for c in verts_world
                if abs(c.z - z) < unit * 0.035 and abs(c.x) < unit * 0.05]
        return max(band) if band else m["back_y"]

    for idx, name in enumerate(("Crest1", "Crest2", "Crest3")):
        spec = by_name[name]
        head, tail = Vector(spec.head), Vector(spec.tail)
        if (tail - head).length < 1e-6:
            continue
        y_base = back_at(head.z)
        y_tip = back_at(tail.z)
        inset = unit * 0.035        # how far the root is buried, so it never floats
        chord = unit * (0.105 - 0.022 * idx)
        reach = unit * (0.090 - 0.018 * idx)
        thick = unit * (0.013 - 0.002 * idx)
        start = len(bm.verts)

        # A centre blade plus one to each side of the lower two segments. A fan keeps
        # a readable outline at any yaw; a single fin vanishes when seen side-on, and
        # §04's 관측자 has to read this flare from wherever they happen to stand.
        blades = [(0.0, 1.0)] if idx == 2 else [(0.0, 1.0),
                                                (-unit * 0.048, 0.66),
                                                (unit * 0.048, 0.66)]
        for dx, scale in blades:
            t = thick * scale
            for sx in (-1.0, 1.0):
                ax = dx + sx * t
                bm.verts.new(Vector((ax, y_base - inset, head.z - unit * 0.012)))
                bm.verts.new(Vector((ax, y_base + chord * 0.55 * scale, head.z)))
                bm.verts.new(Vector((ax * 0.55,
                                     y_tip + reach * scale,
                                     head.z + (tail.z - head.z) * scale)))
        bm.verts.ensure_lookup_table()
        new = bm.verts[start:]
        if len(new) >= 4:
            bmesh.ops.convex_hull(bm, input=new)
        bm.verts.ensure_lookup_table()
        ranges.append((start, len(bm.verts), name))

    bmesh.ops.recalc_face_normals(bm, faces=bm.faces[:])
    bm.to_mesh(me)
    bm.free()
    me.update()
    return ranges


def add_eyes(obj: bpy.types.Object, m: dict) -> list[tuple]:
    """Grows the asymmetric lens pair on the front of the sculpt's head and welds it on.

    The pair is the whole of §04's channel at range. ``MonsterSkin.EyeGlow``'s own note
    puts it plainly: at ``GameConstants.ObserverRange`` the creature is about forty
    pixels tall, the crest is four of them, and two separated points are the only thing
    left that says both *there is something there* and *it is facing you*. §12 obliges
    every zone to hold 관측 지점 that make that readable at 15 m and says that without
    them 관측자는 죽으러 가야 한다, so this is a mechanic, not a highlight.

    The pair is UNEQUAL on purpose — a hooded socket sunk into the creature's left,
    a hot pinpoint bead on its right, staggered in height. Two equal round lenses at
    one height on a smooth skull was the 2026-08 shot review's first finding: it
    reads as a cartoon robot. §04 keeps its two points; what dies is the symmetry.

    **Found, never typed.** The same rule ``gen_monster_model.build_eyes_on`` arrived at
    the hard way, applied to a surface this file did not author. A ray is cast from in
    front of the creature at every candidate (height, x) across the head, and a hit only
    counts when the surface it lands on is actually facing the player — ``ray_cast``
    returns the frontmost surface, so that one test rejects the back of the skull, the
    inside of the mouth and anything the snout occludes. Each lens is then built at an
    authored depth against whatever surface its ray actually hit.

    **What "the best place" means, measured.** The hull generator took the widest hit
    that faced forward at all, and on two flat head blades that was the right answer. On
    a smooth ovoid skull it is not: the widest forward-facing point is where the surface
    has turned almost edge-on, and the first render put both lenses on the *sides* of the
    head, reading as a pair of ears. Both of the things §04 needs are being traded here —
    separation carries *which way it is looking*, and facing carries *whether you can see
    the lens at all*, since a lens on a surface tilted by θ presents cos θ of its area.
    So the score is ``x · (n · view)``, their product, maximised over every candidate.
    On a sphere that lands at 45°, which is unambiguously on the face and still near the
    edge of it; on a flat-faced sculpt it walks straight back out to the corner.

    Re-sculpt the head, or change the decimation ratio, and the eyes move onto the new
    surface instead of ending up inside it. The alternative was tried on the previous
    asset: a hand-picked coordinate put a lens 15 cm inside a 0.66 m deep head, the
    creature shipped with two slivers of glass peeping out of a solid wedge, and the
    only symptom was that sweeping the eye brightness from 1.5 to 12 moved the measured
    frame by 0.0003.

    Returns two lists of ``(start, end, bone)`` vertex ranges — the lenses, then the
    brow hood — so the caller can weight them rigidly to the head (proximity weighting
    would share a lens between Head and Jaw and the gape would tear it in half) and
    put only the lenses on the eye material.
    """
    depsgraph = bpy.context.evaluated_depsgraph_get()
    evaluated = obj.evaluated_get(depsgraph)

    # The sculpt faces -Y (monster_fit's `front_y` is a minimum), so the player stands
    # at -Y and the probe travels +Y into the face.
    forward = Vector((0.0, -1.0, 0.0))
    neck, top = m["neck"], m["top"]
    unit = m["height"]

    head = [obj.matrix_world @ v.co for v in obj.data.vertices if (obj.matrix_world @ v.co).z >= neck]
    if not head:
        blendkit.fail("no geometry above the measured neck — there is no head to put eyes on")
    half_width = max(abs(c.x) for c in head)
    start_y = min(c.y for c in head) - unit * 0.25      # clear of the frontmost point

    def probe(z, x):
        """Frontmost forward-facing surface at (x, z) and how squarely it faces, or None."""
        hit, location, normal, _ = evaluated.ray_cast(
            Vector((x, start_y, z)), -forward, distance=unit * 1.2)
        # 0.15 is gen_monster_model's threshold: enough of the normal pointing at the
        # camera that a lens set into it is seen, not seen edge-on.
        facing = normal.dot(forward) if hit else 0.0
        return (location, facing) if hit and facing > 0.15 else None

    step_x = unit * 0.004

    def search(lo_z: float, hi_z: float):
        step_z = max(unit * 0.004, (hi_z - lo_z) / 48.0)
        found_best = None
        z = lo_z
        while z <= hi_z:
            pair, score = [], 0.0
            for side in (1, -1):
                x, found, mark = unit * 0.010, None, 0.0
                while x <= half_width * 0.99:
                    probed = probe(z, side * x)
                    if probed is not None and x * probed[1] > mark:
                        found, mark = probed[0], x * probed[1]
                    x += step_x
                pair.append(found)
                score += mark

            if all(p is not None for p in pair) and (found_best is None
                                                     or score > found_best[0]):
                found_best = (score, z, pair)
            z += step_z
        return found_best

    # A face band, not the whole skull. The unrestricted search maximises x·facing and
    # on an ovoid skull that lands near the crown — the shot review's frog eyes. The
    # band is where a face's eye line actually sits, above the jaw (a lens on the jaw
    # is an eye that opens when the creature roars) and decisively below the crown.
    # The wide band is kept as a fallback so a re-sculpt whose face band is all snout
    # degrades to the old placement instead of failing the build.
    best = search(neck + (top - neck) * 0.30, neck + (top - neck) * 0.62)
    if best is None:
        best = search(neck + (top - neck) * 0.32, top - (top - neck) * 0.06)

    if best is None:
        blendkit.fail(
            "no forward-facing surface anywhere on the head to sit a pair of lenses on. §04's "
            "관측자 reads the creature's facing off the pair and §12 obliges every zone to hold "
            "관측 지점 that make that readable at 15 m; a head with nowhere to put them is a head "
            "that has to be re-sculpted, not shipped.")
        return [], []

    score, z, pair = best
    separation = abs(pair[0].x - pair[1].x)

    # Two lenses that have merged into one point carry no facing at all, which is half
    # of what the pair exists for.
    if separation < EYE_MERGE_MIN:
        blendkit.fail(f"the widest forward-facing pair on this head is {separation * 100:.1f} cm "
                      f"apart, which at ObserverRange merges into a single point — and the point "
                      f"of two lenses is the facing, not the glow.")

    me = obj.data
    bm = bmesh.new()
    bm.from_mesh(me)
    bm.verts.ensure_lookup_table()

    def hull_range(pts: list[Vector], bone: str, out: list[tuple]) -> None:
        start = len(bm.verts)
        for p in pts:
            bm.verts.new(p)
        bm.verts.ensure_lookup_table()
        if len(bm.verts) - start >= 4:
            bmesh.ops.convex_hull(bm, input=bm.verts[start:])
        bm.verts.ensure_lookup_table()
        out.append((start, len(bm.verts), bone))

    ranges: list[tuple] = []
    extra: list[tuple] = []
    left, right = pair          # pair[0] is +X — the creature's left

    # ── The socket: creature's left. A larger cap SUNK into the face and hooded. ──
    # Sunk 4.5 mm, so only a shallow sliver of lens breaks the surface — the glow
    # arrives dim and edge-broken. Raised 16 mm off the shared eye line, because two
    # eyes at one height is the symmetry being killed. Deliberate millimetres, not
    # the hand-typed-coordinate failure the docstring above recounts: the position
    # still comes from the ray hit; only the depth and stagger are authored.
    centre = left + forward * (-0.0045)
    centre.z += 0.016
    pts = []
    for i in range(8):
        angle = i * math.pi / 4.0
        pts.append(Vector((centre.x + SOCKET_RADIUS * math.cos(angle),
                           centre.y + 0.004,
                           centre.z + SOCKET_RADIUS * 0.92 * math.sin(angle))))
        pts.append(Vector((centre.x + SOCKET_RADIUS * 0.55 * math.cos(angle),
                           centre.y - 0.004,
                           centre.z + SOCKET_RADIUS * 0.50 * math.sin(angle))))
    pts.append(Vector((centre.x, centre.y - 0.007, centre.z)))
    hull_range(pts, "Head", ranges)

    # The hood: a brow of hide drooping over the socket's upper half, running out
    # into a broken spur past the skull's outline. The spur is what puts a wound in
    # the head's FRONT silhouette — the sockets vanish in black-on-white, and a dead
    # human dome up top was the last thing on this creature a runner could be
    # mistaken for. On the hide material and returned separately, so it is welded,
    # weighted to Head and unwrapped like the crest but never lights up.
    pts = []
    for k in range(5):
        angle = math.pi * (0.15 + 0.70 * k / 4.0)
        hx = centre.x + math.cos(angle) * (SOCKET_RADIUS + 0.012)
        hz = centre.z + math.sin(angle) * (SOCKET_RADIUS + 0.010)
        pts.append(Vector((hx, left.y + 0.006, hz + 0.004)))
        pts.append(Vector((hx, left.y - 0.020, hz - 0.007)))
    for dx, dy, dz in ((0.052, -0.004, 0.030), (0.066, 0.004, 0.044),
                      (0.058, 0.014, 0.052)):
        pts.append(Vector((centre.x + dx, left.y + dy, centre.z + dz)))
    hull_range(pts, "Head", extra)

    # ── The pinpoint: creature's right. A bead, barely proud, dropped 12 mm. ──
    # Small is what makes it hot: the same EyeGlow through a tenth of the area reads
    # as a point of heat rather than a lamp.
    centre = right + forward * 0.008
    centre.z -= 0.012
    pts = []
    for i in range(8):
        angle = i * math.pi / 4.0
        pts.append(Vector((centre.x + PIN_RADIUS * math.cos(angle),
                           centre.y + 0.004,
                           centre.z + PIN_RADIUS * 0.90 * math.sin(angle))))
    pts.append(Vector((centre.x, centre.y - 0.008, centre.z)))
    pts.append(Vector((centre.x, centre.y + 0.010, centre.z)))
    hull_range(pts, "Head", ranges)

    bmesh.ops.recalc_face_normals(bm, faces=bm.faces[:])
    bm.to_mesh(me)
    bm.free()
    me.update()

    print(f"EYES {obj.name} z={z:.3f} separation={separation:.3f} m "
          f"socket=+X r={SOCKET_RADIUS} pin=-X r={PIN_RADIUS}")
    return ranges, extra


def project_uvs(obj: bpy.types.Object, ranges: list[tuple], density: float) -> None:
    """Gives added geometry a planar X–Z unwrap at the body's own UV density.

    Density rather than "fill the 0–1 square", and that is the load-bearing part.
    ``MonsterSkin.ApplyTiling`` turns each material's declared ``world_size_metres``
    into a texture scale using one measured number — the whole mesh's UV units per
    metre — so a patch unwrapped at a different density samples its map at a different
    physical size than the manifest claims. Matching the body's density means the
    procedural maps land at exactly the centimetres they were drawn for, with nothing
    dialled in.
    """
    me = obj.data
    layer = me.uv_layers.active
    if layer is None:
        blendkit.fail("the sculpt has no UV layer — the maps would sample garbage")

    marked = set()
    for start, end, _ in ranges:
        marked.update(range(start, end))

    for poly in me.polygons:
        if not all(me.loops[i].vertex_index in marked for i in poly.loop_indices):
            continue
        for i in poly.loop_indices:
            co = me.vertices[me.loops[i].vertex_index].co
            layer.data[i].uv = (0.5 + co.x * density, 0.5 + co.z * density)


def maw_polygons(obj: bpy.types.Object) -> list[int]:
    """The faces the ``Jaw`` bone moves — which is exactly what §06's tell should light.

    ``MonsterAcquireTell`` gapes the mandible and lights ``Monster_Maw`` together, over
    the same 1.65 s, because the two are one event: the creature opening its mouth at
    you. Defining the maw as "whatever the Jaw bone owns" makes that true by
    construction on any sculpt — the lit region and the moving region are the same
    vertices, so the glow cannot end up on a cheek while the mouth opens elsewhere.

    A face belongs to the Jaw when the Jaw carries more than half of its corners'
    weight — a clear majority, not merely the largest of four influences. The margin
    matters: ``skin_by_proximity`` keeps four influences per vertex, so "the biggest
    share" can be 0.3 against 0.28, and taking that took a sixth of the creature. What
    is wanted is the part that visibly *swings* when the mandible drops.
    """
    me = obj.data
    jaw = obj.vertex_groups.get("Jaw")
    if jaw is None:
        blendkit.fail("the rig has no Jaw group, so §06's acquisition tell has nothing to light")
        return []

    index = jaw.index
    weight = [0.0] * len(me.vertices)
    for v in me.vertices:
        for g in v.groups:
            if g.group == index:
                weight[v.index] = g.weight

    faces = []
    for poly in me.polygons:
        verts = [me.loops[i].vertex_index for i in poly.loop_indices]
        if sum(weight[v] for v in verts) / len(verts) > 0.5:
            faces.append(poly.index)

    share = len(faces) / max(1, len(me.polygons))
    # Bounded from both ends because both failures are silent. Nothing, and §06's most
    # consequential transition has no visual at all; a third of the creature, and
    # entering 추격 turns the antagonist into a lamp — §03's darkness is the lock on
    # progress and the monster is not allowed to carry the key.
    if not 0.002 <= share <= 0.06:
        blendkit.fail(f"the Jaw owns {share * 100:.1f}% of the mesh's faces. Under 0.2% is a maw "
                      f"nobody can see light up; over 6% is a creature that becomes a lantern "
                      f"the moment §06 enters 추격.")
    print(f"MAW  {obj.name} {len(faces)} face(s), {share * 100:.2f}% of the mesh")
    return faces


def _segment_distance(p: Vector, a: Vector, b: Vector) -> float:
    ab = b - a
    denom = ab.length_squared
    if denom < 1e-12:
        return (p - a).length
    t = max(0.0, min(1.0, (p - a).dot(ab) / denom))
    return (p - (a + ab * t)).length


def skin_by_proximity(obj: bpy.types.Object, arm_obj: bpy.types.Object,
                      specs: list[BoneSpec], influences: int = 4) -> None:
    """Weights every vertex to its nearest bones, computed here rather than by Blender.

    ``bpy.ops.object.parent_set(type="ARMATURE_AUTO")`` is an operator, and operators
    need a context this process does not have under ``--background``. It does not
    raise — it returns and leaves the mesh unskinned, which is invisible until the
    export, where glTF invents a ``neutral_bone`` to hold the orphans. Measured on the
    first build: **8,215 of 8,291 vertices** ended up on that bone, so every clip
    played and nothing moved.

    So: distance from the vertex to each bone's segment, inverse-distance weighting
    with a sharp exponent, top `influences` kept and normalised. Two rules stop the
    obvious failures —

    * a vertex clearly on one side of the body cannot be weighted to the other side's
      limb bones, or a thigh picks up the opposite leg and the walk tears the pelvis;
    * the crest bones are excluded here and assigned explicitly afterwards, because
      their blades sit right beside the neck and would otherwise be captured by it.
    """
    by_name = {s.name: s for s in specs}
    limb_side = {}
    for name in by_name:
        if name.startswith("Left"):
            limb_side[name] = 1
        elif name.startswith("Right"):
            limb_side[name] = -1

    segments = []
    for s in specs:
        if s.name.startswith("Crest"):
            continue
        segments.append((s.name, Vector(s.head), Vector(s.tail), limb_side.get(s.name, 0)))

    groups = {name: obj.vertex_groups.new(name=name) for name, _, _, _ in segments}

    lo, hi = mesh_bounds(obj)
    half_width = max(1e-6, (hi.x - lo.x) * 0.5)
    # Far enough off the centreline that the limbs are unambiguous, close enough that
    # the torso still draws from both sides.
    side_cut = half_width * 0.22

    for v in obj.data.vertices:
        p = obj.matrix_world @ v.co
        side = 1 if p.x > side_cut else (-1 if p.x < -side_cut else 0)

        scored = []
        for name, head, tail, bone_side in segments:
            if side and bone_side and bone_side != side:
                continue
            d = _segment_distance(p, head, tail)
            scored.append((1.0 / (d + 0.012) ** 4, name))
        if not scored:
            continue
        scored.sort(reverse=True)
        top = scored[:influences]
        total = sum(w for w, _ in top)
        for w, name in top:
            groups[name].add([v.index], w / total, "REPLACE")


def build_rig(obj: bpy.types.Object, m: dict, want_crest: bool) -> tuple:
    """Fits the rig, welds on the crest and the lenses, and skins the lot.

    Returns the armature and the two sets of invented vertex ranges. The caller needs
    the crest's to unwrap it and the lenses' to unwrap them *and* to put them on their
    own material slot.
    """
    import gen_monster_model as gmm  # noqa: PLC0415

    specs = fit_bones(m)
    crest_ranges = add_crest(obj, m, specs) if want_crest else []
    # The pelvis shroud rides with the crest ranges: same rigid weighting, same
    # planar unwrap, same hide material — only the bone differs (Hips).
    crest_ranges += gmm.grow_pelvis_shroud(obj, m)
    # After the crest and before the armature modifier, so the ray-cast sees the final
    # exported surface and nothing posed. A lens placed against the rest sculpt and
    # then re-evaluated under a modifier would sit where the head used to be.
    eye_ranges, hood_ranges = add_eyes(obj, m)
    crest_ranges += hood_ranges

    arm_obj = blendkit.build_armature("Monster_Rig", specs)
    obj.parent = arm_obj
    obj.matrix_parent_inverse = arm_obj.matrix_world.inverted()
    mod = obj.modifiers.new("Armature", "ARMATURE")
    mod.object = arm_obj
    skin_by_proximity(obj, arm_obj, specs)

    # Auto-weights treat the crest as part of whatever spine segment it grew out of,
    # so it bends with the back and never flares. Overwrite those vertices outright.
    for name in ("Crest1", "Crest2", "Crest3"):
        if name not in obj.vertex_groups:
            obj.vertex_groups.new(name=name)

    # The lenses go on the same treatment for a different reason: a lens sits directly
    # above the Jaw's segment as well as the Head's, so proximity weighting splits it
    # between the two and the gape tears the eye in half down the middle.
    for start, end, name in crest_ranges + eye_ranges:
        idx = list(range(start, end))
        for group in obj.vertex_groups:
            group.remove(idx)
        obj.vertex_groups[name].add(idx, 1.0, "REPLACE")

    return arm_obj, crest_ranges, eye_ranges


# ── Textures ────────────────────────────────────────────────────────────────


def _srgb_to_linear(x: np.ndarray) -> np.ndarray:
    return np.where(x <= 0.04045, x / 12.92, ((x + 0.055) / 1.055) ** 2.4)


def _linear_to_srgb(x: np.ndarray) -> np.ndarray:
    x = np.clip(x, 0.0, 1.0)
    return np.where(x <= 0.0031308, x * 12.92, 1.055 * x ** (1.0 / 2.4) - 0.055)


def _resample(img: np.ndarray, res: int) -> np.ndarray:
    """Bilinear resample. Rodin bakes 512²; the monster ships 2048².

    Bilinear and not the nearest-neighbour this used to be: at a 4× upsample nearest
    leaves 4-texel stairs across every baked gradient, and the procedural crack
    relief that now rides on top of these maps traces those stairs faithfully —
    a grid etched into the hide at exactly the range the beam resolves it.
    """
    h, w = img.shape[:2]
    y = np.clip((np.arange(res) + 0.5) * (h / res) - 0.5, 0.0, h - 1.0)
    x = np.clip((np.arange(res) + 0.5) * (w / res) - 0.5, 0.0, w - 1.0)
    y0 = np.floor(y).astype(np.int32)
    x0 = np.floor(x).astype(np.int32)
    y1 = np.minimum(y0 + 1, h - 1)
    x1 = np.minimum(x0 + 1, w - 1)
    fy = (y - y0).astype(np.float32)[:, None, None]
    fx = (x - x0).astype(np.float32)[None, :, None]
    top = img[y0][:, x0] * (1.0 - fx) + img[y0][:, x1] * fx
    bottom = img[y1][:, x0] * (1.0 - fx) + img[y1][:, x1] * fx
    return (top * (1.0 - fy) + bottom * fy).astype(np.float32)


def _image_array(image: bpy.types.Image) -> np.ndarray:
    w, h = image.size
    buf = np.empty(w * h * 4, dtype=np.float32)
    image.pixels.foreach_get(buf)
    return buf.reshape(h, w, 4)


def source_maps(obj: bpy.types.Object) -> dict:
    """Pulls Rodin's baked diffuse / metallic-roughness / normal off the material."""
    out = {}
    for slot in obj.data.materials:
        if slot is None or not slot.use_nodes:
            continue
        for node in slot.node_tree.nodes:
            if node.type != "TEX_IMAGE" or node.image is None:
                continue
            name = node.image.name.lower()
            if "diffuse" in name or "basecolor" in name:
                out["diffuse"] = node.image
            elif "normal" in name:
                out["normal"] = node.image
            elif "rough" in name or "metallic" in name:
                out["orm"] = node.image
    return out


def grade_albedo(diffuse: np.ndarray) -> tuple[np.ndarray, dict]:
    """Puts the sculpt's diffuse on §03's albedo budget: mean 0.17, ceiling 0.2016.

    Measured, not assumed — the creature sculpt arrives at 0.1324 mean linear, i.e.
    already *under* the target, so this is as often a lift as a cut. What the sculpts
    reliably do get wrong is the top end: highlights baked for a turntable sit well
    above the ceiling, and those are what would make the creature announce itself in a
    §12 corridor.

    Above the knee the curve compresses rather than clips, because a clipped highlight
    is a flat white patch and a flat patch on a creature reads as plastic. Compression
    moves the mean down, so the scale is then re-solved against the compressed result
    — a single pass lands at 0.144 and quietly misses the budget it claims to enforce.
    """
    lin = _srgb_to_linear(diffuse[..., :3])
    source_mean = float(lin.mean())
    knee = ALBEDO_MAX * 0.82

    def compress(gain):
        out = lin * gain
        over = out > knee
        out[over] = knee + (ALBEDO_MAX - knee) * np.tanh(
            (out[over] - knee) / (ALBEDO_MAX - knee))
        return out

    gain = ALBEDO_MEAN / max(source_mean, 1e-6)
    graded = compress(gain)
    for _ in range(24):
        err = float(graded.mean())
        if abs(err - ALBEDO_MEAN) <= 1e-4:
            break
        gain *= ALBEDO_MEAN / max(err, 1e-6)
        graded = compress(gain)
    lin = graded

    stats = {
        "albedo_mean_linear": round(float(lin.mean()), 4),
        "albedo_max_linear": round(float(lin.max()), 4),
        "corridor_darkest_linear": CORRIDOR_DARKEST,
        "source_mean_linear": round(source_mean, 4),
        "albedo_gain": round(gain, 4),
    }
    out = diffuse.copy()
    out[..., :3] = _linear_to_srgb(lin)
    return out, stats


def grade_roughness(rough: np.ndarray, target: float, floor: float) -> tuple[np.ndarray, dict]:
    """Puts Rodin's roughness on the mean the hide was calibrated at, keeping its variation.

    Exactly the argument this file already makes one channel over about metallic, applied
    to the channel that decides how §03's beam lands. Rodin lights its sculpts for a
    turntable and returns a fairly glossy surface — measured on the creature, mean 0.436,
    which is *plate* roughness, between the previous asset's carapace (0.380) and the
    inside of its mouth (0.280), and nowhere near its hide (0.836). Under a hard spot a
    metre away that renders as wet plastic; at range it is worse, because a smooth
    surface on a creature twelve pixels wide puts its specular lobe on some pixels and
    not others and crawls frame to frame. ``MonsterBeamResolve`` already fights that by
    rolling smoothness off with distance, and its note says plainly that it can only
    afford to roll it to 0.7 because the highlight is also most of what makes the
    creature visible at 8 m — so the map has to arrive sane rather than be rescued.

    The target is not typed here: it is measured off ``gen_monster_model.build_flesh``,
    which is the hide the corridor pass was calibrated against. Re-paint that surface and
    this follows it.

    Scaled rather than replaced, so the sculpt's own wet patches stay wetter than its dry
    ones — the variation is Rodin's and it is the part worth keeping.
    """
    source_mean = float(rough.mean())
    gain = target / max(source_mean, 1e-6)
    graded = np.clip(rough * gain, floor, 1.0).astype(np.float32)

    # Clipping at the floor moves the mean, so the scale is re-solved against the clipped
    # result — the same two-pass correction grade_albedo needs, for the same reason.
    for _ in range(16):
        err = float(graded.mean())
        if abs(err - target) <= 1e-4:
            break
        gain *= target / max(err, 1e-6)
        graded = np.clip(rough * gain, floor, 1.0).astype(np.float32)

    return graded, {
        "roughness_source_mean": round(source_mean, 4),
        "roughness_gain": round(gain, 4),
    }


def write_png(path: str, data: np.ndarray) -> int:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    h, w = data.shape[:2]
    name = "_w_" + os.path.basename(path)
    img = bpy.data.images.new(name, width=w, height=h, alpha=True)
    img.pixels.foreach_set(np.ascontiguousarray(data, dtype=np.float32).ravel())
    img.file_format = "PNG"
    img.filepath_raw = path
    img.save()
    bpy.data.images.remove(img)
    return os.path.getsize(path)


def hide_roughness() -> float:
    """The roughness the previous asset's hide shipped at, measured rather than copied.

    ``gen_monster_model.build_flesh`` paints it, and every visibility number the shot rig
    has ever reported was measured against a creature whose skin sat there. Reading it
    out of that function costs one 1024² noise field and means a re-paint of the hide
    carries this map with it, instead of leaving the sculpt as the one surface still
    calibrated to a number somebody typed once.
    """
    import gen_monster_model as gmm  # noqa: PLC0415

    return float(gmm.build_flesh(TEX_RES)["roughness"].mean())


def build_textures(obj: bpy.types.Object, material: str, tex_root: str) -> dict:
    """Grades and re-emits the sculpt's maps in the layout Unity already expects."""
    import gen_monster_model as gmm  # noqa: PLC0415

    maps = source_maps(obj)
    if "diffuse" not in maps:
        blendkit.fail(f"{material}: the sculpt carries no diffuse map to grade")

    folder = os.path.join(tex_root, material)
    diffuse = _resample(_image_array(maps["diffuse"]), TEX_RES)
    normal = (_resample(_image_array(maps["normal"]), TEX_RES)
              if "normal" in maps else None)
    orm = _resample(_image_array(maps["orm"]), TEX_RES) if "orm" in maps else None

    # Dress the turntable bake into dead flesh BEFORE any grading: cadaveric mottle,
    # cavity-gated craquelure, dry-shell/wet-crevice roughness, real AO. The dressing
    # is shape only — the grades below still own the mean and the corridor ceiling,
    # so §03's albedo policy is enforced on what actually ships. See the docstring on
    # gen_monster_model.dress_sculpt_maps for the shot-review findings this answers.
    world_size = 1.0 / max(gmm.uv_units_per_metre(obj), 1e-6)
    dressed = gmm.dress_sculpt_maps(diffuse, normal,
                                    orm[..., 1] if orm is not None else None,
                                    TEX_RES, world_size)

    graded, stats = grade_albedo(dressed["albedo"])
    stats.update(dressed["stats"])
    written = {"albedo": write_png(os.path.join(folder, f"{material}_albedo.png"), graded)}

    if dressed["normal"] is not None:
        write_png(os.path.join(folder, f"{material}_normal.png"), dressed["normal"])
        written["normal"] = True

    limits = gmm.pipeline_constants()
    rough, rough_stats = grade_roughness(dressed["rough"], hide_roughness(),
                                         limits["MIN_ROUGHNESS"])
    stats.update(rough_stats)

    rgba = np.ones((TEX_RES, TEX_RES, 4), dtype=np.float32)
    rgba[..., 0] = rgba[..., 1] = rgba[..., 2] = rough
    write_png(os.path.join(folder, f"{material}_rough.png"), rgba)

    # Skin is a dielectric. Rodin's metallic channel comes back around 0.45 mean,
    # which under §03's hard spot renders as wet sheet metal — so it is discarded
    # rather than carried through, matching the 0.0 the previous asset shipped.
    # Nothing is written for it: an all-zero map is a texture fetch that returns
    # what the shader's default already is.
    if orm is not None:
        stats["metallic_source_mean"] = round(float(orm[..., 2].mean()), 4)
    stats["metallic_mean"] = 0.0

    # Rodin bakes no occlusion, so this used to be skipped as a constant-white map.
    # The dressing derives a real one from the normal map's own cavities, and it is
    # load-bearing now: §3.14's rim light samples _OcclusionMap, and a rim over
    # creviced skin without AO flattens it back into a paper cut-out.
    rgba = np.ones((TEX_RES, TEX_RES, 4), dtype=np.float32)
    rgba[..., 0] = rgba[..., 1] = rgba[..., 2] = dressed["ao"]
    write_png(os.path.join(folder, f"{material}_ao.png"), rgba)
    stats["ao_mean"] = round(float(dressed["ao"].mean()), 4)

    ms = np.zeros((TEX_RES, TEX_RES, 4), dtype=np.float32)
    ms[..., 3] = 1.0 - rough          # Unity reads smoothness out of alpha
    write_png(os.path.join(folder, f"{material}_ms.png"), ms)

    stats["roughness_mean"] = round(float(rough.mean()), 4)

    stats["resolution"] = TEX_RES
    stats["bytes"] = written["albedo"]
    return stats


def assign_materials(obj: bpy.types.Object, names: dict, eye_ranges: list[tuple],
                     maw_faces: list[int]) -> dict:
    """Replaces the sculpt's imported material with the three the game drives.

    Empty on purpose. Unity imports this FBX with ``materialImportMode: 2`` and no
    external object remapping — exactly as the previous monster does — so the FBX
    carries material *names* and the maps are found under ``Assets/Textures/<name>/``.
    Hooking image nodes up before the FBX export instead makes Blender's exporter copy
    every PNG into a ``.fbx`` sidecar directory, which is a second copy of the same
    textures committed to the repo and a convention this project does not use.

    Three slots and not one, because three separate pieces of Unity code address this
    creature by material name and two of them have nothing to write to on a sculpt:
    ``MonsterBeamResolve`` drives ``_RimStrength`` on every slot, ``MonsterSkin``
    authors the eyes' constant emission on ``Monster_Eyes``, and
    ``MonsterAcquireTell`` fires ``_EmissionColor`` on ``Monster_Maw``. Ownership is by
    material and by property, which is what stops the last two overwriting each other.
    """
    obj.data.materials.clear()
    built = {}
    for key in ("hide", "eyes", "maw"):
        mat = bpy.data.materials.new(names[key])
        mat.use_nodes = True
        obj.data.materials.append(mat)
        built[key] = mat

    slot = {key: i for i, key in enumerate(("hide", "eyes", "maw"))}
    lens = set()
    for start, end, _ in eye_ranges:
        lens.update(range(start, end))

    me = obj.data
    maw = set(maw_faces)
    for poly in me.polygons:
        if all(me.loops[i].vertex_index in lens for i in poly.loop_indices):
            poly.material_index = slot["eyes"]
        elif poly.index in maw:
            poly.material_index = slot["maw"]
        else:
            poly.material_index = slot["hide"]

    counts = {key: sum(1 for p in me.polygons if p.material_index == i)
              for key, i in slot.items()}
    for key in ("eyes", "maw"):
        if counts[key] == 0:
            blendkit.fail(f"{names[key]} ended up on no faces at all. The material would import as "
                          f"an unused slot and the component that drives it would run every frame "
                          f"writing to nothing — which is invisible, and is how this creature "
                          f"shipped with two unlit eyes before.")
    print(f"SLOTS {obj.name} " + " ".join(f"{names[k]}={counts[k]}" for k in slot))
    return built


def hook_textures(mat: bpy.types.Material, material: str, tex_root: str) -> None:
    """Wires the graded maps onto the material, for the .glb preview only."""
    folder = os.path.join(tex_root, material)
    nt = mat.node_tree
    bsdf = next(n for n in nt.nodes if n.type == "BSDF_PRINCIPLED")

    def hook(suffix, socket, non_color):
        path = os.path.join(folder, f"{material}_{suffix}.png")
        if not os.path.exists(path):
            return None
        node = nt.nodes.new("ShaderNodeTexImage")
        node.image = bpy.data.images.load(path, check_existing=True)
        if non_color:
            node.image.colorspace_settings.name = "Non-Color"
        if socket == "Normal":
            nm = nt.nodes.new("ShaderNodeNormalMap")
            nt.links.new(node.outputs["Color"], nm.inputs["Color"])
            nt.links.new(nm.outputs["Normal"], bsdf.inputs["Normal"])
        else:
            nt.links.new(node.outputs["Color"], bsdf.inputs[socket])
        return node

    hook("albedo", "Base Color", False)
    hook("rough", "Roughness", True)
    hook("normal", "Normal", True)


# ── Animation ───────────────────────────────────────────────────────────────

# The seven §06 states, authored once in gen_monster_model.py and reused verbatim.
# They transfer because they are written as rotations about *world* axes and
# converted per bone through that module's `spec_pose`, so they follow whatever rest
# pose the rig happens to have rather than baking one in — and because every bone
# name here is identical by contract.
CLIP_ORDER = ("Patrol", "Chase", "Alert", "Search", "Standstill", "Stunned", "Grab")


NON_LOOPING = ("Stunned", "Grab")


def author_clips(arm_obj: bpy.types.Object, body: bpy.types.Object) -> list[dict]:
    """Builds the seven clips on the fitted rig, grounds each, and stashes them.

    Grounding is the step that cannot be skipped. Every clip is authored as joint
    rotations against a rest pose, and this rig's rest pose is a sculpt's, not the one
    those rotations were written for — so the same knee angle that planted a foot on
    the original digitigrade skeleton leaves this one hanging in the air or buried in
    the floor. ``gen_monster_model.ground_action`` re-solves the hip height per frame
    against the actual mesh, which is exactly the correction needed and is already
    written, tested and used by the asset that ships today.
    """
    import gen_monster_model as gmm  # noqa: PLC0415 — imported for its clip authors

    builders = {
        "Patrol": gmm.action_patrol,
        "Chase": gmm.action_chase,
        "Alert": gmm.action_alert,
        "Search": gmm.action_search,
        "Standstill": gmm.action_standstill,
        "Stunned": gmm.action_stunned,
        "Grab": gmm.action_grab,
    }

    written = []
    longest = 1
    for name in CLIP_ORDER:
        # The builder's second return value is the gait amplitude, and it is None for
        # exactly the clips that are not locomotion. That is the flag the original
        # generator branches on, so it is the flag used here rather than a hand-kept
        # list of clip names that would drift the first time one is added.
        action, amp = builders[name](arm_obj)
        if action is None:
            blendkit.fail(f"clip {name} produced no action")

        lift = gmm.ground_action(arm_obj, body, action)
        if amp is not None:
            # Locomotion only. Search, Grab and Stunned are *meant* to drift — a
            # creature casting about or recoiling is not holding a stride.
            gmm.lock_stance_slide(arm_obj, action)

        # Measured after both correction passes, because each moves the hips on every
        # frame and therefore moves the foot these numbers are taken from.
        speed, slide = gmm.measure_ground_speed(arm_obj, action)
        # (worst penetration, worst float, hip vertical travel) — sampled on every
        # frame, not just the keys, because the Bézier between two grounded keys can
        # still dip a foot through the floor.
        sink, float_, hip_bob = gmm.grounding_error(arm_obj, body, action)

        frames = int(round(action.frame_range[1] - action.frame_range[0])) + 1
        longest = max(longest, int(math.ceil(action.frame_range[1])))
        written.append({
            "name": name,
            "frames": frames,
            "seconds": round(frames / FPS, 4),
            "loops": name not in NON_LOOPING,
            "locomotion": amp is not None,
            "ground_speed_mps": round(float(speed), 4),
            "residual_slide_mps": round(float(slide), 4),
            "ground_lift_m": round(float(lift), 4),
            "foot_sink_m": round(float(sink), 5),
            "foot_float_m": round(float(float_), 5),
            "hip_bob_m": round(float(hip_bob), 5),
        })
        blendkit.stash_action(arm_obj, action)
    arm_obj.animation_data.action = None

    # The scene range is what the FBX exporter bakes over, so it has to cover the
    # longest clip. Left at a guessed 60 it silently truncates Standstill's 91 frames
    # — and Standstill is the §06 state the design calls the game's weapon.
    blendkit.set_frame_range(1, longest)
    return written


def hide_entry(names: dict, texture: dict, note: str, uv_per_metre: float) -> dict:
    """The sculpt's own surface, described in the shape ``MonsterSkin`` reads.

    One field here is not a measurement of a texture and needs saying out loud.
    ``MonsterSkin.ApplyTiling`` computes ``1 / (uv_units_per_metre × world_size_metres)``
    and puts that on the material as a texture scale, because the rest of the project's
    maps are *tileable patches* drawn at a stated physical size. These are not: Rodin
    baked them to this sculpt's own unwrap, so one tile is the whole creature and the
    only correct scale is exactly 1. Declaring the reciprocal of the measured UV density
    is how that gets said in the vocabulary the manifest already has — and it stays
    correct if the unwrap is ever repacked, because both halves move together.
    """
    hide = names["hide"]
    entry = dict(texture)
    entry.pop("resolution", None)
    return {
        "name": hide,
        "note": note + " Albedo is graded to sit under the darkest §12 corridor wall, so "
                "the creature never announces itself.",
        "world_size_metres": round(1.0 / uv_per_metre, 6),
        **entry,
        "maps": {
            "albedo": f"{hide}/{hide}_albedo.png",
            "normal": f"{hide}/{hide}_normal.png",
            "roughness": f"{hide}/{hide}_rough.png",
            "occlusion": f"{hide}/{hide}_ao.png" if texture.get("ao_mean") else "",
            "metallic_smoothness": f"{hide}/{hide}_ms.png",
        },
    }


def maw_entry(hide: dict) -> dict:
    """The jaw's skin: the hide's own maps, under a second name.

    It is the same surface — it is the same animal — and painting it differently would
    make the mouth read as a separate object stuck to the face. What the second entry
    buys is a second *emission channel*: ``MonsterAcquireTell`` writes
    ``_EmissionColor`` on this slot to light §06's acquisition, and it can only do that
    to a material of its own. Because the emission map is the albedo, the flare then
    takes the shape of the hide's folds rather than flooding a polygon.
    """
    entry = dict(hide)
    entry["maps"] = dict(hide["maps"])   # not the hide's own dict: a shared one would
    entry["name"] = MAW_MATERIAL         # let an edit to either entry move both
    entry["note"] = ("The faces the Jaw bone moves, on the hide's own maps. Split off "
                     "only so §06's acquisition flare has a slot it owns — "
                     "MonsterAcquireTell gapes the mandible and lights this together, "
                     "which is one event and has to look like one.")
    return entry


def write_manifests(models: str, textures: str, variant: dict,
                    clips: list[dict], materials: list[dict], uv_per_metre: float) -> None:
    """Emits the two JSON manifests Unity reads.

    For the shipped variant these land on ``Monster.clips.json`` and
    ``Monster.textures.json`` — the exact paths ``MonsterRig.ClipManifestPath`` and
    ``MonsterSkin.ManifestPath`` hardcode. There is no second copy of either under
    another name, which is the point: a reader who opens either file is looking at the
    creature the game loads.
    """
    with open(os.path.join(models, variant["asset"] + ".clips.json"), "w") as fh:
        json.dump({
            "generated_by": "tools/blender/gen_monster_ai.py",
            "fps": FPS,
            "note": "ground_speed_mps is measured from the weight-bearing foot after "
                    "grounding, not derived. Playback rate for a §07 tier speed is "
                    "tierSpeed / ground_speed_mps.",
            "clips": clips,
        }, fh, indent=2)
        fh.write("\n")

    with open(os.path.join(textures, variant["asset"] + ".textures.json"), "w") as fh:
        json.dump({
            "generated_by": "tools/blender/gen_monster_ai.py",
            "resolution": TEX_RES,
            "uv_units_per_metre": round(uv_per_metre, 6),
            "fbx": f"Assets/Models/Characters/{variant['asset']}.fbx",
            "materials": materials,
        }, fh, indent=2)
        fh.write("\n")


# ── Build ───────────────────────────────────────────────────────────────────


def build_eye_textures() -> dict:
    """Emits the lens's map set through the project's own procedural pipeline.

    Not graded from the sculpt, because the sculpt has no lenses — they were grown here.
    ``gen_monster_model.build_eyes`` already paints exactly this surface and its note
    argues the shape out: near-black wet glass, featureless at the distance that
    matters, with fine crazing that only exists to give §03's beam something to catch at
    3 m. It goes through the same ``write_skin`` every other surface in the game does,
    so the lens is held to ``gen_textures.py``'s albedo band and to the corridor ceiling
    by the same assertions, rather than being a colour this file picked.

    Always into ``Assets/Textures/Monster_Eyes/``, including on a variant that does not
    ship, and that is not an oversight: it is the same lens on either sculpt, painted
    from fixed seeds, so the bytes are identical whoever asked for them.
    """
    import gen_monster_model as gmm  # noqa: PLC0415

    # 1024, not TEX_RES: the 2048 allowance exists for the hide, which is the whole
    # creature on one unwrap. A lens is 5 cm; at 1024² it already carries more texels
    # per centimetre than the hide does.
    return gmm.write_skin(EYE_MATERIAL, gmm.build_eyes, 0.152,
                          "The lenses: a dying lamp behind fouled glass — dead soot cells, "
                          "a drifting membrane, hot pin flecks. Everything anybody ever sees "
                          "of them is MonsterSkin.EyeGlow multiplied through this map, and "
                          "the map's mean still lands on the calibrated target, so §04's "
                          "관측자 keeps the same pair luminance at ObserverRange while the "
                          "near field stops reading as two cartoon irises.",
                          1024, gmm.pipeline_constants())


def build(variant: dict) -> dict:
    import gen_monster_model as gmm  # noqa: PLC0415

    blendkit.reset_scene()

    src = os.path.join(SOURCE_DIR, variant["source"])
    if not os.path.exists(src):
        blendkit.fail(f"missing base sculpt {src}")

    obj = load_base(src)
    obj.name = variant["asset"] + "_Body"
    raw_tris = triangles(obj)

    # Measured at full resolution, then carried forward. The slab analysis needs a
    # densely sampled mesh: at 5.6k vertices a 200-slab scan sees 28 vertices per
    # slab, and every "is this mass a limb or is it noise" threshold degenerates —
    # measured on the decimated vessel it put the ankle at 0.029 m, which is inside
    # the foot. Decimation barely moves the silhouette, so the reading survives it.
    #
    # Decimation *does* move the extremes by a few millimetres, so the mesh is
    # normalised again afterwards and the landmarks are scaled by the same factor —
    # AssetImportPolicy pins the height to the millimetre.
    normalise(obj)
    m = monster_fit.measure(obj)
    decimate(obj, TRI_TARGET)
    normalise(obj)

    # Displacement-only asymmetry (leg bulk, dragged claw, staved temple) — after
    # decimation so it sculpts the vertices that ship, before the rig fit so the
    # eye ray-cast and the skirt anchor against the final surface. Z is untouched,
    # so the landmark heights measured above stay valid.
    gmm.sculpt_asymmetry(obj, m)

    # Measured on the bare sculpt, before anything is welded on. This is the density
    # Rodin's own unwrap holds, and it is what the crest and the lenses are then
    # unwrapped to match — taking it afterwards would measure a mesh that includes the
    # very geometry whose UVs are still undecided.
    sculpt_density = gmm.uv_units_per_metre(obj)

    arm_obj, crest_ranges, eye_ranges = build_rig(obj, m, variant["crest"])

    # Everything this file invented gets a planar unwrap at the sculpt's density.
    # Without it the added vertices carry the (0, 0) bmesh leaves behind, and one
    # texel of the atlas is then stretched across the whole crest — a flat patch on
    # the one part of the creature §04's 관측자 is supposed to read a state off.
    project_uvs(obj, crest_ranges + eye_ranges, sculpt_density)

    names = material_names(variant)
    # Follows the variant, so a variant that does not ship cannot leave its hide in
    # Assets/Textures for someone to find later and wonder which creature wears it.
    tex_root = variant["manifest_dir"]
    stats = build_textures(obj, names["hide"], tex_root)
    eye_stats = build_eye_textures()

    maw_faces = maw_polygons(obj)
    mats = assign_materials(obj, names, eye_ranges, maw_faces)

    uv_per_metre = float(gmm.uv_units_per_metre(obj))
    hide = hide_entry(names, stats, variant["note"], uv_per_metre)
    materials = [hide, eye_stats, maw_entry(hide)]

    clips = author_clips(arm_obj, obj)

    models = variant["models_dir"]
    textures_dir = variant["manifest_dir"]
    os.makedirs(models, exist_ok=True)
    os.makedirs(textures_dir, exist_ok=True)
    write_manifests(models, textures_dir, variant, clips, materials, uv_per_metre)

    fbx = os.path.join(models, variant["asset"] + ".fbx")
    glb = os.path.join(models, variant["asset"] + ".glb")
    blendkit.export_fbx(fbx, [arm_obj, obj], with_animation=True)

    # Textures go on only now, so the .glb — which docs/ASSETS.md keeps for eyeballing
    # an asset without opening Unity — previews with the graded maps, while the FBX
    # above stays a geometry-and-name handoff.
    hook_textures(mats["hide"], names["hide"], tex_root)
    hook_textures(mats["maw"], names["hide"], tex_root)
    hook_textures(mats["eyes"], names["eyes"], os.path.join(blendkit.UNITY_ASSETS, "Textures"))
    blendkit.export_gltf(glb, with_animation=True)

    return {
        "variant": variant,
        "object": obj,
        "rig": arm_obj,
        "landmarks": m,
        "texture": stats,
        "materials": materials,
        "clips": clips,
        "raw_tris": raw_tris,
        "tris": triangles(obj),
        "fbx": fbx,
        "glb": glb,
    }


def wanted_variants(argv: list[str]) -> list[dict]:
    """The variants this run builds, and where each one is allowed to write.

    Shipping variants go into ``Assets/``; anything else goes to ``artifacts/`` and can
    therefore never be mistaken for the monster the game loads, never be picked up by
    ``AssetImportValidator``, and never quietly become a second answer to "which one is
    it". ``-- --vessel`` opts the human-shaped sculpt back in.
    """
    tail = argv[argv.index("--") + 1:] if "--" in argv else []
    chosen = []
    for variant in VARIANTS:
        if not variant["ships"] and f"--{variant['key']}" not in tail:
            print(f"SKIP {variant['key']:9s} not the shipped monster; "
                  f"pass -- --{variant['key']} to build it into artifacts/")
            continue
        root = blendkit.UNITY_ASSETS if variant["ships"] else os.path.abspath(ARTIFACT_DIR)
        chosen.append({
            **variant,
            "models_dir": (os.path.join(root, "Models", "Characters")
                           if variant["ships"] else root),
            "manifest_dir": os.path.join(root, "Textures") if variant["ships"] else root,
        })
    return chosen


def main() -> None:
    results = []
    for variant in wanted_variants(sys.argv):
        r = build(variant)
        m = r["landmarks"]
        lo, hi = mesh_bounds(r["object"])
        height, width = hi.z - lo.z, hi.x - lo.x
        print(f"FIT {variant['key']:9s} tris={r['raw_tris']}->{r['tris']} "
              f"height={height:.3f} width={width:.3f} "
              f"shoulder={m['shoulder']:.3f} crotch={m['crotch']:.3f} "
              f"knee={m['knee']:.3f} ankle={m['ankle']:.3f} "
              f"elbow={m['elbow']:.3f} wrist={m['wrist']:.3f}")
        for entry in r["materials"]:
            print(f"TEX {entry['name']:20s} albedo={entry['albedo_mean_linear']:.4f} "
                  f"max={entry['albedo_max_linear']:.4f} rough={entry['roughness_mean']:.4f} "
                  f"world={entry['world_size_metres']:.4f}m "
                  f"maps={sorted(k for k, v in entry['maps'].items() if v)}")

        if r["tris"] > TRI_BUDGET:
            blendkit.fail(f"{variant['asset']}: {r['tris']} triangles over the "
                          f"{TRI_BUDGET} budget")
        if width > SHOULDER_LIMIT:
            blendkit.fail(f"{variant['asset']}: {width:.3f} m across — §12 corridors "
                          f"cap it at {SHOULDER_LIMIT} m")
        if abs(height - TARGET_HEIGHT) > 0.002:
            blendkit.fail(f"{variant['asset']}: {height:.4f} m tall, "
                          f"AssetImportPolicy pins {TARGET_HEIGHT}")
        verify_rig(variant, r["rig"])
        verify_clips(variant, r["clips"])
        verify_materials(variant, r["materials"])

        for c in r["clips"]:
            print(f"CLIP {variant['key']:9s} {c['name']:11s} {c['seconds']:6.3f}s "
                  f"loco={str(c['locomotion']):5s} speed={c['ground_speed_mps']:7.4f} "
                  f"slide={c['residual_slide_mps']:7.4f} "
                  f"sink={c['foot_sink_m'] * 1000:+6.2f}mm "
                  f"float={c['foot_float_m'] * 1000:+6.2f}mm")

        results.append(r)
        print(f"ASSET_REPORT {variant['asset']} tris={r['tris']} height={height:.3f} "
              f"clips={len(r['clips'])}")
    return results


# ── Verification ────────────────────────────────────────────────────────────

# The 29 names Unity's code depends on. Not a description of the rig — a contract with
# MonsterRig.cs, MonsterAcquireTell.cs and AssetImportValidator.cs.
REQUIRED_BONES = frozenset(
    ["Hips", "Spine", "Chest", "UpperChest", "Neck", "Head", "Jaw",
     "Crest1", "Crest2", "Crest3", "LeftScapulaSpur"]
    + [f"{side}{part}" for side in ("Left", "Right")
       for part in ("Shoulder", "UpperArm", "LowerArm", "ForearmExtra", "Hand",
                    "UpperLeg", "LowerLeg", "Foot", "Toes")]
)


def verify_rig(variant: dict, arm_obj: bpy.types.Object) -> None:
    have = {b.name for b in arm_obj.data.bones}
    missing = REQUIRED_BONES - have
    if missing:
        blendkit.fail(f"{variant['asset']}: rig is missing {sorted(missing)} — "
                      "AssetImportValidator and MonsterAcquireTell address bones by name")
    extra = have - REQUIRED_BONES
    if extra:
        blendkit.fail(f"{variant['asset']}: rig carries unexpected bones {sorted(extra)}. "
                      "A stray bone is usually the exporter's unweighted-vertex holder, "
                      "which means part of the mesh is not skinned to anything.")


def verify_materials(variant: dict, materials: list[dict]) -> None:
    """Asserts the manifest still says everything ``MonsterSkin`` has to be told.

    Every one of these has a silent failure on the other side of it. A missing
    ``world_size_metres`` makes ``ApplyTiling`` throw and the whole skin build fail — the
    loud case, and the least dangerous. A missing ``Monster_Eyes`` builds a creature with
    no lenses and §04's 관측자 loses the only cue that survives 15 m, with nothing
    logged. A missing ``Monster_Maw`` leaves ``MonsterAcquireTell`` writing an emission
    colour to a material that is not there, every frame of every acquisition, forever.
    """
    by_name = {entry["name"]: entry for entry in materials}
    for required in (variant["material"], EYE_MATERIAL, MAW_MATERIAL):
        if required not in by_name:
            blendkit.fail(f"{variant['asset']}: the skin manifest has no {required} entry")

    for entry in materials:
        if entry.get("world_size_metres", 0.0) <= 0.0:
            blendkit.fail(f"{entry['name']}: world_size_metres is not positive, so "
                          "MonsterSkin.ApplyTiling cannot derive a texture scale")
        for slot in ("albedo", "normal", "roughness", "metallic_smoothness"):
            if not entry["maps"].get(slot):
                blendkit.fail(f"{entry['name']}: no {slot} map. §03 makes the flashlight the "
                              "game's central mechanic and a flat surface gives the beam "
                              "nothing to do — no normal to catch its grazing edge, no "
                              "roughness variation to break its hotspot.")


def verify_clips(variant: dict, clips: list[dict]) -> None:
    by_name = {c["name"]: c for c in clips}
    missing = set(CLIP_ORDER) - set(by_name)
    if missing:
        blendkit.fail(f"{variant['asset']}: clips missing {sorted(missing)}")

    for c in clips:
        # 5 mm, the tolerance gen_monster_model holds itself to. A foot through the
        # floor is the one animation error a dark corridor does not hide.
        if c["foot_sink_m"] < -0.005:
            blendkit.fail(f"{variant['asset']}/{c['name']}: a foot sinks "
                          f"{abs(c['foot_sink_m']) * 1000:.1f} mm through the floor")
        if c["locomotion"] and abs(c["residual_slide_mps"]) > 0.05:
            blendkit.fail(f"{variant['asset']}/{c['name']}: {c['residual_slide_mps']:.3f} "
                          "m/s of foot slide — lock_stance_slide did not converge")

    # §06 calls stillness the game's weapon: the Listener loses the creature when it
    # stops, which is only true if it genuinely stops.
    still = by_name["Standstill"]
    if abs(still["ground_speed_mps"]) > 1e-6:
        blendkit.fail(f"{variant['asset']}: Standstill travels "
                      f"{still['ground_speed_mps']:.4f} m/s — it has to be silent and "
                      "motionless, which is the state's entire purpose")


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception:
        blendkit.fail("gen_monster_ai.py raised:\n" + traceback.format_exc())
