#!/usr/bin/env python3
"""Generates the modular map kit — the pieces §12's rules are built out of.

Run headless::

    /Applications/Blender.app/Contents/MacOS/Blender --background --factory-startup \\
        --python tools/blender/gen_mapkit.py

Outputs one FBX per piece into ``Assets/Models/MapKit/`` plus
``MapKit.manifest.json`` describing every footprint, dock point and floor slot.

WHY THIS KIT EXISTS
-------------------
§12 opens with **"맵은 아트가 아니라 시스템이다"** and then derives every dimension
from §06's speeds. That means the pieces themselves are the enforcement mechanism:
if the only 직선 통로 a designer can place is 10 m long, no assembled level can
violate §12's "직선 통로 최대 20m — 넘으면 주자가 죽는다".

So each dimension below is a *consequence*, not a taste:

* **S-corridor legs 10 m.** §12: "10m 구간 2개의 S자 통로 하나면 해제가 성립한다.
  이것이 맵의 기본 단위다." 20 m of path / 4.8 m/s = 4.17 s > the 3 s of broken
  line of sight §06 requires. ``SCorridor_Unit_10m_x2`` ships that whole unit as one
  piece so it cannot be mis-composed, and ``Corridor_Corner_L`` + the straights let
  it be rebuilt by hand.
* **Nothing longer than 20 m.** The longest straight run in the kit is the 10 m
  straight; the widest footprint is the 20 m hall, whose 20 m sight line is
  *required* by §12 (개방 공간 시야 15~25m), not merely tolerated.
* **Loops.** §12: "순환로 개수 — 구역당 1+, 전체 3+ / 트리 구조는 사형선고." A tree
  graph cannot be built from a kit whose junctions are a T and a 4-way, so both ship.
* **Dead ends carry a reward.** §12 wants 20-25% dead ends "위험을 감수할 이유"로.
  ``DeadEnd_Cap`` therefore has a loot plinth and a lit alcove built in — the reward
  is part of the geometry, not level dressing someone may forget.
* **Floor material is a gameplay channel.** §12: "구역별로 바닥 재질이 달라야 청음사가
  위치를 판별할 수 있다. 아트 결정이 아니라 시스템 결정이다. 재질 경계를 명확히 할 것."
  All five surfaces ship with the contractual ``Floor_Wood`` / ``Floor_Tile`` /
  ``Floor_Gravel`` / ``Floor_Concrete`` / ``Floor_Metal`` names *and* with distinct
  surface relief, because §05 says the game is dark — colour alone will not read in
  a flashlight cone, so the boundary is made geometric as well.
* **Observation posts.** §04's Observer works at 15 m and §12 says without posts
  "관측자는 죽으러 가야 한다". Two ship: a 15 m raised gallery and a barred-window
  alcove whose bar gaps are too narrow for the monster.
* **Doors at bottlenecks.** §04's Engineer locks them; §12 allows 구역당 1~2개.
  The leaf is a separate piece so one doorway can be locked and another left open.

GRID AND ORIGIN — the two things a level assembler depends on
-------------------------------------------------------------
* **Grid: 2.5 m**, horizontally, on both axes. Every §12 number is a multiple of it
  (5, 10, 15, 20, 17.5), so every piece footprint is an exact multiple and the
  script asserts it.
* **Origin: the minimum-X / minimum-Y corner of the footprint, at the floor's top
  surface (z = 0).** Placing a piece at grid coordinate (i, j) therefore means
  translating to (i × 2.5, j × 2.5, 0) with no offset arithmetic, and the walkable
  surface is always exactly y = 0 in Unity. The script asserts
  ``bounds_min.x == bounds_min.y == 0`` for every piece.
* Two pieces are **props, not tiles**: ``Door_Panel_Lockable`` (positioned by its
  hinge, which is its origin) and ``WallPanel_Electrical``. They are exempt from the
  grid assertion and say so in the table.

CROSS-SECTION — why the corridor is 2.20 m × 3.00 m clear
---------------------------------------------------------
* §08's w5 궤짝 is a **two-person carry** ("2인 운반"), and §08 calls two players
  walking a chest down a narrow corridor "최고의 순간". Two player capsules side by
  side plus the chest need ≈1.8 m; 2.20 m clear passes it while still being narrow
  enough to be the 섬광수's stage (§12: "넓은 곳에서는 괴물이 우회한다").
* The monster is 2.34 m tall and 0.93 m across the shoulders as generated by
  ``gen_monster_model.py`` (§12 budgets ~1.2 m). 3.00 m clear height and 2.20 m
  clear width both pass with margin, so §06's speeds are never limited by geometry.
* Door hardware (hinge pintles) is the tightest point at 2.08 m clear. Still above
  the two-person carry requirement; called out in the report rather than hidden.
"""

from __future__ import annotations

import json
import math
import os
import random
import sys
import traceback
from dataclasses import dataclass, field
from typing import Callable, Sequence

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import bmesh  # noqa: E402
import bpy  # noqa: E402
from mathutils import Vector  # noqa: E402

import blendkit  # noqa: E402
from blendkit import MaterialSpec  # noqa: E402


# ── Grid and cross-section, all metres ──────────────────────────────────────

GRID = 2.5
"""Snap grid, both horizontal axes. Every §12 length divides by it."""

WALL_T = 0.15
FLOOR_T = 0.15
CEIL_T = 0.15

CLEAR_W = GRID - 2 * WALL_T
"""2.20 m clear corridor width. See the module docstring for the §08 derivation."""

CLEAR_H = 3.00
"""Clear corridor height. The monster stands 2.34 m (gen_monster_model.py)."""

HALL_H = 6.00
"""Clear height of the 개방 공간, so a mezzanine gallery can overlook it."""

STOREY = 3.75
"""Floor-top to floor-top rise of one storey; the stairwell's total climb."""

GALLERY_RISE = 3.00
"""Height the observation gallery is placed above the floor it overlooks."""

DOOR_W = CLEAR_W
DOOR_H = 2.40
LEAF_W = DOOR_W / 2.0
"""2.20 m opening as two 1.10 m leaves — a single leaf that wide is not a door."""

BEVEL_W = 0.012
"""A 12 mm chamfer on structural edges. Floors are excluded so tiles stay flush."""


# ── §06 / §12 / §04 numbers this kit is verified against ────────────────────

MONSTER_SPEED = 4.8          # §06
LOS_BREAK_SECONDS = 3.0      # §06 어그로 해제 시야 차단
S_LEG = 10.0                 # §12 S자 통로 구간
MAX_STRAIGHT = 20.0          # §12 직선 통로 최대
OBSERVER_RANGE = 15.0        # §04 관측자
MONSTER_HEIGHT = 2.34        # gen_monster_model.py, §12 corridor constraint
MONSTER_SHOULDER = 0.93      # ditto
TWO_PERSON_CARRY_W = 1.80    # §08 w5 궤짝, two players abreast


# ── Materials ───────────────────────────────────────────────────────────────
#
# The five Floor_* names are contractual: FloorMaterial in Core/Map maps onto them
# and the Listener's whole ability reads through that mapping (§12). Structural
# materials are deliberately *not* named Floor_* so nothing walkable can be
# mis-assigned by a name match.

MAT_SPECS = {
    "Floor_Wood": MaterialSpec("Floor_Wood", (0.26, 0.15, 0.075), roughness=0.78),
    "Floor_Tile": MaterialSpec("Floor_Tile", (0.60, 0.61, 0.58), roughness=0.22),
    "Floor_Gravel": MaterialSpec("Floor_Gravel", (0.29, 0.27, 0.24), roughness=0.96),
    "Floor_Concrete": MaterialSpec("Floor_Concrete", (0.37, 0.37, 0.35), roughness=0.82),
    "Floor_Metal": MaterialSpec("Floor_Metal", (0.41, 0.43, 0.45), roughness=0.34, metallic=0.85),
    "Wall_Structure": MaterialSpec("Wall_Structure", (0.29, 0.28, 0.26), roughness=0.86),
    "Ceiling_Structure": MaterialSpec("Ceiling_Structure", (0.21, 0.21, 0.20), roughness=0.90),
    "Trim_Steel": MaterialSpec("Trim_Steel", (0.34, 0.35, 0.37), roughness=0.38, metallic=0.90),
    "Door_Leaf": MaterialSpec("Door_Leaf", (0.23, 0.14, 0.075), roughness=0.72),
}


def mat(key: str) -> bpy.types.Material:
    """Creates or reuses a material. Safe to call after every reset_scene()."""
    return blendkit.make_material(MAT_SPECS[key])


# ── Low-level builders ──────────────────────────────────────────────────────


def slab(name: str, x0: float, x1: float, y0: float, y1: float,
         z0: float, z1: float, material: bpy.types.Material,
         floor: bool = False) -> bpy.types.Object:
    """A box given as an axis-aligned extent rather than centre+size.

    Every dimension in §12 is expressed as "from here to there", so building from
    extents is the only way to keep the script readable against the design doc.

    `floor=True` prefixes the name with ``F_``, which excludes it from the bevel
    pass — a 12 mm chamfer on a walkable surface would open a light-leaking groove
    at every tile seam.
    """
    sx, sy, sz = x1 - x0, y1 - y0, z1 - z0
    if min(sx, sy, sz) <= 1e-6:
        raise ValueError(f"{name}: degenerate box {sx:.4f}x{sy:.4f}x{sz:.4f}")
    obj = blendkit.add_box(
        ("F_" if floor else "") + name,
        (sx, sy, sz),
        ((x0 + x1) / 2.0, (y0 + y1) / 2.0, (z0 + z1) / 2.0),
    )
    blendkit.assign_material(obj, material)
    return obj


def wall_run(name: str, x0: float, x1: float, y0: float, y1: float,
             material: bpy.types.Material, z0: float = 0.0, z1: float = CLEAR_H,
             openings: Sequence[tuple[float, float, float, float]] = ()) -> list:
    """A wall panel with holes in it, emitted as solid segments, sills and heads.

    `openings` are ``(a0, a1, h0, h1)`` in world coordinates along the wall's long
    axis. Doorways and the barred window are all cut this way so the opening width
    is a stated number rather than an accident of overlapping boxes.
    """
    parts: list = []
    horizontal = (x1 - x0) >= (y1 - y0)
    a0, a1 = (x0, x1) if horizontal else (y0, y1)

    def emit(pa0: float, pa1: float, pz0: float, pz1: float, tag: str) -> None:
        if pa1 - pa0 <= 1e-6 or pz1 - pz0 <= 1e-6:
            return
        if horizontal:
            parts.append(slab(f"{name}_{tag}", pa0, pa1, y0, y1, pz0, pz1, material))
        else:
            parts.append(slab(f"{name}_{tag}", x0, x1, pa0, pa1, pz0, pz1, material))

    cursor = a0
    for i, (oa0, oa1, oh0, oh1) in enumerate(sorted(openings)):
        emit(cursor, oa0, z0, z1, f"seg{i}")
        emit(oa0, oa1, z0, oh0, f"sill{i}")
        emit(oa0, oa1, oh1, z1, f"head{i}")
        cursor = max(cursor, oa1)
    emit(cursor, a1, z0, z1, "segE")
    return parts


def corbels(objs: list, length_axis: str, span: float, material: bpy.types.Material,
            inner_a: float, inner_b: float) -> None:
    """Ceiling brackets every 2.5 m.

    §05 makes the flashlight the only light source, and a flat 2.20 m wall gives its
    cone nothing to break on. These sit at 2.20-2.60 m — above head height, so the
    2.20 m walking width the §08 chest carry needs is untouched.
    """
    n = max(1, int(round(span / GRID)))
    for k in range(n):
        c = k * GRID + GRID / 2.0
        if length_axis == "Y":
            objs.append(slab(f"CorbelA{k}", inner_a, inner_a + 0.10, c - 0.15, c + 0.15,
                             2.20, 2.60, material))
            objs.append(slab(f"CorbelB{k}", inner_b - 0.10, inner_b, c - 0.15, c + 0.15,
                             2.20, 2.60, material))
        else:
            objs.append(slab(f"CorbelA{k}", c - 0.15, c + 0.15, inner_a, inner_a + 0.10,
                             2.20, 2.60, material))
            objs.append(slab(f"CorbelB{k}", c - 0.15, c + 0.15, inner_b - 0.10, inner_b,
                             2.20, 2.60, material))


# ── Corridors ───────────────────────────────────────────────────────────────


def build_straight(length: float) -> Callable[[], list]:
    """A straight corridor of `length` m.

    §12 caps 직선 통로 at 20 m ("넘으면 주자가 죽는다"), so the kit's longest straight
    is 10 m — half the ceiling. Two 10 m pieces butted end to end reach exactly the
    limit and nothing in the kit can exceed it.
    """
    def build() -> list:
        objs: list = []
        w, c = mat("Wall_Structure"), mat("Ceiling_Structure")
        objs.append(slab("Floor", 0, GRID, 0, length, -FLOOR_T, 0.0,
                         mat("Floor_Concrete"), floor=True))
        objs.append(slab("Ceil", 0, GRID, 0, length, CLEAR_H, CLEAR_H + CEIL_T, c))
        objs.append(slab("WallW", 0, WALL_T, 0, length, 0.0, CLEAR_H, w))
        objs.append(slab("WallE", GRID - WALL_T, GRID, 0, length, 0.0, CLEAR_H, w))
        corbels(objs, "Y", length, w, WALL_T, GRID - WALL_T)
        return objs
    return build


def build_corner_l() -> list:
    """A 90° turn in one 2.5 m cell, open on -Y and +X.

    Four of these plus the straights rebuild §12's S-corridor by hand:
    corner + 5 m + 2.5 m = a 10 m leg, exactly.
    """
    objs: list = []
    w, c = mat("Wall_Structure"), mat("Ceiling_Structure")
    objs.append(slab("Floor", 0, GRID, 0, GRID, -FLOOR_T, 0.0,
                     mat("Floor_Concrete"), floor=True))
    objs.append(slab("Ceil", 0, GRID, 0, GRID, CLEAR_H, CLEAR_H + CEIL_T, c))
    objs.append(slab("WallW", 0, WALL_T, 0, GRID, 0.0, CLEAR_H, w))
    objs.append(slab("WallN", WALL_T, GRID, GRID - WALL_T, GRID, 0.0, CLEAR_H, w))
    # The inner corner post carries the ceiling and gives the turn a hard edge to
    # read against — the Runner has to judge this corner at 5.6 m/s (§05).
    objs.append(slab("PostSE", GRID - WALL_T, GRID, 0, WALL_T, 0.0, CLEAR_H, w))
    objs.append(slab("CornerBrace", WALL_T, WALL_T + 0.28, GRID - WALL_T - 0.28,
                     GRID - WALL_T, 2.20, CLEAR_H, w))
    return objs


def build_s_corridor() -> list:
    """§12's 맵의 기본 단위 as a single piece: two 10 m legs, 20 m of path.

    §12 proves this is the only reliable 어그로 해제 structure::

        구간 L = 10m,  총 20m
        통과 시간 = 20 / 4.8 = 4.2초  >=  3초  ✅

    Centreline, measured: (1.25, 0) -> (1.25, 8.75) -> (3.75, 8.75) -> (3.75, 17.5)
    = 8.75 + 2.50 + 8.75 = **20.00 m** exactly. Neither leg's straight sight line
    exceeds 10 m, and entry and exit are on opposite ends so it *connects* two
    places rather than being a hairpin — which is what makes it usable as the
    map's base unit rather than a set piece.
    """
    total_y = 17.5
    objs: list = []
    w, c, fl = mat("Wall_Structure"), mat("Ceiling_Structure"), mat("Floor_Concrete")

    # Leg A occupies x[0, 2.5] y[0, 10]; leg B occupies x[2.5, 5.0] y[7.5, 17.5].
    objs.append(slab("FloorA", 0, GRID, 0, S_LEG, -FLOOR_T, 0.0, fl, floor=True))
    objs.append(slab("FloorB", GRID, 2 * GRID, S_LEG - GRID, total_y, -FLOOR_T, 0.0,
                     fl, floor=True))
    objs.append(slab("CeilA", 0, GRID, 0, S_LEG, CLEAR_H, CLEAR_H + CEIL_T, c))
    objs.append(slab("CeilB", GRID, 2 * GRID, S_LEG - GRID, total_y,
                     CLEAR_H, CLEAR_H + CEIL_T, c))

    # Leg A: west wall full length, east wall stops at the jog, north wall closes it.
    objs.append(slab("A_WallW", 0, WALL_T, 0, S_LEG, 0.0, CLEAR_H, w))
    objs.append(slab("A_WallE", GRID - WALL_T, GRID, 0, S_LEG - GRID, 0.0, CLEAR_H, w))
    objs.append(slab("A_WallN", 0, GRID, S_LEG - WALL_T, S_LEG, 0.0, CLEAR_H, w))
    # Leg B: south wall closes it, west wall starts above the jog.
    objs.append(slab("B_WallS", GRID, 2 * GRID, S_LEG - GRID, S_LEG - GRID + WALL_T,
                     0.0, CLEAR_H, w))
    objs.append(slab("B_WallW", GRID, GRID + WALL_T, S_LEG, total_y, 0.0, CLEAR_H, w))
    objs.append(slab("B_WallE", 2 * GRID - WALL_T, 2 * GRID, S_LEG - GRID, total_y,
                     0.0, CLEAR_H, w))

    corbels(objs, "Y", S_LEG - GRID, w, WALL_T, GRID - WALL_T)
    return objs


def build_junction_t() -> list:
    """A T. §12 needs 순환로 구역당 1+, 전체 3+ — "트리 구조는 사형선고"."""
    objs: list = []
    w, c = mat("Wall_Structure"), mat("Ceiling_Structure")
    objs.append(slab("Floor", 0, GRID, 0, GRID, -FLOOR_T, 0.0,
                     mat("Floor_Concrete"), floor=True))
    objs.append(slab("Ceil", 0, GRID, 0, GRID, CLEAR_H, CLEAR_H + CEIL_T, c))
    objs.append(slab("WallW", 0, WALL_T, 0, GRID, 0.0, CLEAR_H, w))
    objs.append(slab("PostSE", GRID - WALL_T, GRID, 0, WALL_T, 0.0, CLEAR_H, w))
    objs.append(slab("PostNE", GRID - WALL_T, GRID, GRID - WALL_T, GRID, 0.0, CLEAR_H, w))
    objs.append(slab("BeamE", GRID - WALL_T, GRID, WALL_T, GRID - WALL_T,
                     CLEAR_H - 0.30, CLEAR_H, w))
    return objs


def build_junction_cross() -> list:
    """A 4-way. Two of these in a zone make a loop unavoidable (§12)."""
    objs: list = []
    w, c = mat("Wall_Structure"), mat("Ceiling_Structure")
    objs.append(slab("Floor", 0, GRID, 0, GRID, -FLOOR_T, 0.0,
                     mat("Floor_Concrete"), floor=True))
    objs.append(slab("Ceil", 0, GRID, 0, GRID, CLEAR_H, CLEAR_H + CEIL_T, c))
    for nx, ny, tag in ((0, 0, "SW"), (1, 0, "SE"), (0, 1, "NW"), (1, 1, "NE")):
        x0 = 0.0 if nx == 0 else GRID - WALL_T
        y0 = 0.0 if ny == 0 else GRID - WALL_T
        objs.append(slab(f"Post{tag}", x0, x0 + WALL_T, y0, y0 + WALL_T,
                         0.0, CLEAR_H, w))
    # Cross beams: the 4-way has no walls at all, so the ceiling needs carrying and
    # the junction needs something for a flashlight to catch (§05).
    objs.append(slab("BeamX", 0, GRID, GRID / 2 - 0.09, GRID / 2 + 0.09,
                     CLEAR_H - 0.26, CLEAR_H, w))
    objs.append(slab("BeamY", GRID / 2 - 0.09, GRID / 2 + 0.09, 0, GRID,
                     CLEAR_H - 0.26, CLEAR_H, w))
    return objs


def build_dead_end() -> list:
    """A 2.5 x 5 m dead end whose reward is part of the geometry.

    §12 wants 막힌 길 비율 20~25% and pairs it with 막힌 길 보상 = 전리품 · 자재,
    reason: "위험을 감수할 이유". A cap with no reward is the failure mode this piece
    exists to make impossible — the loot plinth and the alcove ship with it.
    """
    depth = 2 * GRID
    objs: list = []
    w, c, st = mat("Wall_Structure"), mat("Ceiling_Structure"), mat("Trim_Steel")
    objs.append(slab("Floor", 0, GRID, 0, depth, -FLOOR_T, 0.0,
                     mat("Floor_Concrete"), floor=True))
    objs.append(slab("Ceil", 0, GRID, 0, depth, CLEAR_H, CLEAR_H + CEIL_T, c))
    objs.append(slab("WallW", 0, WALL_T, 0, depth, 0.0, CLEAR_H, w))
    objs.append(slab("WallE", GRID - WALL_T, GRID, 0, depth, 0.0, CLEAR_H, w))

    # North wall, built around a 1.25 x 0.22 x 1.35 m alcove over a 0.55 m shelf.
    ny0, ny1 = depth - 0.30, depth
    objs.append(slab("N_L", WALL_T, 0.70, ny0, ny1, 0.0, CLEAR_H, w))
    objs.append(slab("N_R", 1.95, GRID - WALL_T, ny0, ny1, 0.0, CLEAR_H, w))
    objs.append(slab("N_Back", 0.70, 1.95, ny1 - 0.08, ny1, 0.0, CLEAR_H, w))
    objs.append(slab("N_Head", 0.70, 1.95, ny0, ny1 - 0.08, 1.90, CLEAR_H, w))
    objs.append(slab("N_Shelf", 0.70, 1.95, ny0, ny1 - 0.08, 0.0, 0.55, w))
    # The plinth: where the 전리품 sits. Steel, so it reads as salvage staging.
    objs.append(slab("Plinth", 0.90, 1.75, depth - 1.05, depth - 0.50, 0.0, 0.60, st))
    objs.append(slab("PlinthTop", 0.84, 1.81, depth - 1.11, depth - 0.44,
                     0.60, 0.66, st))
    corbels(objs, "Y", depth, w, WALL_T, GRID - WALL_T)
    return objs


# ── Rooms ───────────────────────────────────────────────────────────────────


def build_hall() -> list:
    """The 개방 공간: 20 x 20 m, clear 20 m sight lines, 6 m ceiling.

    §12 requires an open space adjacent to maze space and gives it 시야 15~25m,
    because §12's own table shows the Runner must take aggro from **10 m or more**
    for release to be reliable (at 3 m it fails, at 5 m it is "이론상 겨우"). A 20 m
    hall means the Runner can start the chase at double the minimum.

    The four columns sit on grid at 6.25 / 13.75 m, so the centre lines x = 10 and
    y = 10 stay clear for the full 20 m while the columns still give the 섬광수
    somewhere to work. Two openings per wall (also on grid) exist so the hall can be
    part of a 순환로 — §12: "트리 구조는 사형선고."
    """
    s = 8 * GRID  # 20.0 m
    objs: list = []
    w, c = mat("Wall_Structure"), mat("Ceiling_Structure")
    objs.append(slab("Floor", 0, s, 0, s, -FLOOR_T, 0.0, mat("Floor_Tile"), floor=True))
    objs.append(slab("Ceil", 0, s, 0, s, HALL_H, HALL_H + CEIL_T, c))

    half = CLEAR_W / 2.0
    cuts = [(6.25 - half, 6.25 + half, 0.0, CLEAR_H),
            (13.75 - half, 13.75 + half, 0.0, CLEAR_H)]
    objs += wall_run("WallS", 0, s, 0, WALL_T, w, 0.0, HALL_H, cuts)
    objs += wall_run("WallN", 0, s, s - WALL_T, s, w, 0.0, HALL_H, cuts)
    objs += wall_run("WallW", 0, WALL_T, WALL_T, s - WALL_T, w, 0.0, HALL_H, cuts)
    objs += wall_run("WallE", s - WALL_T, s, WALL_T, s - WALL_T, w, 0.0, HALL_H, cuts)

    for cx in (6.25, 13.75):
        for cy in (6.25, 13.75):
            objs.append(slab(f"Col{cx:.0f}_{cy:.0f}", cx - 0.25, cx + 0.25,
                             cy - 0.25, cy + 0.25, 0.0, HALL_H, w))
            objs.append(slab(f"Cap{cx:.0f}_{cy:.0f}", cx - 0.38, cx + 0.38,
                             cy - 0.38, cy + 0.38, HALL_H - 0.30, HALL_H, w))
    return objs


def build_stairwell() -> list:
    """A metal dog-leg stair climbing one storey (3.75 m). §12 gives stairs 금속.

    §12's Listener table assigns 계단 = 금속 / 울림 — its own material, distinct from
    all four zone surfaces, because a stair is the one place the Listener needs to
    know the monster changed *level*. Treads, landings and the shaft floor are all
    ``Floor_Metal`` and nothing else in the kit uses it as a walking surface.

    9 treads per flight, 0.2083 m rise x 0.30 m going, 2.20 m clear stair width.
    The spine wall between the flights breaks line of sight between them, so the
    stairwell is also a 연속 차단 structure and not just vertical circulation. The
    void under the upper flight is 1.73 m high — §12's checklist wants 은폐 지점.
    """
    s = 2 * GRID  # 5.0 m square shaft
    flights, steps = 2, 9
    rise = STOREY / (flights * steps)     # 0.208333 m
    going = 0.30
    run = steps * going                   # 2.70 m
    y_foot, y_head = 0.40, 0.40 + run     # 0.40 -> 3.10
    top_h = STOREY + CLEAR_H              # wall height, 6.75 m

    objs: list = []
    w, c, fm = mat("Wall_Structure"), mat("Ceiling_Structure"), mat("Floor_Metal")
    objs.append(slab("Floor", 0, s, 0, s, -FLOOR_T, 0.0, fm, floor=True))
    objs.append(slab("Ceil", 0, s, 0, s, top_h, top_h + CEIL_T, c))

    ax0, ax1 = WALL_T, WALL_T + CLEAR_W           # 0.15 .. 2.35
    bx0, bx1 = s - WALL_T - CLEAR_W, s - WALL_T   # 2.65 .. 4.85

    for k in range(steps):  # flight A: ascends +Y from 0 to 1.875 m
        objs.append(slab(f"A_Step{k}", ax0, ax1, y_foot + k * going,
                         y_foot + (k + 1) * going, 0.0, (k + 1) * rise, fm, floor=True))
    objs.append(slab("MidLanding", ax0, bx1, y_head, s - WALL_T,
                     STOREY / 2 - FLOOR_T, STOREY / 2, fm, floor=True))
    for k in range(steps):  # flight B: ascends -Y from 1.875 to 3.75 m
        objs.append(slab(f"B_Step{k}", bx0, bx1, y_head - (k + 1) * going,
                         y_head - k * going, STOREY / 2 - FLOOR_T,
                         STOREY / 2 + (k + 1) * rise, fm, floor=True))
    objs.append(slab("TopLanding", bx0, bx1, WALL_T, y_foot,
                     STOREY - FLOOR_T, STOREY, fm, floor=True))

    # Spine wall: steps up with flight A, so neither flight can see the other.
    for k in range(steps):
        objs.append(slab(f"Spine{k}", ax1, bx0, y_foot + k * going,
                         y_foot + (k + 1) * going, 0.0, (k + 1) * rise + 1.05, w))
    objs.append(slab("SpineTop", ax1, bx0, y_head, s - WALL_T, 0.0, STOREY / 2 + 1.05, w))

    # Perimeter. The -Y wall carries both the lower entry and the upper exit, which
    # is what makes this piece the join between two storeys of the grid.
    objs += wall_run("WallS", 0, s, 0, WALL_T, w, 0.0, top_h, [
        (ax0, ax1, 0.0, CLEAR_H),
        (bx0, bx1, STOREY, top_h),
    ])
    objs += wall_run("WallN", 0, s, s - WALL_T, s, w, 0.0, top_h)
    objs += wall_run("WallW", 0, WALL_T, WALL_T, s - WALL_T, w, 0.0, top_h)
    objs += wall_run("WallE", s - WALL_T, s, WALL_T, s - WALL_T, w, 0.0, top_h)
    return objs


def build_gallery() -> list:
    """A 15 m raised walkway with a barred parapet — §04's Observer post.

    §04: the Observer reads the monster's vision from **within 15 m**, holding still
    3 s. §12: "높이 차(2층 난간) · 창문 · 격자 등 15m 거리에서 안전하게 괴물을 볼 수 있는
    지점을 구역당 1~2개 배치. 없으면 관측자는 죽으러 가야 한다."

    So 15 m is the piece's length, not a coincidence: an Observer standing at one end
    covers the whole deck at exactly the ability's range. Placed at
    ``GALLERY_RISE`` = 3.00 m above the floor it overlooks, a monster at 14.70 m
    horizontally is at a slant range of exactly 15.00 m — inside the 20 m hall, so
    the geometry actually delivers the number.

    Safety is structural: a 0.35 m kerb, 0.75 m of steel bars at 0.75 m centres and a
    top rail at 1.05-1.20 m. The deck is ``Floor_Concrete`` rather than metal on
    purpose — §12 reserves 금속 for stairs, and a ringing catwalk would put a false
    stairwell into the Listener's map.
    """
    length = 6 * GRID  # 15.0 m
    objs: list = []
    w, c, st = mat("Wall_Structure"), mat("Ceiling_Structure"), mat("Trim_Steel")
    objs.append(slab("Deck", 0, GRID, 0, length, -FLOOR_T, 0.0,
                     mat("Floor_Concrete"), floor=True))
    objs.append(slab("Ceil", 0, GRID, 0, length, CLEAR_H, CLEAR_H + CEIL_T, c))
    objs.append(slab("BackWall", 0, WALL_T, 0, length, 0.0, CLEAR_H, w))
    objs.append(slab("Kerb", GRID - WALL_T, GRID, 0, length, 0.0, 0.35, w))
    objs.append(slab("TopRail", GRID - WALL_T, GRID, 0, length, 1.05, 1.20, st))
    n_bars = int(round(length / 0.75))
    for k in range(n_bars):
        yc = (k + 0.5) * (length / n_bars)
        objs.append(slab(f"Bar{k}", GRID - 0.125, GRID - 0.070,
                         yc - 0.025, yc + 0.025, 0.35, 1.10, st))
    # Both ends stay open — §12 wants every worthwhile spot to have two escape
    # routes. Only a header beam closes them off overhead.
    objs.append(slab("HeadS", WALL_T, GRID - WALL_T, 0, WALL_T, DOOR_H, CLEAR_H, w))
    objs.append(slab("HeadN", WALL_T, GRID - WALL_T, length - WALL_T, length,
                     DOOR_H, CLEAR_H, w))
    return objs


def build_barred_window() -> list:
    """A 2.5 m alcove with a barred window — the cheap Observer post.

    The other half of §12's "창문 · 격자" requirement, for zones with no height
    difference to exploit. The Observer stands in the alcove and reads the monster
    through the grating; the 0.13 m bar gaps are far narrower than the monster's
    0.93 m shoulders, so the post is safe in the literal sense §12 asks for.
    """
    objs: list = []
    w, c, st = mat("Wall_Structure"), mat("Ceiling_Structure"), mat("Trim_Steel")
    objs.append(slab("Floor", 0, GRID, 0, GRID, -FLOOR_T, 0.0,
                     mat("Floor_Concrete"), floor=True))
    objs.append(slab("Ceil", 0, GRID, 0, GRID, CLEAR_H, CLEAR_H + CEIL_T, c))
    objs.append(slab("WallW", 0, WALL_T, 0, GRID, 0.0, CLEAR_H, w))
    objs.append(slab("WallN", WALL_T, GRID - WALL_T, GRID - WALL_T, GRID,
                     0.0, CLEAR_H, w))
    win_y0, win_y1, win_z0, win_z1 = 0.30, 2.20, 1.00, 2.20
    objs += wall_run("WallE", GRID - WALL_T, GRID, 0, GRID, w, 0.0, CLEAR_H,
                     [(win_y0, win_y1, win_z0, win_z1)])
    objs.append(slab("Sill", GRID - WALL_T - 0.06, GRID, win_y0, win_y1, 0.92, 1.00, w))
    n_bars = 10
    span = (win_y1 - win_y0 - 0.06) / (n_bars - 1)
    for k in range(n_bars):
        yc = win_y0 + 0.03 + k * span
        objs.append(slab(f"Bar{k}", GRID - WALL_T, GRID, yc - 0.03, yc + 0.03,
                         win_z0, win_z1, st))
    objs.append(slab("Mullion", GRID - WALL_T, GRID, win_y0, win_y1, 1.57, 1.63, st))
    return objs


# ── Doors (§04 Engineer, §12 병목) ──────────────────────────────────────────


def build_doorway_frame() -> list:
    """A 2.5 m cell with a 2.20 x 2.40 m framed opening across it.

    §12 puts 잠글 수 있는 문 1~2개 per zone at bottlenecks, and singles out the neck
    of a 순환로: "잠그면 순환이 끊김 (전략적 선택)". The opening is the full 2.20 m
    corridor width because §03's objective has to come *out* through it and §08 makes
    the w5 궤짝 a two-person carry — a 1.2 m single door would silently make the
    objective uncarryable.

    Hinge pintles stand 0.06 m proud of each jamb, so the tightest clear passage in
    the whole kit is 2.08 m. That is the number to check against §08, and it passes.
    """
    objs: list = []
    w, c, st = mat("Wall_Structure"), mat("Ceiling_Structure"), mat("Trim_Steel")
    objs.append(slab("Floor", 0, GRID, 0, GRID, -FLOOR_T, 0.0,
                     mat("Floor_Concrete"), floor=True))
    objs.append(slab("Ceil", 0, GRID, 0, GRID, CLEAR_H, CLEAR_H + CEIL_T, c))
    objs.append(slab("WallW", 0, WALL_T, 0, GRID, 0.0, CLEAR_H, w))
    objs.append(slab("WallE", GRID - WALL_T, GRID, 0, GRID, 0.0, CLEAR_H, w))

    cy0, cy1 = GRID / 2 - WALL_T / 2, GRID / 2 + WALL_T / 2   # 1.175 .. 1.325
    objs.append(slab("Lintel", WALL_T, GRID - WALL_T, cy0, cy1, DOOR_H, CLEAR_H, w))
    # Head casing sits on the wall faces above the opening, so it costs no width.
    objs.append(slab("HeadCaseA", WALL_T, GRID - WALL_T, cy0 - 0.10, cy0,
                     DOOR_H, DOOR_H + 0.12, st))
    objs.append(slab("HeadCaseB", WALL_T, GRID - WALL_T, cy1, cy1 + 0.10,
                     DOOR_H, DOOR_H + 0.12, st))
    # Threshold sits *below* z = 0 so it is flush with the floor: no trip, and the
    # door line still reads as a hard material seam under a flashlight.
    objs.append(slab("Threshold", WALL_T, GRID - WALL_T, cy0, cy1, -0.025, 0.0, st))
    for k, z in enumerate((0.20, 1.10, 2.15)):
        objs.append(slab(f"PintleW{k}", WALL_T, WALL_T + 0.06, cy0 - 0.05, cy0,
                         z, z + 0.14, st))
        objs.append(slab(f"PintleE{k}", GRID - WALL_T - 0.06, GRID - WALL_T,
                         cy0 - 0.05, cy0, z, z + 0.14, st))
    # Strike keep at the meeting stile: what the Engineer's lock actually engages.
    objs.append(slab("StrikeKeep", GRID / 2 - 0.05, GRID / 2 + 0.05, cy1, cy1 + 0.07,
                     1.02, 1.32, st))
    return objs


def build_door_panel() -> list:
    """One lockable leaf, 1.10 x 2.40 m, hinged on its own origin.

    Two of these fill a ``Doorway_Frame`` (2 x 1.10 = 2.20 m). The origin is the
    hinge axis, so Unity rotates the transform directly with no pivot fixing — which
    matters because §04's Engineer locks and unlocks these live and §04 warns the
    role's mistakes kill teammates ("문 안에 아군"), so the door has to animate
    honestly rather than teleport between states.

    This piece is a **prop, not a grid tile** — it is placed by the frame's hinge
    point, so its footprint is deliberately not a multiple of 2.5 m.
    """
    objs: list = []
    d, st = mat("Door_Leaf"), mat("Trim_Steel")
    objs.append(slab("Core", 0, LEAF_W, 0.03, 0.09, 0.0, DOOR_H, d))
    for face_y0, face_y1, side in ((0.0, 0.03, "A"), (0.09, 0.12, "B")):
        objs.append(slab(f"StileL{side}", 0.0, 0.14, face_y0, face_y1, 0.0, DOOR_H, d))
        objs.append(slab(f"StileR{side}", LEAF_W - 0.14, LEAF_W, face_y0, face_y1,
                         0.0, DOOR_H, d))
        objs.append(slab(f"RailB{side}", 0.14, LEAF_W - 0.14, face_y0, face_y1,
                         0.0, 0.22, d))
        objs.append(slab(f"RailM{side}", 0.14, LEAF_W - 0.14, face_y0, face_y1,
                         1.05, 1.25, d))
        objs.append(slab(f"RailT{side}", 0.14, LEAF_W - 0.14, face_y0, face_y1,
                         DOOR_H - 0.18, DOOR_H, d))
    for k, z in enumerate((0.20, 1.10, 2.15)):
        objs.append(slab(f"Hinge{k}", 0.0, 0.13, 0.12, 0.145, z, z + 0.14, st))
    # Deadbolt housing + lever: the visible state of §04's lock ability.
    objs.append(slab("BoltHousing", LEAF_W - 0.16, LEAF_W - 0.02, 0.0, 0.155,
                     1.00, 1.34, st))
    objs.append(slab("LeverRose", LEAF_W - 0.26, LEAF_W - 0.16, 0.0, 0.155,
                     1.05, 1.15, st))
    objs.append(slab("Lever", LEAF_W - 0.30, LEAF_W - 0.18, 0.155, 0.175,
                     1.07, 1.13, st))
    # Meeting-stile plate: with two leaves hung, this laps the joint so no light
    # (§03's lock on progress) leaks through a closed door.
    objs.append(slab("MeetPlate", LEAF_W - 0.10, LEAF_W, 0.145, 0.175, 0.0, DOOR_H, st))
    return objs


def build_electrical_panel() -> list:
    """A wall-mounted breaker panel. §12: 전기 패널 구역당 1개.

    §03 makes darkness the lock on the objective and §12 requires every clue site to
    have 전기 패널 접근 가능 so the Engineer can light it (§04: "조명으로 단서를 읽게
    만든다"). Also a **prop, not a grid tile**.
    """
    objs: list = []
    st, w = mat("Trim_Steel"), mat("Wall_Structure")
    objs.append(slab("Box", 0.0, 0.62, 0.0, 0.16, 0.0, 0.90, st))
    objs.append(slab("DoorLeaf", 0.02, 0.60, 0.16, 0.20, 0.03, 0.87, st))
    objs.append(slab("Latch", 0.54, 0.62, 0.16, 0.23, 0.40, 0.52, st))
    objs.append(slab("MainLever", 0.10, 0.18, 0.16, 0.26, 0.60, 0.78, st))
    for k in range(4):
        objs.append(slab(f"Breaker{k}", 0.24 + k * 0.09, 0.30 + k * 0.09,
                         0.16, 0.21, 0.30, 0.44, st))
    objs.append(slab("ConduitUp", 0.26, 0.36, 0.02, 0.12, 0.90, 1.40, w))
    objs.append(slab("ConduitDn", 0.26, 0.36, 0.02, 0.12, -0.50, 0.0, w))
    return objs


# ── Floor tiles: §12's gameplay channel ─────────────────────────────────────
#
# §12 is explicit that this is a systems decision, not an art one, and that the
# boundary must be unambiguous. §05 says the game is dark and lit by a narrow
# flashlight cone, so colour cannot be the whole signal — every tile therefore has
# distinct *relief* as well, and every relief pattern keeps its contact plane at
# exactly z = 0 so tiles of different materials butt together without a step.

TILE = 2 * GRID  # 5.0 m square


def build_tile_wood() -> list:
    """Zone A — 나무 / 삐걱. Ten 0.5 m planks with open joints."""
    objs: list = []
    m = mat("Floor_Wood")
    objs.append(slab("Base", 0, TILE, 0, TILE, -FLOOR_T, -0.022, m, floor=True))
    n = 10
    pitch = TILE / n
    for k in range(n):
        x0 = k * pitch + 0.012
        objs.append(slab(f"Plank{k}", x0, x0 + pitch - 0.024, 0, TILE,
                         -0.022, 0.0, m, floor=True))
    return objs


def build_tile_tile() -> list:
    """Zone B — 타일 / 딱딱, 반향. A 10 x 10 grid of 0.5 m tiles with grout lines."""
    objs: list = []
    m = mat("Floor_Tile")
    objs.append(slab("Base", 0, TILE, 0, TILE, -FLOOR_T, -0.018, m, floor=True))
    n = 10
    pitch = TILE / n
    for i in range(n):
        for j in range(n):
            objs.append(slab(f"T{i}_{j}", i * pitch + 0.011, (i + 1) * pitch - 0.011,
                             j * pitch + 0.011, (j + 1) * pitch - 0.011,
                             -0.018, 0.0, m, floor=True))
    return objs


def build_tile_gravel() -> list:
    """Zone C — 자갈 / 부스럭. A jittered surface, seeded so rebuilds are identical.

    Built with bmesh rather than boxes: an irregular walking surface is what makes
    gravel unmistakable in a flashlight cone, and it costs a fraction of the
    triangles that a few hundred pebble boxes would. The perimeter ring is pinned to
    z = 0 so the tile still butts flush against every other material.
    """
    rng = random.Random(0xC0FFEE)
    n = 20
    step = TILE / n
    mesh = bpy.data.meshes.new("F_GravelMesh")
    obj = bpy.data.objects.new("F_GravelTop", mesh)
    bpy.context.collection.objects.link(obj)

    bm = bmesh.new()
    grid = []
    for i in range(n + 1):
        row = []
        for j in range(n + 1):
            edge = i in (0, n) or j in (0, n)
            z = 0.0 if edge else -rng.uniform(0.008, 0.055)
            row.append(bm.verts.new((i * step, j * step, z)))
        grid.append(row)
    for i in range(n):
        for j in range(n):
            bm.faces.new((grid[i][j], grid[i + 1][j], grid[i + 1][j + 1], grid[i][j + 1]))

    ring = []
    for i in range(n):
        ring.append(grid[i][0])
    for j in range(n):
        ring.append(grid[n][j])
    for i in range(n, 0, -1):
        ring.append(grid[i][n])
    for j in range(n, 0, -1):
        ring.append(grid[0][j])
    bottom = [bm.verts.new((v.co.x, v.co.y, -FLOOR_T)) for v in ring]
    for k in range(len(ring)):
        nk = (k + 1) % len(ring)
        bm.faces.new((ring[k], ring[nk], bottom[nk], bottom[k]))
    bm.faces.new(tuple(reversed(bottom)))
    bmesh.ops.recalc_face_normals(bm, faces=bm.faces[:])
    bm.to_mesh(mesh)
    bm.free()
    mesh.update()
    blendkit.assign_material(obj, mat("Floor_Gravel"))
    return [obj]


def build_tile_concrete() -> list:
    """Zone D — 콘크리트 / 둔탁. Four poured slabs and a control joint. Flat on purpose."""
    objs: list = []
    m = mat("Floor_Concrete")
    objs.append(slab("Base", 0, TILE, 0, TILE, -FLOOR_T, -0.012, m, floor=True))
    for i in range(2):
        for j in range(2):
            objs.append(slab(f"Slab{i}{j}", i * GRID + 0.014, (i + 1) * GRID - 0.014,
                             j * GRID + 0.014, (j + 1) * GRID - 0.014,
                             -0.012, 0.0, m, floor=True))
    return objs


def build_tile_metal() -> list:
    """계단 — 금속 / 울림. Checker plate with raised tread ribs.

    §12 gives 금속 to stairs alone, so this tile is for stair landings, catwalks and
    plant rooms. The cross-hatched ribs are the loudest relief in the kit, which is
    the point: metal is the surface the Listener must never confuse with the four
    zone materials.
    """
    objs: list = []
    m = mat("Floor_Metal")
    objs.append(slab("Base", 0, TILE, 0, TILE, -FLOOR_T, -0.020, m, floor=True))
    for i in range(2):
        for j in range(2):
            objs.append(slab(f"Plate{i}{j}", i * GRID + 0.010, (i + 1) * GRID - 0.010,
                             j * GRID + 0.010, (j + 1) * GRID - 0.010,
                             -0.020, -0.006, m, floor=True))
    n = 12
    pitch = TILE / n
    for k in range(n):
        c = (k + 0.5) * pitch
        objs.append(slab(f"RibX{k}", 0, TILE, c - 0.035, c + 0.035, -0.006, 0.0,
                         m, floor=True))
        objs.append(slab(f"RibY{k}", c - 0.035, c + 0.035, 0, TILE, -0.006, 0.0,
                         m, floor=True))
    return objs


def build_floor_boundary() -> list:
    """The material change itself, made a piece. §12: "재질 경계를 명확히 할 것."

    The Listener reads the monster's position from which surface its feet land on
    (§04, §12), so an ambiguous boundary is not a cosmetic flaw — it is a broken
    ability. This 5.0 x 2.5 m piece puts two surfaces edge to edge across a 0.20 m
    recessed channel, 0.03 m deep: the seam casts a shadow line at any flashlight
    angle, and a footstep can only ever sample one side of it or the other.

    The two slots ship as ``Floor_Concrete`` and ``Floor_Wood`` (§12's D/A pair) and
    are meant to be reassigned per adjacency in Unity — the contractual names make
    that a rename, not a re-export.
    """
    objs: list = []
    a, b = mat("Floor_Concrete"), mat("Floor_Wood")
    mid = GRID / 2.0
    objs.append(slab("SideA", 0, TILE, 0, mid - 0.10, -FLOOR_T, 0.0, a, floor=True))
    objs.append(slab("Channel", 0, TILE, mid - 0.10, mid + 0.10, -FLOOR_T, -0.030,
                     a, floor=True))
    objs.append(slab("SideB", 0, TILE, mid + 0.10, GRID, -FLOOR_T, 0.0, b, floor=True))
    return objs


# ── Piece registry ──────────────────────────────────────────────────────────


@dataclass
class PieceSpec:
    """One exported piece and everything the verification pass checks it against."""

    name: str
    build: Callable[[], list]
    footprint: tuple[float, float] | None
    """Nominal footprint in metres, or None for props that are not grid tiles."""
    max_straight: float
    """Longest unobstructed straight run inside the piece. §12 caps this at 20 m."""
    max_tris: int
    kind: str
    floor_slot: str
    docks: list = field(default_factory=list)
    note: str = ""


def docks_ns(length: float, level: float = 0.0) -> list:
    """Dock points at both ends of a corridor running along +Y."""
    return [
        {"edge": "-Y", "centre": [GRID / 2, 0.0], "width": CLEAR_W, "height": CLEAR_H, "level": level},
        {"edge": "+Y", "centre": [GRID / 2, length], "width": CLEAR_W, "height": CLEAR_H, "level": level},
    ]


PIECES: list[PieceSpec] = [
    PieceSpec("Corridor_Straight_2m5", build_straight(GRID), (GRID, GRID), GRID, 2500,
              "corridor", "Floor_Concrete", docks_ns(GRID),
              "Grid-unit filler. corner + 5 m + 2.5 m = a 10 m S-corridor leg."),
    PieceSpec("Corridor_Straight_5m", build_straight(2 * GRID), (GRID, 2 * GRID),
              2 * GRID, 2500, "corridor", "Floor_Concrete", docks_ns(2 * GRID),
              "§12 straight section, 5 m."),
    PieceSpec("Corridor_Straight_10m", build_straight(4 * GRID), (GRID, 4 * GRID),
              4 * GRID, 3000, "corridor", "Floor_Concrete", docks_ns(4 * GRID),
              "§12 straight section, 10 m. Longest straight in the kit — half the 20 m cap."),
    PieceSpec("Corridor_Corner_L", build_corner_l, (GRID, GRID), GRID, 2500,
              "corridor", "Floor_Concrete",
              [{"edge": "-Y", "centre": [GRID / 2, 0.0], "width": CLEAR_W, "height": CLEAR_H, "level": 0.0},
               {"edge": "+X", "centre": [GRID, GRID / 2], "width": CLEAR_W, "height": CLEAR_H, "level": 0.0}],
              "90° turn. Composes the S-corridor by hand."),
    PieceSpec("SCorridor_Unit_10m_x2", build_s_corridor, (2 * GRID, 7 * GRID),
              S_LEG, 4000, "corridor", "Floor_Concrete",
              [{"edge": "-Y", "centre": [GRID / 2, 0.0], "width": CLEAR_W, "height": CLEAR_H, "level": 0.0},
               {"edge": "+Y", "centre": [1.5 * GRID, 7 * GRID], "width": CLEAR_W, "height": CLEAR_H, "level": 0.0}],
              "§12 맵의 기본 단위: two 10 m legs, 20.00 m of path, 4.17 s of broken sight."),
    PieceSpec("Junction_T", build_junction_t, (GRID, GRID), GRID, 2500,
              "junction", "Floor_Concrete",
              [{"edge": "-Y", "centre": [GRID / 2, 0.0], "width": CLEAR_W, "height": CLEAR_H, "level": 0.0},
               {"edge": "+Y", "centre": [GRID / 2, GRID], "width": CLEAR_W, "height": CLEAR_H, "level": 0.0},
               {"edge": "+X", "centre": [GRID, GRID / 2], "width": CLEAR_W, "height": CLEAR_H, "level": 0.0}],
              "§12 분기 / loop feeder."),
    PieceSpec("Junction_Cross_4Way", build_junction_cross, (GRID, GRID), GRID, 2500,
              "junction", "Floor_Concrete",
              [{"edge": e, "centre": c, "width": CLEAR_W, "height": CLEAR_H, "level": 0.0}
               for e, c in (("-Y", [GRID / 2, 0.0]), ("+Y", [GRID / 2, GRID]),
                            ("-X", [0.0, GRID / 2]), ("+X", [GRID, GRID / 2]))],
              "§12 순환로: 전체 3+ required, 트리 구조는 사형선고."),
    PieceSpec("DeadEnd_Cap", build_dead_end, (GRID, 2 * GRID), 2 * GRID, 3000,
              "deadend", "Floor_Concrete",
              [{"edge": "-Y", "centre": [GRID / 2, 0.0], "width": CLEAR_W, "height": CLEAR_H, "level": 0.0}],
              "§12 막힌 길 20~25%, each with a reward — plinth + alcove built in."),
    PieceSpec("Hall_Open_20x20", build_hall, (8 * GRID, 8 * GRID), 8 * GRID, 9000,
              "open", "Floor_Tile",
              [{"edge": e, "centre": c, "width": CLEAR_W, "height": CLEAR_H, "level": 0.0}
               for e, c in (("-Y", [6.25, 0.0]), ("-Y", [13.75, 0.0]),
                            ("+Y", [6.25, 20.0]), ("+Y", [13.75, 20.0]),
                            ("-X", [0.0, 6.25]), ("-X", [0.0, 13.75]),
                            ("+X", [20.0, 6.25]), ("+X", [20.0, 13.75]))],
              "§12 개방 공간, 20 m sight line. §12's own table: aggro at 10 m+ is where escape is reliable."),
    PieceSpec("Stairwell_Metal", build_stairwell, (2 * GRID, 2 * GRID), 2 * GRID, 9000,
              "stair", "Floor_Metal",
              [{"edge": "-Y", "centre": [1.25, 0.0], "width": CLEAR_W, "height": CLEAR_H, "level": 0.0},
               {"edge": "-Y", "centre": [3.75, 0.0], "width": CLEAR_W, "height": CLEAR_H, "level": STOREY}],
              "§12 계단 = 금속. Climbs one storey (3.75 m); spine wall breaks sight between flights."),
    PieceSpec("ObservationPost_Gallery", build_gallery, (GRID, 6 * GRID), 6 * GRID, 9000,
              "observation", "Floor_Concrete",
              [{"edge": "-Y", "centre": [GRID / 2, 0.0], "width": CLEAR_W, "height": DOOR_H, "level": 0.0},
               {"edge": "+Y", "centre": [GRID / 2, 15.0], "width": CLEAR_W, "height": DOOR_H, "level": 0.0}],
              "§04 관측자 15 m. Place at +3.00 m over a floor: 14.70 m horizontal = 15.00 m slant."),
    PieceSpec("ObservationPost_BarredWindow", build_barred_window, (GRID, GRID), GRID, 4000,
              "observation", "Floor_Concrete",
              [{"edge": "-Y", "centre": [GRID / 2, 0.0], "width": CLEAR_W, "height": CLEAR_H, "level": 0.0}],
              "§12 창문 · 격자 variant. 0.14 m bar gaps vs the monster's 0.93 m shoulders."),
    PieceSpec("Doorway_Frame", build_doorway_frame, (GRID, GRID), GRID, 3000,
              "door", "Floor_Concrete", docks_ns(GRID),
              "§12 병목. 2.20 x 2.40 m opening; 2.08 m at the hinge pintles."),
    PieceSpec("Door_Panel_Lockable", build_door_panel, None, LEAF_W, 3000,
              "prop", "-", [],
              "PROP, not a grid tile. Hinge on origin. Two leaves fill one Doorway_Frame."),
    PieceSpec("WallPanel_Electrical", build_electrical_panel, None, 0.62, 2000,
              "prop", "-", [],
              "PROP. §12 전기 패널 구역당 1개 — §04's Engineer lights the clue."),
    PieceSpec("FloorTile_Wood", build_tile_wood, (TILE, TILE), TILE, 5000,
              "floor", "Floor_Wood", [], "§12 구역 A — 삐걱. Plank relief."),
    PieceSpec("FloorTile_Tile", build_tile_tile, (TILE, TILE), TILE, 6000,
              "floor", "Floor_Tile", [], "§12 구역 B — 딱딱, 반향. 0.5 m grid, grout lines."),
    PieceSpec("FloorTile_Gravel", build_tile_gravel, (TILE, TILE), TILE, 5000,
              "floor", "Floor_Gravel", [], "§12 구역 C — 부스럭. Jittered surface, seeded."),
    PieceSpec("FloorTile_Concrete", build_tile_concrete, (TILE, TILE), TILE, 5000,
              "floor", "Floor_Concrete", [], "§12 구역 D — 둔탁. Poured slabs, flat on purpose."),
    PieceSpec("FloorTile_Metal", build_tile_metal, (TILE, TILE), TILE, 5000,
              "floor", "Floor_Metal", [], "§12 계단 — 울림. Checker plate, cross-hatched ribs."),
    PieceSpec("FloorBoundary_Split", build_floor_boundary, (TILE, GRID), TILE, 1500,
              "floor", "Floor_Concrete + Floor_Wood", [],
              "§12 재질 경계를 명확히 할 것. 0.20 m x 0.03 m recessed channel between two slots."),
]


# ── Build pipeline ──────────────────────────────────────────────────────────


def build_piece(spec: PieceSpec) -> tuple[blendkit.AssetReport, list]:
    """Builds, joins, verifies and exports one piece in a clean scene."""
    blendkit.reset_scene()
    bpy.context.scene.cursor.location = (0.0, 0.0, 0.0)

    objs = spec.build()
    if not objs:
        raise AssertionError(f"{spec.name}: builder produced no objects")

    floors = [o for o in objs if o.name.startswith("F_")]
    struct = [o for o in objs if not o.name.startswith("F_")]
    parts = []
    if struct:
        s = blendkit.join(struct, spec.name + "_S")
        blendkit.bevel(s, BEVEL_W, 1)
        parts.append(s)
    if floors:
        parts.append(blendkit.join(floors, spec.name + "_F"))

    piece = blendkit.join(parts, spec.name)
    blendkit.triangulate(piece)

    bpy.ops.object.select_all(action="DESELECT")
    piece.select_set(True)
    bpy.context.view_layer.objects.active = piece
    bpy.ops.object.origin_set(type="ORIGIN_CURSOR")
    try:
        blendkit.uv_smart_project(piece)
    except Exception:  # noqa: BLE001 — UVs are a refinement, not a gate.
        print(f"NOTE {spec.name}: smart UV project skipped")

    slots = [m.name if m else "<none>" for m in piece.data.materials]
    path = blendkit.out_path("MapKit", spec.name + ".fbx")
    blendkit.export_fbx(path, [piece])

    report = blendkit.describe(path)
    blendkit.assert_asset(report, min_vertices=8, max_triangles=spec.max_tris,
                          max_dimension=25.0)
    verify_piece(spec, report)
    blendkit.print_report(report)
    return report, slots


def verify_piece(spec: PieceSpec, report: blendkit.AssetReport) -> None:
    """The §12 checks. A piece that fails one of these cannot be placed safely."""
    sx, sy, sz = report.size
    lo = report.bounds_min

    if abs(lo[0]) > 1e-4 or abs(lo[1]) > 1e-4:
        raise AssertionError(
            f"{spec.name}: origin is not the min-X/min-Y corner — bounds_min="
            f"({lo[0]:.4f}, {lo[1]:.4f}). A level placed on grid coordinates would drift.")

    if max(sx, sy) > MAX_STRAIGHT + 1e-4:
        raise AssertionError(
            f"{spec.name}: footprint {sx:.2f} x {sy:.2f} m exceeds §12's 20 m — "
            "'직선 통로 최대 20m, 넘으면 주자가 죽는다'.")

    if spec.max_straight > MAX_STRAIGHT + 1e-4:
        raise AssertionError(
            f"{spec.name}: declared straight run {spec.max_straight:.2f} m exceeds §12's 20 m.")

    if spec.footprint is not None:
        ex, ey = spec.footprint
        if abs(sx - ex) > 2e-3 or abs(sy - ey) > 2e-3:
            raise AssertionError(
                f"{spec.name}: measured footprint {sx:.4f} x {sy:.4f} m, expected {ex} x {ey}.")
        for axis, v in (("X", sx), ("Y", sy)):
            cells = v / GRID
            if abs(cells - round(cells)) > 1e-4:
                raise AssertionError(
                    f"{spec.name}: {axis} footprint {v:.4f} m is not a multiple of the "
                    f"{GRID} m grid ({cells:.4f} cells).")
        if abs(lo[2] + FLOOR_T) > 1e-4:
            raise AssertionError(
                f"{spec.name}: floor top is not at z = 0 — bounds_min.z={lo[2]:.4f}, "
                f"expected {-FLOOR_T}.")
    if sz <= 0.05:
        raise AssertionError(f"{spec.name}: height {sz:.3f} m — the piece is flat.")


# ── §12 rule confirmations, computed rather than asserted by hand ────────────


def design_checks() -> list[tuple[bool, str]]:
    """Recomputes §12's own arithmetic against the numbers this kit was built from."""
    s_path = (S_LEG - GRID / 2) + GRID + (S_LEG - GRID / 2)
    s_time = s_path / MONSTER_SPEED
    reach = math.sqrt(OBSERVER_RANGE ** 2 - GALLERY_RISE ** 2)
    door_clear = CLEAR_W - 2 * 0.06
    bar_gap = (2.20 - 0.30 - 0.06) / 9 - 0.06
    return [
        (abs(s_path - 2 * S_LEG) < 1e-6,
         f"S-corridor centreline path = {s_path:.2f} m (§12 requires 10 m x 2 = 20 m)"),
        (s_time >= LOS_BREAK_SECONDS,
         f"S-corridor traversal = {s_path:.2f} / {MONSTER_SPEED} = {s_time:.2f} s "
         f">= {LOS_BREAK_SECONDS} s of broken sight (§06)"),
        (4 * GRID <= MAX_STRAIGHT,
         f"longest straight piece = {4 * GRID:.1f} m <= §12's {MAX_STRAIGHT:.0f} m cap"),
        (8 * GRID <= MAX_STRAIGHT,
         f"largest footprint = {8 * GRID:.1f} m (hall) <= {MAX_STRAIGHT:.0f} m in every horizontal direction"),
        (8 * GRID >= 15.0,
         f"hall sight line = {8 * GRID:.1f} m, inside §12's 개방 공간 시야 15~25 m"),
        (CLEAR_W >= TWO_PERSON_CARRY_W,
         f"corridor clear width = {CLEAR_W:.2f} m >= {TWO_PERSON_CARRY_W:.2f} m for §08's two-person w5 궤짝"),
        (door_clear >= TWO_PERSON_CARRY_W,
         f"narrowest point in kit = {door_clear:.2f} m at the door pintles >= {TWO_PERSON_CARRY_W:.2f} m"),
        (CLEAR_W >= MONSTER_SHOULDER,
         f"corridor clear width = {CLEAR_W:.2f} m >= monster shoulders {MONSTER_SHOULDER:.2f} m"),
        (CLEAR_H > MONSTER_HEIGHT,
         f"corridor clear height = {CLEAR_H:.2f} m > monster height {MONSTER_HEIGHT:.2f} m"),
        (abs(reach - 14.6969) < 1e-3,
         f"gallery at +{GALLERY_RISE:.2f} m reaches §04's {OBSERVER_RANGE:.0f} m at "
         f"{reach:.2f} m horizontally — inside the {8 * GRID:.0f} m hall"),
        (bar_gap < MONSTER_SHOULDER,
         f"observation-window bar gap = {bar_gap:.3f} m < monster shoulders {MONSTER_SHOULDER:.2f} m"),
        (abs(STOREY / (2 * 9) - 0.2083333) < 1e-5,
         f"stair rise {STOREY:.2f} m / 18 treads = {STOREY / 18:.4f} m per riser"),
    ]


def main() -> None:
    out_dir = os.path.join(blendkit.MODELS_DIR, "MapKit")
    rows = []
    for spec in PIECES:
        report, slots = build_piece(spec)
        rows.append((spec, report, slots))

    print()
    print("=" * 118)
    print(f"MAP KIT — grid {GRID} m, origin = min-X/min-Y corner at floor top (z=0), "
          f"corridor {CLEAR_W:.2f} m x {CLEAR_H:.2f} m clear")
    print("=" * 118)
    head = (f"{'PIECE':<30}{'FOOTPRINT m':>14}{'CELLS':>8}{'HEIGHT m':>10}"
            f"{'STRAIGHT m':>12}{'TRIS':>7}{'VERTS':>7}{'BYTES':>9}  FLOOR SLOT")
    print(head)
    print("-" * 118)
    worst = 0.0
    total_tris = 0
    for spec, report, slots in rows:
        sx, sy, sz = report.size
        worst = max(worst, sx, sy)
        total_tris += report.triangles
        cells = ("prop" if spec.footprint is None
                 else f"{round(sx / GRID)}x{round(sy / GRID)}")
        print(f"{spec.name:<30}{sx:>7.2f} x{sy:>6.2f}{cells:>8}{sz:>10.2f}"
              f"{spec.max_straight:>12.2f}{report.triangles:>7}{report.vertices:>7}"
              f"{report.bytes:>9}  {spec.floor_slot}")
    print("-" * 118)
    print(f"{len(rows)} pieces, {total_tris} triangles total, "
          f"largest horizontal dimension {worst:.2f} m")
    print()

    print("§12 RULE CONFIRMATIONS")
    print("-" * 118)
    failures = []
    for ok, text in design_checks():
        print(f"  [{'PASS' if ok else 'FAIL'}] {text}")
        if not ok:
            failures.append(text)
    over = [s.name for s, r, _ in rows if max(r.size[0], r.size[1]) > MAX_STRAIGHT + 1e-4]
    print(f"  [{'PASS' if not over else 'FAIL'}] "
          f"no piece exceeds {MAX_STRAIGHT:.0f} m in any horizontal direction "
          f"(worst = {worst:.2f} m)")
    if over:
        failures.append("pieces over 20 m: " + ", ".join(over))
    print()

    print("MATERIAL SLOTS AS EXPORTED")
    print("-" * 118)
    seen = set()
    for spec, report, slots in rows:
        for s in slots:
            seen.add(s)
        print(f"  {spec.name:<30} {', '.join(slots)}")
    required = {"Floor_Wood", "Floor_Tile", "Floor_Gravel", "Floor_Concrete", "Floor_Metal"}
    missing = sorted(required - seen)
    print(f"  [{'PASS' if not missing else 'FAIL'}] all five contractual §12 floor "
          f"material names present" + (f" — MISSING {missing}" if missing else ""))
    if missing:
        failures.append(f"missing floor materials: {missing}")
    print()

    print("ASSEMBLY PROOF — §12's prototype layout (B 홀 + A 미로 + S자 통로) built from the kit")
    print("-" * 118)
    by_name = {spec.name: (spec, report) for spec, report, _ in rows}
    asm_results, asm_stats = check_assembly(by_name)
    for ok, text in asm_results:
        print(f"  [{'PASS' if ok else 'FAIL'}] {text}")
        if not ok:
            failures.append(text)
    print(f"  ... {asm_stats['pieces']} pieces, {asm_stats['connections']} connections, "
          f"{asm_stats['open_docks']} docks left open for further zones")
    print()

    manifest = {
        "grid_metres": GRID,
        "origin": "min-X / min-Y corner of the footprint, at the floor top surface (z = 0)",
        "storey_metres": STOREY,
        "corridor_clear": {"width": CLEAR_W, "height": CLEAR_H},
        "gallery_rise_metres": GALLERY_RISE,
        "design_sections": ["§03", "§04", "§05", "§06", "§08", "§12"],
        "prototype_assembly": asm_stats,
        "pieces": [
            {
                "name": spec.name,
                "file": spec.name + ".fbx",
                "kind": spec.kind,
                "grid_snapped": spec.footprint is not None,
                "footprint_metres": [round(report.size[0], 4), round(report.size[1], 4)],
                "footprint_cells": (None if spec.footprint is None else
                                    [round(report.size[0] / GRID), round(report.size[1] / GRID)]),
                "height_metres": round(report.size[2], 4),
                "max_straight_run_metres": spec.max_straight,
                "floor_slot": spec.floor_slot,
                "material_slots": slots,
                "triangles": report.triangles,
                "vertices": report.vertices,
                "docks": spec.docks,
                "note": spec.note,
            }
            for spec, report, slots in rows
        ],
    }
    manifest_path = os.path.join(out_dir, "MapKit.manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)
    print(f"MANIFEST {os.path.relpath(manifest_path, blendkit.REPO_ROOT)}")

    if failures:
        blendkit.fail("§12 verification failed: " + " | ".join(failures))
    print(f"MAPKIT_OK {len(rows)} pieces written to "
          f"{os.path.relpath(out_dir, blendkit.REPO_ROOT)}")


# ── Assembly proof ──────────────────────────────────────────────────────────
#
# §12 says "맵은 아트가 아니라 시스템이다", so shipping 21 files that each measure
# correctly is only half the job — the kit has to *assemble* into something §12
# would accept. This layout is assembled symbolically (no geometry) every run, and
# the checks below are the ones from §12's own 검증 체크리스트 that a piece kit can
# be held to: grid alignment, no overlap, docks that actually meet, and loops.
#
# It builds §12's prototype recommendation — "프로토타입은 B + A + S자 통로만 만들면
# 된다" — as a maze zone (미로 공간) of crosses and 5 m corridors, joined to the 20 m
# hall (개방 공간) through the S-corridor, exactly the adjacency §12 demands:
#
#     [개방 공간] ──진입── [미로 공간]
#        어그로 획득          어그로 해제

EDGE_NORMALS = {"-X": (-1, 0), "+X": (1, 0), "-Y": (0, -1), "+Y": (0, 1)}
OPPOSITE = {"-X": "+X", "+X": "-X", "-Y": "+Y", "+Y": "-Y"}

# (piece name, cell x, cell y, rotation in degrees, level in metres)
PROTOTYPE_LAYOUT = [
    # Maze zone: three loops of 4-ways and 5 m corridors.
    ("Junction_Cross_4Way", 0, 0, 0, 0.0), ("Junction_Cross_4Way", 3, 0, 0, 0.0),
    ("Junction_Cross_4Way", 0, 3, 0, 0.0), ("Junction_Cross_4Way", 3, 3, 0, 0.0),
    ("Junction_Cross_4Way", 6, 0, 0, 0.0), ("Junction_Cross_4Way", 6, 3, 0, 0.0),
    ("Junction_Cross_4Way", 0, 6, 0, 0.0), ("Junction_Cross_4Way", 3, 6, 0, 0.0),
    ("Corridor_Straight_5m", 1, 0, 90, 0.0), ("Corridor_Straight_5m", 4, 0, 90, 0.0),
    ("Corridor_Straight_5m", 1, 3, 90, 0.0), ("Corridor_Straight_5m", 4, 3, 90, 0.0),
    ("Corridor_Straight_5m", 1, 6, 90, 0.0),
    ("Corridor_Straight_5m", 0, 1, 0, 0.0), ("Corridor_Straight_5m", 3, 1, 0, 0.0),
    ("Corridor_Straight_5m", 0, 4, 0, 0.0), ("Corridor_Straight_5m", 3, 4, 0, 0.0),
    # §12: 순환로의 목에 문 하나 → 잠그면 순환이 끊김. This door is that neck.
    ("Doorway_Frame", 6, 1, 0, 0.0), ("Corridor_Straight_2m5", 6, 2, 0, 0.0),
    # §12: 막힌 길 20~25%, each with a reward.
    ("DeadEnd_Cap", 7, 0, 270, 0.0),
    # §12: 관측 지점 구역당 1~2개.
    ("ObservationPost_BarredWindow", 7, 3, 270, 0.0),
    # The base unit joins the maze to the open space.
    ("SCorridor_Unit_10m_x2", 3, 7, 0, 0.0),
    ("Hall_Open_20x20", 2, 14, 0, 0.0),
    ("Stairwell_Metal", 10, 15, 270, 0.0),
    # Mezzanine over the hall: overlaps it in plan on purpose, hence its own level.
    ("ObservationPost_Gallery", 2, 14, 0, GALLERY_RISE),
]


def rot_point(px: float, py: float, rot: int, fx: float, fy: float) -> tuple[float, float]:
    """Rotates a piece-local point, re-anchored so the min corner stays at (0, 0)."""
    if rot == 0:
        return (px, py)
    if rot == 90:
        return (fy - py, px)
    if rot == 180:
        return (fx - px, fy - py)
    if rot == 270:
        return (py, fx - px)
    raise ValueError(f"rotation must be a multiple of 90°, got {rot}")


def rot_edge(edge: str, rot: int) -> str:
    nx, ny = EDGE_NORMALS[edge]
    for _ in range((rot // 90) % 4):
        nx, ny = -ny, nx
    for name, vec in EDGE_NORMALS.items():
        if vec == (round(nx), round(ny)):
            return name
    raise ValueError(edge)


def check_assembly(by_name: dict) -> tuple[list[tuple[bool, str]], dict]:
    """Assembles PROTOTYPE_LAYOUT symbolically and applies §12's checklist."""
    placed = []
    for idx, (name, cx, cy, rot, level) in enumerate(PROTOTYPE_LAYOUT):
        spec, report = by_name[name]
        fx, fy = report.size[0], report.size[1]
        wx, wy = (fy, fx) if rot in (90, 270) else (fx, fy)
        ox, oy = cx * GRID, cy * GRID
        docks = []
        for d in spec.docks:
            lx, ly = rot_point(d["centre"][0], d["centre"][1], rot, fx, fy)
            docks.append({
                "edge": rot_edge(d["edge"], rot),
                "pt": (round(ox + lx, 4), round(oy + ly, 4)),
                "width": d["width"], "height": d["height"],
                "level": level + d["level"],
            })
        placed.append({"i": idx, "name": name, "cells": (cx, cy, cx + round(wx / GRID),
                                                         cy + round(wy / GRID)),
                       "extent": (ox, oy, ox + wx, oy + wy),
                       "level": level, "docks": docks, "kind": spec.kind})

    results: list[tuple[bool, str]] = []

    off_grid = [p["name"] for p in placed
                if abs(p["extent"][2] / GRID - round(p["extent"][2] / GRID)) > 1e-6
                or abs(p["extent"][3] / GRID - round(p["extent"][3] / GRID)) > 1e-6]
    results.append((not off_grid,
                    f"all {len(placed)} placements land on the {GRID} m grid"
                    + (f" — OFF GRID: {off_grid}" if off_grid else "")))

    clashes = []
    for a in range(len(placed)):
        for b in range(a + 1, len(placed)):
            pa, pb = placed[a], placed[b]
            if abs(pa["level"] - pb["level"]) > 1e-6:
                continue
            ax0, ay0, ax1, ay1 = pa["cells"]
            bx0, by0, bx1, by1 = pb["cells"]
            if ax0 < bx1 and bx0 < ax1 and ay0 < by1 and by0 < ay1:
                clashes.append(f"{pa['name']}@{pa['cells'][:2]} vs {pb['name']}@{pb['cells'][:2]}")
    results.append((not clashes,
                    f"no two same-level pieces overlap"
                    + (f" — CLASHES: {clashes}" if clashes else "")))

    parent = list(range(len(placed)))

    def find(i: int) -> int:
        while parent[i] != i:
            parent[i] = parent[parent[i]]
            i = parent[i]
        return i

    edges = 0
    mismatched = []
    open_docks = 0
    for a in range(len(placed)):
        for da in placed[a]["docks"]:
            partner = None
            for b in range(len(placed)):
                if b == a:
                    continue
                for db in placed[b]["docks"]:
                    if (da["pt"] == db["pt"] and abs(da["level"] - db["level"]) < 1e-6
                            and db["edge"] == OPPOSITE[da["edge"]]):
                        partner = (b, db)
            if partner is None:
                open_docks += 1
                continue
            b, db = partner
            if abs(da["width"] - db["width"]) > 1e-6:
                mismatched.append(f"{placed[a]['name']} {da['width']:.2f} m vs "
                                  f"{placed[b]['name']} {db['width']:.2f} m at {da['pt']}")
            if a < b:
                edges += 1
                ra, rb = find(a), find(b)
                if ra != rb:
                    parent[ra] = rb
    results.append((not mismatched,
                    f"{edges} dock connections, every one matched in clear width "
                    f"({CLEAR_W:.2f} m)" + (f" — MISMATCH: {mismatched}" if mismatched else "")))

    components = len({find(i) for i in range(len(placed))})
    loops = edges - len(placed) + components
    results.append((loops >= 3,
                    f"independent loops = E - V + C = {edges} - {len(placed)} + {components} "
                    f"= {loops} (§12 requires 3+ map-wide; 트리 구조는 사형선고)"))

    dead_ends = sum(1 for p in placed if p["kind"] == "deadend")
    results.append((dead_ends >= 1,
                    f"{dead_ends} dead end(s) placed, each carrying a reward (§12 막힌 길 보상)"))

    posts = sum(1 for p in placed if p["kind"] == "observation")
    results.append((posts >= 1,
                    f"{posts} observation post(s) — §12 구역당 1~2개, else 관측자는 죽으러 가야 한다"))

    has_open = any(p["kind"] == "open" for p in placed)
    open_adjacent = False
    for p in placed:
        if p["kind"] != "open":
            continue
        for d in p["docks"]:
            for q in placed:
                if q["kind"] == "corridor" and any(e["pt"] == d["pt"] for e in q["docks"]):
                    open_adjacent = True
    results.append((has_open and open_adjacent,
                    "개방 공간 present and adjacent to 미로 공간 (§12: 개방만 있으면 도망칠 곳이 없고, "
                    "미로만 있으면 멀리서 어그로를 걸 수 없다)"))

    max_x = max(p["extent"][2] for p in placed)
    max_y = max(p["extent"][3] for p in placed)
    results.append((max_x <= 100.0 and max_y <= 100.0,
                    f"assembly extent {max_x:.1f} x {max_y:.1f} m, inside §12's 100 x 100 m map"))

    stats = {"pieces": len(placed), "connections": edges, "loops": loops,
             "open_docks": open_docks, "extent": [max_x, max_y],
             "dead_ends": dead_ends, "observation_posts": posts}
    return results, stats


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:  # noqa: BLE001 — Blender exits 0 after a Python
        # exception, so a broken generator looks successful. Everything routes
        # through blendkit.fail() to make a failure a failure.
        traceback.print_exc()
        blendkit.fail(f"gen_mapkit.py: {type(exc).__name__}: {exc}")
