"""Procedural PBR texture generation for the horror game.

Every surface the game ships is generated by code in this file. Nothing is
photographed, downloaded, or licensed — the same reason the audio toolkit in
`tools/audio/synth.py` synthesises rather than samples: a Steam release has no
attribution to track and no texture that turns out to be someone else's.

WHY THIS EXISTS AT ALL
----------------------
The measured baseline was a black screen. The flashlight beam landed on a wall
and the wall stayed invisible, because every surface was a flat colour with an
albedo so low there was nothing for the beam to bounce off. §03 makes darkness
the lock on progress and the flashlight the key, so a beam that visibly does
nothing is not atmosphere — it is a broken mechanic.

The fix is stated once, here, and enforced by assertion below:

    **Darkness comes from LIGHTING, never from painting the albedo black.**

A real basement wall reflects 20–40% of the light that hits it. Painted black
it reflects 2%, and no amount of lamp intensity recovers the shape of the room.
So every albedo this file produces is calibrated to a mean in
[`ALBEDO_MIN_LINEAR`, `ALBEDO_MAX_LINEAR`] *linear* and the run fails if one
drifts out.

§12 IS A GAMEPLAY REQUIREMENT, NOT AN ART REQUEST
--------------------------------------------------
"구역별로 바닥 재질이 달라야 청음사가 위치를 판별할 수 있다 — 아트 결정이 아니라
시스템 결정이다." The five floors are a channel the Listener reads. The audio
side already makes them distinguishable by ear; this file has to make them
distinguishable by eye, under a narrow beam, at a glance. That is why each floor
gets a different *structure* (planks / grid / loose stones / stains / plate)
rather than a different tint — a tint dies the moment the beam is off-centre,
structure survives because the normal map keeps working at grazing angles.

CONVENTIONS, AND THE REASONS FOR THEM
-------------------------------------
* **Everything is periodic by construction.** A seam every 2 m reads as amateur
  work. No filter here is allowed to be non-periodic: blurs use `mode="wrap"`,
  frequency-domain work is inherently circular, structure counts divide the
  resolution exactly, and domain warps index with integer wraparound. The seam
  check at the end measures it rather than trusting it.
* **Height fields are in metres, and carry `world_size`.** The normal map is a
  real slope, `dh/dx`, not a fudge factor — which is why gravel actually reads
  as loose stone instead of as a bumpy photograph of stone.
* **Linear float internally, sRGB only at the PNG boundary.** Albedo is authored
  and calibrated in linear because that is the space the band is specified in;
  roughness / AO / normal are data and never get an sRGB curve.
* **Buffers are float32 in [0, 1] until written.**
"""

from __future__ import annotations

import argparse
import math
import os
import struct
import sys
import zlib
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Sequence, Tuple

import numpy as np
from scipy import ndimage

# ── Calibration constants ───────────────────────────────────────────────────

ALBEDO_MIN_LINEAR = 0.15
"""Floor of the albedo band, linear.

Below this a surface returns so little of the beam that the flashlight stops
reading as a light source. §03 needs the beam to visibly carve — a wall that
eats it is indistinguishable from a wall that is not there.
"""

ALBEDO_MAX_LINEAR = 0.45
"""Ceiling of the albedo band, linear.

Above this the room stops being dark even before the lighting rig is tuned, and
§05's "어둡다" turns into an evenly lit grey box. It is also roughly the top of
the range real building materials occupy: dry concrete sits near 0.35, white
plaster near 0.45, and nothing indoors goes higher without being a light source.
"""

ALBEDO_CLAMP_LINEAR = (0.012, 0.90)
"""Hard per-texel bounds, linear — charcoal to fresh snow.

Individual texels may sit outside the *mean* band (grout is darker than tile,
that is the point), but a texel outside these bounds is not a material any more,
it is a hole in the render.
"""

MAX_CALIBRATION_GAIN = 2.6
"""How far the mean calibration in `finish_albedo` may move a texture.

The gain exists to land an intentional target exactly, not to rescue bad
authoring. If a material needs more than this, its paint values are wrong and
the run should fail loudly rather than quietly ship a washed-out texture.
"""

SEAM_RATIO_LIMIT = 1.10
"""Wrap-edge difference over the *largest* interior difference.

See `seam_ratio` for the derivation. The materials here score 0.0–0.95 and a
genuine discontinuity scores 6–12, so this sits in the gap with a factor of five
of margin on the failing side.
"""

MIN_ROUGHNESS = 0.16
"""Floor on roughness for every surface in the set.

Not a physical limit — polished tile really does go below this — but a limit set
by the light rig. §03 puts a bright spot light within a metre or two of a wall
and there is no exposure control in front of it, so a surface at roughness 0.06
returns a specular lobe several hundred times over white and renders as a hole
punched in the frame. The first textured render showed exactly that: a blown
disc where the beam met smooth trim, with the material underneath unreadable.

Clamping roughness costs a little of the wet-tile look and buys back the whole
highlight. It sits here rather than in each builder so that the reason is stated
once and no surface can quietly opt out of it.
"""

NORMAL_UNIT_TOLERANCE = 0.02
"""Allowed deviation from unit length after 8-bit quantisation.

An 8-bit channel steps by 1/255 ≈ 0.0078 in [0,1] and twice that once remapped
to [-1,1], so a correctly generated normal cannot be exact. Anything beyond this
means the vector was never normalised, not that it was rounded.
"""

DEFAULT_RESOLUTION = 1024
"""Texels per side.

1024 over a 2 m tile is ~512 px/m, far beyond what a 12 m flashlight range
(`GameConstants.FlashlightRange`) resolves, and it keeps the whole set inside a
few seconds of generation and a sane import time.
"""


# ── PNG output ──────────────────────────────────────────────────────────────
#
# Written by hand rather than through Pillow so the toolkit runs in the same
# venv the audio generators use (numpy + scipy, nothing else). PNG's stored
# format is exactly what we need anyway: lossless, 8-bit, deflate.


def _png_chunk(tag: bytes, data: bytes) -> bytes:
    """One length-tag-payload-CRC PNG chunk."""
    return (
        struct.pack(">I", len(data))
        + tag
        + data
        + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)
    )


def write_png(path: str, image: np.ndarray) -> None:
    """Writes an 8-bit PNG from a uint8 array shaped (H, W), (H, W, 3) or (H, W, 4)."""
    if image.dtype != np.uint8:
        raise TypeError("write_png wants uint8; convert deliberately so rounding is visible")

    if image.ndim == 2:
        colour_type, channels = 0, 1
    elif image.ndim == 3 and image.shape[2] == 3:
        colour_type, channels = 2, 3
    elif image.ndim == 3 and image.shape[2] == 4:
        colour_type, channels = 6, 4
    else:
        raise ValueError("write_png supports grey, RGB and RGBA only, got shape %r" % (image.shape,))

    height, width = image.shape[0], image.shape[1]

    # Filter byte 0 (None) per scanline. The images here are noise-dominated, so
    # the adaptive filters buy little and cost a pass over every row.
    raw = np.zeros((height, width * channels + 1), dtype=np.uint8)
    raw[:, 1:] = image.reshape(height, width * channels)

    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "wb") as handle:
        handle.write(b"\x89PNG\r\n\x1a\n")
        handle.write(_png_chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, colour_type, 0, 0, 0)))
        handle.write(_png_chunk(b"IDAT", zlib.compress(raw.tobytes(), 9)))
        handle.write(_png_chunk(b"IEND", b""))


# ── Colour space ────────────────────────────────────────────────────────────


def linear_to_srgb(x: np.ndarray) -> np.ndarray:
    """Linear light to sRGB-encoded, the exact IEC 61966-2-1 curve.

    Albedo PNGs are read back through the inverse of this by the GPU, so using
    the real curve rather than a 1/2.2 approximation is what makes the asserted
    linear mean the mean the shader actually sees.
    """
    x = np.clip(x, 0.0, 1.0)
    return np.where(x <= 0.0031308, x * 12.92, 1.055 * np.power(x, 1.0 / 2.4) - 0.055)


def srgb_to_linear(x: np.ndarray) -> np.ndarray:
    """sRGB-encoded to linear light."""
    x = np.clip(x, 0.0, 1.0)
    return np.where(x <= 0.04045, x / 12.92, np.power((x + 0.055) / 1.055, 2.4))


def to_u8(x: np.ndarray) -> np.ndarray:
    """Rounds a [0,1] float array to uint8 without the truncation bias of a cast."""
    return np.clip(np.rint(np.asarray(x, dtype=np.float64) * 255.0), 0, 255).astype(np.uint8)


# ── Periodic noise ──────────────────────────────────────────────────────────
#
# Every generator below is periodic over the full texture. That is the property
# that makes tiling free rather than something to paper over afterwards.


def rng(seed: int) -> np.random.Generator:
    """Seeded generator. Every texture is reproducible from its seed alone."""
    return np.random.default_rng(seed)


def _radial_frequency(res: int) -> np.ndarray:
    """Radial frequency magnitude for an `res × res` FFT grid, in cycles/tile."""
    fy = np.fft.fftfreq(res)[:, None] * res
    fx = np.fft.fftfreq(res)[None, :] * res
    return np.sqrt(fy * fy + fx * fx)


def fbm(
    res: int,
    seed: int,
    beta: float = 1.9,
    low_cycles: float = 2.0,
    high_cycles: float | None = None,
) -> np.ndarray:
    """Fractal noise by spectral synthesis, normalised to [0, 1].

    Built in the frequency domain because a circular FFT is periodic *by
    definition* — there is no wrap-around error to correct, unlike a lattice
    noise that has to be told its period. `beta` is the power-law falloff:
    around 2 gives the self-similar mottling of concrete and plaster, lower
    values keep more fine grain.
    """
    freq = _radial_frequency(res)
    spectrum = np.fft.fft2(rng(seed).standard_normal((res, res)))

    amplitude = np.zeros_like(freq)
    np.divide(1.0, np.power(freq, beta), out=amplitude, where=freq > 0)
    amplitude[freq < low_cycles] = 0.0
    if high_cycles is not None:
        amplitude[freq > high_cycles] = 0.0

    field = np.real(np.fft.ifft2(spectrum * amplitude))
    return normalise01(field)


def normalise01(field: np.ndarray) -> np.ndarray:
    """Rescales to exactly [0, 1]. Flat input becomes 0.5 rather than NaN."""
    low, high = float(field.min()), float(field.max())
    if high - low < 1e-12:
        return np.full_like(field, 0.5, dtype=np.float32)
    return ((field - low) / (high - low)).astype(np.float32)


def blur(field: np.ndarray, sigma: float) -> np.ndarray:
    """Gaussian blur that wraps.

    `mode="wrap"` is the whole point: the default reflecting boundary would make
    every blurred feature stop dead at the texture edge, which is precisely the
    seam this file exists to avoid.
    """
    if sigma <= 0.0:
        return field
    return ndimage.gaussian_filter(field, sigma=sigma, mode="wrap").astype(np.float32)


def worley(
    res: int,
    cells: int,
    seed: int,
    jitter: float = 1.0,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Periodic cellular noise. Returns (F1, F2, cell id) with distances in tiles.

    One feature point per cell of a `cells × cells` grid, searched over the 3×3
    neighbourhood with wrapped cell indices, so the pattern is periodic and no
    point near an edge loses its neighbours. Used two different ways here:
    F1 plus the cell id builds gravel (a dome and a tone per stone), and F2 − F1
    builds crack networks, because that difference goes to zero exactly on the
    boundary between two cells — which is what a fracture is.
    """
    generator = rng(seed)
    points = (np.stack(np.meshgrid(np.arange(cells), np.arange(cells), indexing="ij"), axis=-1)
              + 0.5 + (generator.random((cells, cells, 2)) - 0.5) * jitter) / cells

    axis = (np.arange(res) + 0.5) / res
    py = axis[:, None]
    px = axis[None, :]

    cell_y = np.minimum((py * cells).astype(np.int32), cells - 1)
    cell_x = np.minimum((px * cells).astype(np.int32), cells - 1)

    best1 = np.full((res, res), 4.0, dtype=np.float32)
    best2 = np.full((res, res), 4.0, dtype=np.float32)
    owner = np.zeros((res, res), dtype=np.int32)

    for offset_y in (-1, 0, 1):
        for offset_x in (-1, 0, 1):
            ny = (cell_y + offset_y) % cells
            nx = (cell_x + offset_x) % cells
            feature = points[ny, nx]

            # Wrapped difference: the shorter way round the torus.
            dy = feature[..., 0] - py
            dx = feature[..., 1] - px
            dy -= np.rint(dy)
            dx -= np.rint(dx)
            distance = np.sqrt(dy * dy + dx * dx).astype(np.float32)

            closer = distance < best1
            best2 = np.where(closer, best1, np.minimum(best2, distance))
            owner = np.where(closer, ny * cells + nx, owner)
            best1 = np.where(closer, distance, best1)

    return best1, best2, owner


def per_cell(owner: np.ndarray, cells: int, seed: int, low: float = 0.0, high: float = 1.0) -> np.ndarray:
    """A random value per Worley cell, painted back over the pixels it owns.

    This is what turns a distance field into a pile of individual stones: each
    one gets its own tone, height and roughness instead of the whole surface
    sharing one.
    """
    table = rng(seed).uniform(low, high, size=cells * cells).astype(np.float32)
    return table[owner]


def stripes(res: int, count: int, axis: int, phase: np.ndarray | None = None) -> np.ndarray:
    """Sawtooth position within a stripe, in [0, 1). Periodic when `count` divides `res`.

    The building block for planks, tile rows, brick courses and form boards.
    `phase` offsets each stripe, which is how brick courses get their stagger.
    """
    coordinate = (np.arange(res, dtype=np.float32) + 0.5) / res
    grid = coordinate[:, None] if axis == 0 else coordinate[None, :]
    value = grid * count
    if phase is not None:
        value = value + phase
    return np.mod(value, 1.0).astype(np.float32)


def index_of(res: int, count: int, axis: int, phase: np.ndarray | None = None) -> np.ndarray:
    """Which stripe each texel falls in, wrapped to [0, count). Pairs with `stripes`."""
    coordinate = (np.arange(res, dtype=np.float32) + 0.5) / res
    grid = coordinate[:, None] if axis == 0 else coordinate[None, :]
    value = grid * count
    if phase is not None:
        value = value + phase
    return np.mod(np.floor(value), count).astype(np.int32)


def cell_random(index: np.ndarray, count: int, seed: int, low: float = 0.0, high: float = 1.0) -> np.ndarray:
    """A random value per stripe / brick / tile index."""
    table = rng(seed).uniform(low, high, size=count).astype(np.float32)
    return table[np.clip(index, 0, count - 1)]


def groove(position: np.ndarray, width: float, softness: float = 0.35) -> np.ndarray:
    """1 inside a gap of fractional `width` centred on a stripe boundary, 0 on the face.

    Drives every joint in the set — plank gaps, tile grout, brick mortar, plate
    seams — so they all get the same chamfer treatment and read as the same
    building.
    """
    distance = np.minimum(position, 1.0 - position)
    edge = width * 0.5
    return np.clip(1.0 - (distance - edge * (1.0 - softness)) / (edge * softness + 1e-6), 0.0, 1.0).astype(np.float32)


def smoothstep(low: float, high: float, x: np.ndarray) -> np.ndarray:
    """Hermite fade between two thresholds."""
    t = np.clip((x - low) / (high - low + 1e-9), 0.0, 1.0)
    return (t * t * (3.0 - 2.0 * t)).astype(np.float32)


def warp(field: np.ndarray, offset_y: np.ndarray, offset_x: np.ndarray) -> np.ndarray:
    """Domain-warps by integer texel offsets, wrapping at the edges.

    Integer offsets with `np.take(mode="wrap")` rather than a resampling warp:
    it costs nothing, and it cannot introduce the edge artefacts that a
    interpolating warp would need a periodic-aware sampler to avoid.
    """
    res = field.shape[0]
    grid_y, grid_x = np.meshgrid(np.arange(res), np.arange(res), indexing="ij")
    sample_y = np.mod(grid_y + np.rint(offset_y).astype(np.int32), res)
    sample_x = np.mod(grid_x + np.rint(offset_x).astype(np.int32), res)
    return field[sample_y, sample_x].astype(np.float32)


def warped_fbm(res: int, seed: int, beta: float, strength: float, low_cycles: float = 2.0) -> np.ndarray:
    """fBm pushed around by more fBm — breaks up the machine regularity of pure noise.

    Straight fBm reads as television static at close range. Warping it gives the
    directional streaking that stains, rust and water damage actually have.
    """
    base = fbm(res, seed, beta=beta, low_cycles=low_cycles)
    push_y = (fbm(res, seed + 991, beta=2.2, low_cycles=1.0) - 0.5) * strength
    push_x = (fbm(res, seed + 997, beta=2.2, low_cycles=1.0) - 0.5) * strength
    return normalise01(warp(base, push_y, push_x))


def stain(
    res: int,
    seed: int,
    threshold: float = 0.5,
    softness: float = 0.06,
    detail: float = 0.40,
    low_cycles: float = 1.5,
    beta: float = 2.4,
) -> np.ndarray:
    """A stain-shaped mask with a *ragged* edge, in [0, 1].

    This exists because the obvious construction is wrong in a way that is only
    obvious once rendered. Thresholding a smooth low-frequency field —
    `smoothstep(a, b, warped_fbm(...))` — produces enormous smooth-edged bubbles:
    the field varies slowly, so its contour lines are slow curves, and the result
    reads as clouds painted onto the wall rather than as damp.

    The fix is to perturb the field with mid- and high-frequency noise *before*
    thresholding. The contour then has to detour around every small wiggle, so
    the boundary is broken at every scale at once, which is exactly what a real
    water mark, rust bloom or paint failure looks like: a large-scale shape with
    a fractal edge.
    """
    large = warped_fbm(res, seed, beta=beta, strength=res * 0.05, low_cycles=low_cycles)
    mid = fbm(res, seed + 13, beta=1.8, low_cycles=6.0)
    fine = fbm(res, seed + 17, beta=1.4, low_cycles=20.0)

    field = large + (mid - 0.5) * detail + (fine - 0.5) * detail * 0.45
    return smoothstep(threshold - softness, threshold + softness, field)


def runs(source: np.ndarray, length: int, falloff: float = 1.6, axis: int = 0) -> np.ndarray:
    """Drags a mask along one axis with decay — water running down a surface.

    Gravity is the strongest tell that a stain is real: rust, seepage and grime
    all originate somewhere and travel *one* way. Radiating blobs read as paint.
    `np.roll` keeps it periodic, so a streak that leaves the bottom re-enters the
    top and the tiling survives.
    """
    out = np.zeros_like(source)
    for step in range(1, max(2, length)):
        out = np.maximum(out, np.roll(source, step, axis=axis) * (1.0 - step / length) ** falloff)
    return out.astype(np.float32)


def scratches(res: int, seed: int, count: int, length: float, width: float) -> np.ndarray:
    """Thin wrapped line marks — scuffs, drag marks, tool scars.

    Drawn by walking a point across the torus and stamping it, then blurring.
    Wrapping the walk with a modulo is what keeps them continuous across the
    seam instead of stopping at the edge like a scratch on a photograph.
    """
    generator = rng(seed)
    canvas = np.zeros((res, res), dtype=np.float32)
    steps = max(2, int(length * res))

    for _ in range(count):
        angle = generator.uniform(0.0, math.pi * 2.0)
        wobble = generator.uniform(-0.6, 0.6)
        y = generator.uniform(0.0, res)
        x = generator.uniform(0.0, res)
        strength = generator.uniform(0.35, 1.0)

        for step in range(steps):
            drift = angle + wobble * math.sin(step / max(1.0, steps * 0.25))
            y = (y + math.sin(drift)) % res
            x = (x + math.cos(drift)) % res
            canvas[int(y), int(x)] = max(canvas[int(y), int(x)], strength)

    return normalise01(blur(canvas, max(0.6, width * res * 0.5)))


# ── Height → normal, AO ─────────────────────────────────────────────────────


def height_to_normal(height: np.ndarray, world_size: float, height_scale: float) -> np.ndarray:
    """Tangent-space normal from the real slope of the height field.

    `height` is unitless [0,1]; `height_scale` is the metres between its 0 and
    its 1, and `world_size` is the metres the tile spans. So `dh/dx` below is a
    true gradient in metres per metre and the relief strength of every material
    is set by a number with a physical meaning, not by a taste slider. That is
    why gravel and tile can share this function and still read as different
    depths of surface.

    Differences are taken with `np.roll`, which is periodic — the normal map
    tiles because the height field does, with no special case at the border.
    OpenGL convention (green = +Y), which is what Unity samples.
    """
    res = height.shape[0]
    metres_per_texel = world_size / res

    dz_dy = (np.roll(height, -1, axis=0) - np.roll(height, 1, axis=0)) * height_scale / (2.0 * metres_per_texel)
    dz_dx = (np.roll(height, -1, axis=1) - np.roll(height, 1, axis=1)) * height_scale / (2.0 * metres_per_texel)

    normal = np.stack([-dz_dx, -dz_dy, np.ones_like(height)], axis=-1)
    normal /= np.linalg.norm(normal, axis=-1, keepdims=True)
    return normal.astype(np.float32)


def ambient_occlusion(height: np.ndarray, world_size: float, height_scale: float, strength: float = 1.0) -> np.ndarray:
    """Cavity-style AO: how far below its own neighbourhood a texel sits.

    Compared against several blur radii rather than one, so a deep narrow grout
    line and a wide shallow dish both darken. Cheap, and for surfaces lit almost
    entirely by a moving flashlight it is indistinguishable from a ray-traced
    bake — the occlusion that matters here is contact shadowing in the joints.
    """
    relief = np.zeros_like(height)
    res = height.shape[0]
    scales = 0

    for radius_metres in (0.008, 0.02, 0.05, 0.12):
        sigma = radius_metres / world_size * res
        if sigma < 0.7:
            continue

        # Depth below the local mean, in metres, over the radius it was measured
        # at — a dimensionless "how enclosed is this texel". Dividing by the
        # radius is the part that has to be right: the first version divided by
        # its square root and multiplied by `height_scale` separately, which left
        # the whole term four orders of magnitude too small. Every AO map came out
        # at a mean of 0.99, imported fine, and did nothing at all.
        drop = np.clip(blur(height, sigma) - height, 0.0, None) * height_scale
        relief += drop / radius_metres
        scales += 1

    if scales == 0:
        return np.ones_like(height)

    return np.clip(1.0 - (relief / scales) * strength * 3.2, 0.0, 1.0).astype(np.float32)


# ── Material description ────────────────────────────────────────────────────


@dataclass
class MapSet:
    """The four maps a material is made of, plus what they mean physically."""

    albedo: np.ndarray
    """Linear RGB, shaped (res, res, 3). Calibrated by `finish_albedo`."""

    roughness: np.ndarray
    """GGX roughness in [0,1]. Unity is handed 1 − this as smoothness."""

    height: np.ndarray
    """Unitless [0,1]; multiply by `height_scale` for metres."""

    metallic: np.ndarray
    """0 for dielectrics. Only the steel surfaces put anything here."""

    world_size: float
    """Metres one tile spans. Sets the material's UV tiling in Unity."""

    height_scale: float
    """Metres between height 0 and height 1. Sets normal-map strength."""


@dataclass(frozen=True)
class MaterialSpec:
    """One shippable surface: how to build it, and where it plugs into the kit."""

    name: str
    build: Callable[[int, int], MapSet]
    seed: int
    target_albedo: float
    """Intended mean linear albedo. An art decision, and it must sit in the band."""

    note: str
    """Why this surface looks the way it does. Ends up in the generated manifest."""

    slots: Tuple[str, ...] = ()
    """MapKit material slot names this binds to. Empty = generated but unbound."""

    tiling_axes: Tuple[int, ...] = (0, 1)
    """Which axes must tile. 0 is V (down the texture), 1 is U (across).

    Almost everything tiles both ways. Trim is the exception: a skirting board is
    a *cross-section* — a profile that repeats along its length and does not
    repeat across its height. Demanding it tile vertically would mean forcing the
    top edge of the board to match the floor-scuffed bottom edge, which is not a
    seam fix, it is a wrong board. Declaring the axis is the honest move; silently
    loosening the threshold for everything would have hidden real seams elsewhere.
    """


def finish_albedo(colour: np.ndarray, target_mean: float) -> Tuple[np.ndarray, float]:
    """Lands a linear albedo on its intended mean and clamps it to real materials.

    The gain is a deliberate, reported calibration step, not a rescue: it is
    bounded by `MAX_CALIBRATION_GAIN`, so a surface painted far from its target
    fails the run instead of being silently normalised into looking fine. Scaling
    happens in linear space, which preserves the ratios between grout and tile,
    rust and plate — the contrast survives, only the overall level moves.
    """
    if not ALBEDO_MIN_LINEAR <= target_mean <= ALBEDO_MAX_LINEAR:
        raise AssertionError(
            "target mean %.3f is outside the [%.2f, %.2f] band; §03 needs the beam to "
            "land on something that reflects it" % (target_mean, ALBEDO_MIN_LINEAR, ALBEDO_MAX_LINEAR)
        )

    colour = np.clip(colour, 1e-4, None)
    gain = target_mean / float(colour.mean())
    if not (1.0 / MAX_CALIBRATION_GAIN) <= gain <= MAX_CALIBRATION_GAIN:
        raise AssertionError(
            "albedo needs a %.2fx correction to reach %.3f — the painted values are wrong, "
            "fix them rather than widening the gain" % (gain, target_mean)
        )

    return np.clip(colour * gain, *ALBEDO_CLAMP_LINEAR).astype(np.float32), gain


def _as_rgb(colour: Sequence[float] | np.ndarray) -> np.ndarray:
    """Accepts either a single linear RGB triple or a full per-texel colour field."""
    array = np.asarray(colour, dtype=np.float32)
    return array if array.ndim == 3 else array.reshape(1, 1, 3)


def tint(base: Sequence[float] | np.ndarray, variation: np.ndarray,
         toward: Sequence[float] | np.ndarray, amount: np.ndarray) -> np.ndarray:
    """Blends a base colour toward another, per texel, in linear space.

    Takes a flat triple or an already-built colour field on either side so the
    material builders can chain it — brick, then paint over the brick, then damp
    over the paint — which is the order the real surface acquired them in.
    """
    mix = np.clip(amount, 0.0, 1.0)[..., None]
    return (_as_rgb(base) * variation[..., None] * (1.0 - mix) + _as_rgb(toward) * mix).astype(np.float32)


# ── §12 floors ──────────────────────────────────────────────────────────────
#
# Five surfaces that have to be told apart at a glance under a 44° beam
# (`GameConstants.FlashlightHalfAngle` × 2). Each one is given a different
# *structure*, because structure is what survives when the beam is off-axis.


def build_wood(res: int, seed: int) -> MapSet:
    """§12 구역 A — 나무. Boards, grain, gaps, and wear where feet go.

    The recognisable feature at a glance is the long parallel gap lines: they
    stay legible at grazing angles where a wood *colour* would just read as
    "brown floor". Boards are broken into staggered lengths so a beam sweeping
    along the corridor crosses butt joints, which is the cue that says "planks"
    faster than grain does.
    """
    world = 2.0
    planks = 10
    segments = 4

    plank_index = index_of(res, planks, axis=1)
    plank_position = stripes(res, planks, axis=1)

    # Each board is cut into lengths at a different offset, so butt joints never
    # line up across the floor — the give-away of a tiling texture.
    stagger = cell_random(plank_index, planks, seed + 1, 0.0, 1.0)
    board_position = stripes(res, segments, axis=0, phase=stagger)
    board_index = plank_index * segments + index_of(res, segments, axis=0, phase=stagger)

    gap = np.maximum(groove(plank_position, 0.055), groove(board_position, 0.030) * 0.75)

    # Grain: noise stretched hard along the board, plus a slow ring structure.
    grain = fbm(res, seed + 2, beta=1.35, low_cycles=3.0)
    grain = blur(grain, res * 0.010)
    grain_stretch = warp(grain, np.zeros((res, res)), (fbm(res, seed + 3, beta=2.4) - 0.5) * res * 0.02)
    rings = normalise01(np.abs(np.sin(grain_stretch * math.pi * 9.0 + cell_random(board_index, planks * segments, seed + 4, 0.0, 6.0))))

    board_tone = cell_random(board_index, planks * segments, seed + 5, 0.72, 1.28)

    # A soft traffic lane, deliberately low contrast and broken up by noise: a
    # hard stripe would tile into a painted line down the middle of the corridor.
    lane = np.exp(-((stripes(res, 1, axis=0) - 0.5) ** 2) / 0.055)
    lane = np.clip(lane * (0.55 + 0.45 * fbm(res, seed + 6, beta=2.0, low_cycles=1.0)), 0.0, 1.0)

    scuff = scratches(res, seed + 7, count=40, length=0.35, width=0.0015)
    dirt = warped_fbm(res, seed + 8, beta=2.1, strength=res * 0.03)

    height = np.clip(
        0.80
        + board_tone * 0.06
        + rings * 0.05
        + grain_stretch * 0.06
        - gap * 0.85
        - lane * 0.03,
        0.0, 1.0,
    )

    shade = board_tone * (0.80 + 0.20 * rings) * (0.85 + 0.30 * grain_stretch)
    shade *= 1.0 - 0.28 * dirt
    shade *= 1.0 - 0.35 * gap

    colour = tint((0.300, 0.170, 0.086), shade, (0.055, 0.036, 0.026), gap * 0.85)
    # Worn wood goes grey and pale, not darker — it is the finish that is missing,
    # not the timber. Darkening the lane would have been the intuitive move and
    # the wrong one: it reads as a stain rather than as traffic.
    colour = tint(colour, np.ones((res, res), np.float32), (0.250, 0.200, 0.148), lane * 0.30)
    colour *= 1.0 - 0.20 * scuff[..., None]

    roughness = np.clip(
        0.82 - 0.16 * lane - 0.05 * board_tone + 0.10 * grain_stretch + 0.12 * gap + 0.08 * scuff,
        0.05, 1.0,
    )

    return MapSet(colour, roughness, height, np.zeros((res, res), np.float32), world, 0.010)


def build_tile(res: int, seed: int) -> MapSet:
    """§12 구역 B — 타일. Grid, grout, chips, and the gloss that catches the beam.

    This is the surface that most needs to *shine*: §12 gives zone B the open
    hall and the observation post, and a glossy floor there gives the flashlight
    a specular streak that reads as distance. The grid is the strongest
    at-a-glance cue in the set, so the grout is cut deep and kept dark.
    """
    world = 2.0
    count = 8

    position_y = stripes(res, count, axis=0)
    position_x = stripes(res, count, axis=1)
    tile_index = index_of(res, count, axis=0) * count + index_of(res, count, axis=1)

    grout = np.maximum(groove(position_y, 0.055, softness=0.5), groove(position_x, 0.055, softness=0.5))

    # Chips: the corners take the damage, so the chip mask is biased to them.
    corner = np.minimum(np.minimum(position_y, 1.0 - position_y), np.minimum(position_x, 1.0 - position_x))
    chip_noise = fbm(res, seed + 1, beta=1.4, low_cycles=14.0)
    chips = smoothstep(0.62, 0.80, chip_noise) * smoothstep(0.22, 0.02, corner)

    # Wide tone spread per tile: a tiled floor laid over decades is never one
    # batch, and it is the mismatch between neighbouring tiles that makes the
    # grid legible from across a room rather than only underfoot.
    tile_tone = cell_random(tile_index, count * count, seed + 2, 0.74, 1.26)
    mottle = blur(fbm(res, seed + 3, beta=2.3, low_cycles=3.0), res * 0.004)

    f1_craze, f2_craze, _ = worley(res, 26, seed + 4, jitter=0.9)
    crazing = 1.0 - smoothstep(0.0, 0.012, f2_craze - f1_craze)

    grime = np.clip(
        stain(res, seed + 5, threshold=0.52, softness=0.10, detail=0.5, low_cycles=2.0) * 0.7
        + stain(res, seed + 9, threshold=0.72, softness=0.04, detail=0.6, low_cycles=5.0) * 0.5,
        0.0, 1.0)

    # Grime collects in the grout — the single detail that stops a tiled floor
    # looking like a bathroom showroom.
    grout_grime = grout * (0.45 + 0.55 * grime)

    height = np.clip(
        0.88
        + tile_tone * 0.02
        - grout * 0.80
        - chips * 0.45
        - crazing * 0.03,
        0.0, 1.0,
    )

    shade = tile_tone * (0.90 + 0.20 * mottle)
    shade *= 1.0 - 0.22 * grime
    colour = tint((0.360, 0.352, 0.330), shade, (0.105, 0.100, 0.090), np.clip(grout * 0.9 + grout_grime * 0.4, 0, 1))
    colour = tint(colour, np.ones((res, res), np.float32), (0.185, 0.172, 0.155), chips * 0.85)
    colour *= 1.0 - 0.10 * crazing[..., None]

    roughness = np.clip(
        0.22 + 0.60 * grout + 0.45 * chips + 0.14 * grime - 0.06 * tile_tone,
        0.06, 1.0,
    )

    return MapSet(colour, roughness, height, np.zeros((res, res), np.float32), world, 0.008)


def build_gravel(res: int, seed: int) -> MapSet:
    """§12 구역 C — 자갈. Loose stones, and the deepest relief in the set.

    Gravel is the one floor with no flat plane at all, so it is unmistakable the
    instant a beam crosses it — every stone throws its own shadow. Three sizes of
    stone are layered because a single Worley scale reads as a golf ball; real
    gravel has fines packed between the big pieces.
    """
    world = 1.5

    # Layers combine with `maximum`, not by adding. Gravel is packed stone: the
    # surface at any point is the top of whichever stone is there, so the height
    # is a max over the layers. Summing them — the obvious thing, and what this
    # did first — makes regions where several domes overlap pile up into broad
    # mounds, and the render came back looking like rippled sand dunes with the
    # individual stones washed out.
    height = np.zeros((res, res), dtype=np.float32)
    shade = np.full((res, res), 0.9, dtype=np.float32)

    for level, (cells, lift) in enumerate(((16, 0.00), (27, 0.10), (45, 0.18))):
        distance, _, owner = worley(res, cells, seed + level * 37, jitter=1.0)

        # A dome per stone: high at the centre, falling to the gap between stones.
        radius = 0.66 / cells
        dome = np.sqrt(np.clip(1.0 - (distance / radius) ** 1.7, 0.0, 1.0))
        dome = dome * per_cell(owner, cells, seed + level * 37 + 11, 0.60, 1.0)

        # Smaller stones sit slightly proud, filling between the larger ones.
        candidate = dome * (1.0 - lift) + lift * (dome > 0.02)
        winner = candidate > height
        shade = np.where(winner, per_cell(owner, cells, seed + level * 37 + 13, 0.45, 1.45), shade)
        height = np.maximum(height, candidate)

    height = normalise01(height + fbm(res, seed + 5, beta=1.4, low_cycles=26.0) * 0.06)

    grit = fbm(res, seed + 6, beta=1.2, low_cycles=30.0)
    dust = blur(fbm(res, seed + 7, beta=2.4, low_cycles=2.0), res * 0.01)

    # Depth between stones is the read. Darken the gaps hard, but never to black:
    # the beam still has to find something down there.
    pit = smoothstep(0.42, 0.0, height)

    surface = shade * (0.85 + 0.30 * grit) * (0.88 + 0.24 * dust)
    colour = tint((0.300, 0.282, 0.252), surface, (0.070, 0.066, 0.060), pit * 0.80)

    # A minority of stones are a different rock. Cheap, and it stops the pile
    # reading as one extruded material.
    _, _, owner_big = worley(res, 16, seed, jitter=1.0)
    reddish = smoothstep(0.78, 0.92, per_cell(owner_big, 16, seed + 21, 0.0, 1.0))
    colour = tint(colour, np.ones((res, res), np.float32), (0.235, 0.150, 0.108), reddish * 0.55)

    roughness = np.clip(0.86 - 0.10 * shade + 0.10 * grit - 0.06 * dust, 0.35, 1.0)

    return MapSet(colour, roughness, height, np.zeros((res, res), np.float32), world, 0.045)


def build_concrete_floor(res: int, seed: int) -> MapSet:
    """§12 구역 D — 콘크리트. Dull, stained, cracked, hairline fractures.

    Zone D holds the exit, so this is the surface players see most under stress.
    It has the least structure of the five on purpose — the contrast against
    gravel and tile is what makes those two legible. Its identity comes from
    stains and a crack network instead.
    """
    world = 2.5

    base = warped_fbm(res, seed + 1, beta=2.1, strength=res * 0.05)
    fine = fbm(res, seed + 2, beta=1.5, low_cycles=18.0)

    # Cracks: the boundary between Worley cells is where a slab actually fails.
    # The raw boundaries are dead straight, though, and a floor of clean polygons
    # reads as dried mud, not concrete — so the distance field is domain-warped
    # before thresholding, which bends each crack into an irregular path. Masked
    # hard as well, because "hairline fracture" means occasional, not a network.
    crack = np.zeros((res, res), dtype=np.float32)
    for cells, width, seed_offset in ((6, 0.0032, 31), (11, 0.0020, 47)):
        f1, f2, _ = worley(res, cells, seed + seed_offset, jitter=0.95)
        wander_y = (fbm(res, seed + seed_offset + 71, beta=2.0, low_cycles=4.0) - 0.5) * res * 0.045
        wander_x = (fbm(res, seed + seed_offset + 73, beta=2.0, low_cycles=4.0) - 0.5) * res * 0.045
        vein = 1.0 - smoothstep(0.0, width, warp(f2 - f1, wander_y, wander_x))

        # Branch decay: a crack fades along its length instead of running the
        # full width of the slab at constant strength.
        mask = smoothstep(0.34, 0.66, fbm(res, seed + seed_offset + 5, beta=2.4, low_cycles=2.5))
        crack = np.maximum(crack, vein * mask)
    crack = blur(crack, 0.6)

    # Aggregate showing through where the surface has worn.
    aggregate_distance, _, aggregate_owner = worley(res, 46, seed + 9, jitter=1.0)
    exposed = smoothstep(0.55, 0.80, base) * smoothstep(0.020, 0.006, aggregate_distance)
    pits = smoothstep(0.80, 0.94, fbm(res, seed + 10, beta=1.3, low_cycles=26.0))

    # Kept deliberately weak. Zone D holds the exit, so this floor is read under
    # stress and its job is to be the *plain* one — heavy staining here would
    # compete with the crack network that gives it its identity.
    damp = np.clip(
        stain(res, seed + 11, threshold=0.66, softness=0.09, detail=0.5, low_cycles=2.0) * 0.6
        + stain(res, seed + 14, threshold=0.76, softness=0.03, detail=0.6, low_cycles=4.5) * 0.45,
        0.0, 1.0)
    efflorescence = stain(res, seed + 12, threshold=0.70, softness=0.05, detail=0.55, low_cycles=3.5)

    height = np.clip(
        0.86
        + base * 0.06
        + fine * 0.03
        + exposed * 0.04
        - crack * 0.70
        - pits * 0.35,
        0.0, 1.0,
    )

    shade = (0.86 + 0.28 * base) * (0.92 + 0.16 * fine)
    shade *= 1.0 - 0.30 * damp
    colour = tint((0.318, 0.312, 0.300), shade, (0.075, 0.072, 0.070), np.clip(crack * 0.9 + pits * 0.6, 0, 1))
    colour = tint(colour, np.ones((res, res), np.float32), (0.400, 0.392, 0.365), efflorescence * 0.35)
    colour = tint(colour, np.ones((res, res), np.float32), (0.250, 0.235, 0.205),
                  per_cell(aggregate_owner, 46, seed + 13, 0.0, 1.0) * exposed * 0.6)

    roughness = np.clip(0.74 + 0.16 * fine - 0.10 * damp + 0.14 * crack + 0.10 * pits, 0.30, 1.0)

    return MapSet(colour, roughness, height, np.zeros((res, res), np.float32), world, 0.012)


def build_metal_floor(res: int, seed: int) -> MapSet:
    """§12 계단 — 금속. Plate, rivets, rust streaks, the brightest specular of the five.

    The stair is where §04's Listener hears 울림, and it should be the surface
    that most obviously *reflects*: a low-roughness plate throws a hard specular
    lozenge back at a flashlight, which no other floor here does. Rust is the
    counterweight — it breaks the plate into panels and keeps the albedo from
    reading as one flat sheet.

    Metallic is left partial rather than 1.0 deliberately. The scene's ambient is
    near black by design (§03), and a fully metallic surface with nothing to
    reflect renders as a black hole with a highlight in it. Partial metallic
    keeps a diffuse term so the plate is still *visible* off-beam.
    """
    world = 2.0
    plates = 2

    plate_y = stripes(res, plates, axis=0)
    plate_x = stripes(res, plates, axis=1)
    plate_index = index_of(res, plates, axis=0) * plates + index_of(res, plates, axis=1)
    seam = np.maximum(groove(plate_y, 0.020, softness=0.55), groove(plate_x, 0.020, softness=0.55))

    # Rivets march along the seams — the detail that says "fabricated" instantly.
    rivet_pitch = 16
    along_y = stripes(res, rivet_pitch, axis=1)
    along_x = stripes(res, rivet_pitch, axis=0)
    near_seam_y = groove(plate_y, 0.075, softness=0.9)
    near_seam_x = groove(plate_x, 0.075, softness=0.9)
    rivet = np.maximum(
        smoothstep(0.34, 0.16, np.abs(along_y - 0.5)) * near_seam_y,
        smoothstep(0.34, 0.16, np.abs(along_x - 0.5)) * near_seam_x,
    )
    rivet = smoothstep(0.55, 0.95, rivet)

    # Tread pattern: a raised diamond grid, the reason a steel floor is walkable.
    tread_count = 26
    diamond = np.abs(stripes(res, tread_count, axis=0) - 0.5) + np.abs(stripes(res, tread_count, axis=1) - 0.5)
    tread = smoothstep(0.42, 0.24, diamond) * (1.0 - seam)

    brushed = fbm(res, seed + 1, beta=1.1, low_cycles=40.0)
    brushed = blur(brushed, 0.4) * 0.5 + 0.5 * warp(brushed, np.zeros((res, res)), np.zeros((res, res)))

    # Rust starts where water sits — the seams and the rivet heads — and runs
    # downhill from there. Sourcing it from the geometry rather than from free
    # noise is what makes it read as corrosion instead of as camouflage paint:
    # every streak has a visible origin the eye can trace back to.
    # Higher `low_cycles` than the walls on purpose: a handful of large rust
    # blooms per tile makes the repeat obvious the moment two tiles are visible
    # at once. Many small ones read as corrosion and hide the period.
    streak_source = np.clip(seam * 0.75 + rivet, 0.0, 1.0) * \
        stain(res, seed + 2, threshold=0.50, softness=0.10, detail=0.6, low_cycles=6.0)
    streak = runs(streak_source, length=int(res * 0.18), falloff=1.5)

    bloom = stain(res, seed + 3, threshold=0.62, softness=0.05, detail=0.6, low_cycles=7.0)
    rust = np.clip(bloom * 0.75 + streak * 0.95, 0.0, 1.0)

    # Corrosion is granular at close range; without this it is a smooth wash.
    rust = np.clip(rust * (0.55 + 0.45 * fbm(res, seed + 4, beta=1.5, low_cycles=18.0)) * 1.25, 0.0, 1.0)

    plate_tone = cell_random(plate_index, plates * plates, seed + 5, 0.92, 1.08)
    scuff = scratches(res, seed + 6, count=55, length=0.30, width=0.0012)

    height = np.clip(
        0.72
        + tread * 0.16
        + rivet * 0.22
        - seam * 0.60
        + brushed * 0.02
        + rust * 0.05,
        0.0, 1.0,
    )

    shade = plate_tone * (0.88 + 0.24 * brushed) * (1.0 - 0.18 * scuff)
    colour = tint((0.345, 0.352, 0.368), shade, (0.090, 0.088, 0.092), seam * 0.85)

    # Two rust tones, dark iron oxide under a lighter powdery bloom, rather than
    # one flat brown — a single tint over grey plate blends to salmon.
    colour = tint(colour, np.ones((res, res), np.float32), (0.145, 0.062, 0.028), rust * 0.92)
    colour = tint(colour, np.ones((res, res), np.float32), (0.255, 0.125, 0.055),
                  np.clip(rust - 0.35, 0.0, 1.0) * 0.75)

    # The tread and the rivet heads take the polish, so they are the brightest
    # thing on the plate — that is what the beam catches first.
    colour *= (1.0 + 0.22 * tread * (1.0 - rust))[..., None]
    colour *= (1.0 + 0.30 * rivet * (1.0 - rust))[..., None]

    roughness = np.clip(0.26 + 0.52 * rust + 0.30 * seam + 0.16 * scuff - 0.10 * tread - 0.08 * rivet, 0.08, 1.0)
    metallic = np.clip(0.50 * (1.0 - rust) * (1.0 - seam * 0.8), 0.0, 1.0)

    return MapSet(colour, roughness, height, metallic, world, 0.012)


# ── Walls ───────────────────────────────────────────────────────────────────


def build_wall_brick(res: int, seed: int) -> MapSet:
    """Painted brick. The default basement wall.

    Brick is chosen as the bound wall because its courses are horizontal lines at
    a fixed spacing: when a flashlight sweeps across it, the mortar lines give a
    continuous readout of distance and angle. A flat wall gives none, which is
    exactly why the baseline read as a void. The paint is old and failing, so
    patches of bare brick and plaster show through — that variation is what stops
    a 2 m tile from announcing itself.
    """
    world = 1.8
    courses = 24
    per_course = 8

    course_index = index_of(res, courses, axis=0)
    # Alternate courses shift half a brick — the stretcher bond every wall uses.
    stagger = (course_index % 2).astype(np.float32) * 0.5
    course_position = stripes(res, courses, axis=0)
    brick_position = stripes(res, per_course, axis=1, phase=stagger)
    brick_index = course_index * per_course + index_of(res, per_course, axis=1, phase=stagger)

    mortar = np.maximum(groove(course_position, 0.13, softness=0.55), groove(brick_position, 0.10, softness=0.55))

    brick_tone = cell_random(brick_index, courses * per_course, seed + 1, 0.78, 1.22)
    brick_lean = cell_random(brick_index, courses * per_course, seed + 2, -1.0, 1.0)
    face = fbm(res, seed + 3, beta=1.6, low_cycles=12.0)
    pocks = smoothstep(0.72, 0.92, fbm(res, seed + 4, beta=1.2, low_cycles=30.0))

    # Paint fails around damp and along the mortar, which holds water. Modulating
    # the mask by the brick structure itself is what keeps it from floating over
    # the wall as an unrelated shape — real paint failure follows the substrate.
    paint = stain(res, seed + 5, threshold=0.42, softness=0.09, detail=0.50, low_cycles=1.8)
    peel = stain(res, seed + 6, threshold=0.58, softness=0.04, detail=0.60, low_cycles=6.0)
    paint = np.clip(paint * (0.72 + 0.28 * (1.0 - mortar)) - peel * 0.75 - pocks * 0.4, 0.0, 1.0)

    damp = np.clip(
        stain(res, seed + 7, threshold=0.60, softness=0.08, detail=0.45, low_cycles=1.2) * 0.75
        + runs(stain(res, seed + 8, threshold=0.76, softness=0.03, detail=0.5, low_cycles=2.5),
               length=int(res * 0.14)) * 0.5,
        0.0, 1.0)

    height = np.clip(
        0.80
        + brick_tone * 0.05
        + face * 0.04
        - mortar * 0.75
        - pocks * 0.30
        + paint * 0.03,
        0.0, 1.0,
    )

    shade = brick_tone * (0.86 + 0.28 * face)
    brick_colour = tint((0.270, 0.150, 0.115), shade, (0.330, 0.205, 0.150), np.clip(brick_lean * 0.5 + 0.5, 0, 1) * 0.5)
    mortar_colour = np.asarray([0.300, 0.292, 0.272], dtype=np.float32)

    colour = brick_colour * (1.0 - mortar[..., None] * 0.85) + mortar_colour[None, None, :] * mortar[..., None] * 0.85
    colour = tint(colour, np.ones((res, res), np.float32), (0.330, 0.325, 0.290), paint * 0.80)
    colour *= 1.0 - 0.32 * damp[..., None]
    colour *= 1.0 - 0.25 * pocks[..., None]

    roughness = np.clip(0.86 - 0.30 * paint + 0.10 * face + 0.06 * mortar - 0.12 * damp, 0.18, 1.0)

    return MapSet(colour, roughness, height, np.zeros((res, res), np.float32), world, 0.014)


def build_wall_concrete(res: int, seed: int) -> MapSet:
    """Bare poured concrete wall — board-formed, tie holes, streaked.

    The utilitarian counterpart to brick. Its identity is the horizontal board
    lines from the formwork and the regular grid of snap-tie holes, both of which
    are strong horizontal cues under a beam.
    """
    world = 2.5
    boards = 10

    board_position = stripes(res, boards, axis=0)
    board_index = index_of(res, boards, axis=0)
    board_seam = groove(board_position, 0.045, softness=0.6)
    board_tone = cell_random(board_index, boards, seed + 1, 0.90, 1.10)

    # Snap-tie holes: a regular grid, plugged and slightly proud of the wall.
    tie_y = stripes(res, 4, axis=0)
    tie_x = stripes(res, 5, axis=1)
    tie = smoothstep(0.055, 0.020,
                     np.sqrt((tie_y - 0.5) ** 2 + (tie_x - 0.5) ** 2).astype(np.float32))

    base = warped_fbm(res, seed + 2, beta=2.2, strength=res * 0.04)
    fine = fbm(res, seed + 3, beta=1.5, low_cycles=20.0)

    # Rust bleed from the ties and lime leaching from the board joints both run
    # downward, so the streaking is sourced from those features and dragged.
    bleed = np.clip(
        runs(np.clip(tie * 0.9 + board_seam * 0.35, 0.0, 1.0) *
             stain(res, seed + 4, threshold=0.44, softness=0.10, detail=0.6, low_cycles=2.0),
             length=int(res * 0.20), falloff=1.4) * 0.9
        + stain(res, seed + 6, threshold=0.66, softness=0.06, detail=0.5, low_cycles=1.5) * 0.45,
        0.0, 1.0)
    pits = smoothstep(0.82, 0.95, fbm(res, seed + 5, beta=1.3, low_cycles=28.0))

    height = np.clip(0.86 + base * 0.06 + fine * 0.03 - board_seam * 0.55 - tie * 0.40 - pits * 0.30, 0.0, 1.0)

    shade = board_tone * (0.88 + 0.24 * base) * (0.94 + 0.12 * fine)
    shade *= 1.0 - 0.26 * bleed
    colour = tint((0.335, 0.330, 0.318), shade, (0.100, 0.098, 0.095), np.clip(board_seam * 0.7 + pits * 0.6, 0, 1))
    colour = tint(colour, np.ones((res, res), np.float32), (0.215, 0.200, 0.175), tie * 0.55)

    roughness = np.clip(0.78 + 0.12 * fine - 0.14 * bleed + 0.10 * pits, 0.30, 1.0)

    return MapSet(colour, roughness, height, np.zeros((res, res), np.float32), world, 0.010)


def build_wall_plaster(res: int, seed: int) -> MapSet:
    """Water-stained plaster — the brightest wall in the set.

    Kept pale on purpose: §03's flashlight needs at least one surface class that
    throws light back generously, or every room reads at the same brightness.
    Plaster is that surface. The staining is what keeps it from looking clean —
    tide marks where water ran and dried, and blown patches where it has fallen
    away to the substrate.
    """
    world = 2.2

    trowel = blur(fbm(res, seed + 1, beta=2.2, low_cycles=3.0), res * 0.004)
    swirl = warp(trowel, (fbm(res, seed + 2, beta=2.2) - 0.5) * res * 0.05,
                 (fbm(res, seed + 3, beta=2.2) - 0.5) * res * 0.05)
    fine = fbm(res, seed + 4, beta=1.4, low_cycles=22.0)

    # Water damage in three layers, because one mask reads as a cloud. A broad
    # damp area, a hard tide line at its edge where the water stopped and dried
    # its dissolved load, and vertical runs above it. All ragged-edged.
    damp = stain(res, seed + 5, threshold=0.56, softness=0.10, detail=0.45, low_cycles=1.2)
    tide_edge = stain(res, seed + 5, threshold=0.52, softness=0.02, detail=0.45, low_cycles=1.2) - \
        stain(res, seed + 5, threshold=0.58, softness=0.03, detail=0.45, low_cycles=1.2)
    trickle = runs(stain(res, seed + 21, threshold=0.74, softness=0.03, detail=0.5, low_cycles=2.5),
                   length=int(res * 0.16)) * 0.55

    # Weighted down from what looks right in an image viewer. Plaster is the
    # brightest surface in the building and its value range is doing structural
    # work — heavy blotching turns it into camouflage and costs the room the one
    # wall that reliably throws light back.
    marks = np.clip(damp * 0.40 + np.clip(tide_edge, 0.0, 1.0) * 0.60 + trickle * 0.8, 0.0, 1.0)

    blown = stain(res, seed + 6, threshold=0.70, softness=0.05, detail=0.55, low_cycles=4.0)
    hairline = np.zeros((res, res), dtype=np.float32)
    for cells, width, offset in ((9, 0.0030, 61), (17, 0.0018, 71)):
        f1, f2, _ = worley(res, cells, seed + offset, jitter=0.95)
        vein = 1.0 - smoothstep(0.0, width, f2 - f1)
        hairline = np.maximum(hairline, vein * smoothstep(0.45, 0.72, fbm(res, seed + offset + 3, beta=2.2, low_cycles=2.0)))

    mould = stain(res, seed + 7, threshold=0.76, softness=0.04, detail=0.5, low_cycles=3.0) * marks

    height = np.clip(0.88 + swirl * 0.06 + fine * 0.02 - blown * 0.45 - hairline * 0.50, 0.0, 1.0)

    shade = (0.86 + 0.28 * swirl) * (0.95 + 0.10 * fine)
    colour = tint((0.430, 0.418, 0.388), shade, (0.250, 0.212, 0.158), marks * 0.60)
    colour = tint(colour, np.ones((res, res), np.float32), (0.135, 0.140, 0.115), mould * 0.55)
    colour = tint(colour, np.ones((res, res), np.float32), (0.290, 0.268, 0.238), blown * 0.70)
    colour *= 1.0 - 0.30 * hairline[..., None]

    roughness = np.clip(0.80 + 0.10 * fine - 0.10 * marks + 0.12 * blown, 0.30, 1.0)

    return MapSet(colour, roughness, height, np.zeros((res, res), np.float32), world, 0.008)


# ── Ceiling ─────────────────────────────────────────────────────────────────


def build_ceiling_concrete(res: int, seed: int) -> MapSet:
    """Concrete soffit with form marks — the plank impressions the shuttering left.

    A ceiling is mostly seen at a grazing angle in flashlight spill, so its whole
    job is to have *direction*. Board impressions running one way give the eye
    something to follow down a corridor. Kept a little darker than the walls
    because it is the surface furthest from the beam and closest to the shadow
    the room needs.
    """
    world = 2.5
    boards = 12

    board_position = stripes(res, boards, axis=0)
    board_index = index_of(res, boards, axis=0)
    board_seam = groove(board_position, 0.055, softness=0.5)
    board_tone = cell_random(board_index, boards, seed + 1, 0.88, 1.12)

    # Grain of the shuttering timber, printed into the concrete.
    grain = blur(fbm(res, seed + 2, beta=1.3, low_cycles=5.0), res * 0.008)
    grain = warp(grain, np.zeros((res, res)), (fbm(res, seed + 3, beta=2.4) - 0.5) * res * 0.015)

    base = warped_fbm(res, seed + 4, beta=2.2, strength=res * 0.04)

    # Water tracks along a board joint before it drips, so seepage is seeded on
    # the joints. Soot is the opposite — it settles evenly and only collects in
    # the low corners — so it stays a broad ragged field.
    seep = np.clip(
        board_seam * stain(res, seed + 5, threshold=0.42, softness=0.10, detail=0.6, low_cycles=2.0) * 0.9
        + stain(res, seed + 8, threshold=0.70, softness=0.05, detail=0.55, low_cycles=2.5) * 0.55,
        0.0, 1.0)
    soot = stain(res, seed + 6, threshold=0.60, softness=0.10, detail=0.5, low_cycles=1.5)
    pits = smoothstep(0.80, 0.94, fbm(res, seed + 7, beta=1.3, low_cycles=24.0))

    height = np.clip(0.86 + base * 0.05 + grain * 0.05 - board_seam * 0.62 - pits * 0.28, 0.0, 1.0)

    shade = board_tone * (0.88 + 0.22 * base) * (0.90 + 0.20 * grain)
    shade *= 1.0 - 0.30 * soot
    colour = tint((0.300, 0.296, 0.288), shade, (0.090, 0.088, 0.086), np.clip(board_seam * 0.8 + pits * 0.5, 0, 1))
    colour = tint(colour, np.ones((res, res), np.float32), (0.185, 0.165, 0.130), seep * 0.55)

    roughness = np.clip(0.82 + 0.10 * grain - 0.12 * seep + 0.08 * pits, 0.32, 1.0)

    return MapSet(colour, roughness, height, np.zeros((res, res), np.float32), world, 0.011)


# ── Trim ────────────────────────────────────────────────────────────────────


def build_trim_steel(res: int, seed: int) -> MapSet:
    """Rusted steel trim — the kit's `Trim_Steel` slot.

    Trim runs along corridor edges, so it is almost always *inside* the beam
    while the wall behind it is not. Making it rusted and rough rather than clean
    steel means it reads as a band of warm colour rather than a blown-out
    highlight line.
    """
    world = 1.0

    ribs = stripes(res, 6, axis=0)
    rib = smoothstep(0.44, 0.28, np.abs(ribs - 0.5))
    edge = groove(ribs, 0.10, softness=0.6)

    pit_distance, _, pit_owner = worley(res, 40, seed + 1, jitter=1.0)
    pitting = smoothstep(0.014, 0.004, pit_distance) * smoothstep(0.55, 0.80, per_cell(pit_owner, 40, seed + 2, 0.0, 1.0))

    rust = np.clip(
        stain(res, seed + 3, threshold=0.48, softness=0.07, detail=0.6, low_cycles=5.0) + pitting * 0.8,
        0.0, 1.0)
    flake = smoothstep(0.62, 0.84, fbm(res, seed + 4, beta=1.6, low_cycles=14.0)) * rust
    brushed = fbm(res, seed + 5, beta=1.1, low_cycles=45.0)
    scuff = scratches(res, seed + 6, count=45, length=0.28, width=0.0012)

    height = np.clip(0.78 + rib * 0.12 - edge * 0.45 - pitting * 0.35 + rust * 0.06 + brushed * 0.02, 0.0, 1.0)

    shade = (0.88 + 0.24 * brushed) * (1.0 - 0.18 * scuff)
    colour = tint((0.310, 0.318, 0.330), shade, (0.255, 0.118, 0.052), rust * 0.92)
    colour = tint(colour, np.ones((res, res), np.float32), (0.160, 0.082, 0.045), flake * 0.60)
    colour *= 1.0 - 0.22 * edge[..., None]

    roughness = np.clip(0.34 + 0.55 * rust + 0.20 * pitting + 0.14 * scuff, 0.20, 1.0)

    # Held well below 1.0. A fully metallic surface has no diffuse term at all,
    # so with this scene's near-black ambient it renders as a black cutout with a
    # highlight sitting in it — the trim disappears the instant the beam moves off
    # it, which is the opposite of what trim is for.
    metallic = np.clip(0.45 * (1.0 - rust), 0.0, 1.0)

    return MapSet(colour, roughness, height, metallic, world, 0.010)


def build_trim_door(res: int, seed: int) -> MapSet:
    """Painted door leaf and frame — the kit's `Door_Leaf` slot.

    §04's Mechanic locks doors at the chokepoints §12 puts them in, so a door is
    a thing players *look for*. It is the palest surface in the set so that a
    beam finds it first, with the paint chipped back to primer at the edges where
    hands and trolleys hit it.
    """
    world = 1.2

    panel_y = stripes(res, 2, axis=0)
    panel_x = stripes(res, 1, axis=1)
    inset = np.maximum(
        smoothstep(0.16, 0.24, np.abs(panel_y - 0.5) * 2.0),
        smoothstep(0.55, 0.72, np.abs(panel_x - 0.5) * 2.0),
    )
    rail = groove(panel_y, 0.10, softness=0.6)

    brush = blur(fbm(res, seed + 1, beta=1.9, low_cycles=6.0), res * 0.004)
    brush = warp(brush, (fbm(res, seed + 2, beta=2.4) - 0.5) * res * 0.01, np.zeros((res, res)))

    chip = stain(res, seed + 3, threshold=0.62, softness=0.04, detail=0.6, low_cycles=8.0)
    chip = np.clip(chip * (0.30 + 0.70 * np.maximum(rail, 1.0 - inset)), 0.0, 1.0)
    grime = np.clip(
        stain(res, seed + 4, threshold=0.54, softness=0.09, detail=0.5, low_cycles=2.0) * 0.7
        + runs(stain(res, seed + 7, threshold=0.76, softness=0.03, detail=0.6, low_cycles=4.0),
               length=int(res * 0.12)) * 0.5,
        0.0, 1.0)
    scuff = scratches(res, seed + 5, count=30, length=0.20, width=0.0014)

    height = np.clip(0.84 + inset * 0.08 - rail * 0.40 + brush * 0.03 - chip * 0.25, 0.0, 1.0)

    shade = (0.90 + 0.20 * brush) * (1.0 - 0.14 * scuff)
    colour = tint((0.352, 0.340, 0.300), shade, (0.230, 0.216, 0.188), np.clip(grime * 0.55 + rail * 0.4, 0, 1))
    colour = tint(colour, np.ones((res, res), np.float32), (0.245, 0.140, 0.092), chip * 0.75)

    roughness = np.clip(0.42 + 0.34 * chip + 0.16 * grime + 0.10 * scuff, 0.14, 1.0)

    return MapSet(colour, roughness, height, np.zeros((res, res), np.float32), world, 0.009)


def build_trim_skirting(res: int, seed: int) -> MapSet:
    """Painted timber skirting — the base board where wall meets floor.

    Not bound to a kit slot yet (the kit has no skirting mesh). Generated because
    the moment one is modelled this has to exist, and a skirting board is the
    cheapest way to stop a wall/floor junction reading as two planes meeting at
    nothing — the artefact that made the baseline look like grey boxes.
    """
    world = 1.0

    profile = stripes(res, 1, axis=0)
    bead = smoothstep(0.10, 0.04, np.abs(profile - 0.22)) + smoothstep(0.07, 0.02, np.abs(profile - 0.34))
    body = smoothstep(0.02, 0.10, profile) * smoothstep(0.98, 0.86, profile)

    # Shadow lines top and bottom. A skirting board is nailed over finished wall
    # and never sits flush, so there is a dark gap where it meets the plaster and
    # another where it meets the floor. Without them the profile is all smooth
    # ramps, the AO map has nothing to occlude, and the board reads as a painted
    # stripe rather than as a thing standing proud of the wall.
    shadow_top = smoothstep(0.030, 0.006, np.abs(profile - 0.87))
    shadow_floor = smoothstep(0.030, 0.006, np.abs(profile - 0.05))
    shadow = np.clip(shadow_top + shadow_floor, 0.0, 1.0)

    grain = blur(fbm(res, seed + 1, beta=1.3, low_cycles=4.0), res * 0.010)
    grain = warp(grain, np.zeros((res, res)), (fbm(res, seed + 2, beta=2.4) - 0.5) * res * 0.02)

    # Skirting takes damage at the bottom, from mops, boots and damp.
    low = smoothstep(0.42, 0.06, profile)
    chip = smoothstep(0.66, 0.85, fbm(res, seed + 3, beta=1.5, low_cycles=16.0)) * (0.3 + 0.7 * low)
    scuffing = np.clip(low * smoothstep(0.35, 0.75, fbm(res, seed + 4, beta=2.0, low_cycles=3.0)), 0.0, 1.0)
    dust = warped_fbm(res, seed + 5, beta=2.4, strength=res * 0.04, low_cycles=1.5)

    height = np.clip(0.70 + body * 0.14 + bead * 0.14 + grain * 0.03 - chip * 0.25
                     - shadow * 0.55, 0.0, 1.0)

    shade = (0.90 + 0.20 * grain)
    colour = tint((0.340, 0.330, 0.298), shade, (0.215, 0.196, 0.168), np.clip(scuffing * 0.7 + dust * 0.3, 0, 1))
    colour = tint(colour, np.ones((res, res), np.float32), (0.230, 0.148, 0.090), chip * 0.70)
    colour *= 1.0 - 0.45 * shadow[..., None]

    roughness = np.clip(0.48 + 0.30 * chip + 0.14 * scuffing + 0.08 * grain + 0.15 * shadow, 0.16, 1.0)

    return MapSet(colour, roughness, height, np.zeros((res, res), np.float32), world, 0.012)


# ── The set ─────────────────────────────────────────────────────────────────
#
# `slots` are MapKit material slot names read out of
# `Assets/Models/MapKit/MapKit.manifest.json`. The Unity side binds by these, so
# the contractual Floor_* names survive: §04's Listener reads the surface off the
# collider's physics material and the footstep audio matches on the same string.


MATERIALS: Tuple[MaterialSpec, ...] = (
    MaterialSpec(
        "Floor_Wood", build_wood, seed=1201, target_albedo=0.20,
        slots=("Floor_Wood",),
        note="§12 구역 A 나무 — staggered boards, deep gaps, soft traffic lane.",
    ),
    MaterialSpec(
        "Floor_Tile", build_tile, seed=1301, target_albedo=0.32,
        slots=("Floor_Tile",),
        note="§12 구역 B 타일 — 8×8 grid, dark grout, glossiest floor so the beam streaks.",
    ),
    MaterialSpec(
        "Floor_Gravel", build_gravel, seed=1401, target_albedo=0.24,
        slots=("Floor_Gravel",),
        note="§12 구역 C 자갈 — three stone scales, 45 mm relief, deepest normals in the set.",
    ),
    MaterialSpec(
        "Floor_Concrete", build_concrete_floor, seed=1501, target_albedo=0.28,
        slots=("Floor_Concrete",),
        note="§12 구역 D 콘크리트 — stains, exposed aggregate, two-scale crack network.",
    ),
    MaterialSpec(
        "Floor_Metal", build_metal_floor, seed=1601, target_albedo=0.26,
        slots=("Floor_Metal",),
        note="§12 계단 금속 — diamond tread, rivets, rust streaks, lowest roughness.",
    ),
    MaterialSpec(
        "Wall_Brick_Painted", build_wall_brick, seed=2101, target_albedo=0.22,
        slots=("Wall_Structure",),
        note="Painted brick, stretcher bond. Bound to the kit's single wall slot.",
    ),
    MaterialSpec(
        "Wall_Concrete_Bare", build_wall_concrete, seed=2201, target_albedo=0.27,
        note="Board-formed concrete with snap-tie holes. Generated, awaiting a per-zone wall slot.",
    ),
    MaterialSpec(
        "Wall_Plaster_Stained", build_wall_plaster, seed=2301, target_albedo=0.34,
        slots=("Wall_Dado",),
        note="Water-stained plaster on the dado — the lower wall band. Rising damp is a "
             "lower-wall phenomenon, and the palest surface sits where the beam points.",
    ),
    MaterialSpec(
        "Ceiling_Concrete_Formed", build_ceiling_concrete, seed=3101, target_albedo=0.21,
        slots=("Ceiling_Structure",),
        note="Board-marked soffit — directional grain for corridors seen at grazing angles.",
    ),
    MaterialSpec(
        "Trim_Steel_Rusted", build_trim_steel, seed=4101, target_albedo=0.19,
        slots=("Trim_Steel",),
        note="Rusted ribbed steel. Sits inside the beam more often than the wall behind it.",
    ),
    MaterialSpec(
        "Trim_Door_Painted", build_trim_door, seed=4201, target_albedo=0.31,
        slots=("Door_Leaf",),
        note="Painted door leaf — palest surface, so a beam finds §04's 정비공 chokepoints first.",
    ),
    MaterialSpec(
        "Trim_Skirting_Painted", build_trim_skirting, seed=4301, target_albedo=0.29,
        slots=("Trim_Painted",),
        tiling_axes=(1,),
        note="Painted skirting, a cross-section profile: tiles along its length only.",
    ),
)


# ── Verification ────────────────────────────────────────────────────────────
#
# The three properties that, if wrong, make the whole set worthless. Measured,
# never eyeballed.


@dataclass
class TextureReport:
    """What one generated material measured. Printed as a table at the end."""

    name: str
    resolution: int
    world_size: float
    albedo_mean_linear: float
    albedo_min_linear: float
    albedo_max_linear: float
    calibration_gain: float
    roughness_mean: float
    roughness_span: float
    normal_unit_error: float
    normal_relief_mm: float
    ao_mean: float
    ao_contrast: float = 0.0
    seam_ratio: float = 0.0
    failures: List[str] = field(default_factory=list)


def seam_ratio(image: np.ndarray, axes: Tuple[int, ...] = (0, 1)) -> float:
    """How far the wrap-around edge is an outlier among ordinary interior edges.

    Testing edge rows for *equality* would fail every detailed texture — two
    neighbouring rows of gravel are not equal either. So the test is whether the
    wrap pair is a *discontinuity*: does it differ more than adjacent pairs
    elsewhere in the same image?

    The comparison is against the *largest* interior difference, and arriving at
    that took two wrong answers worth recording, because both are the obvious
    thing to do.

    Comparing against the **mean** flags every texture that has structure in it.
    A board-formed wall has ten hard board boundaries among a thousand smooth row
    pairs, so the mean is dominated by the smooth ones; the wrap lands on a board
    boundary — it must, since the boundaries are periodic too — and the ratio
    explodes to 18 on a texture that is provably periodic.

    Comparing against a high **percentile** fixes that case and then fails when a
    texture has only a *few* structural edges. This wall's snap-tie holes sit on
    four rows, so the 99th percentile of a thousand row pairs still lands among
    the smooth ones and a legitimate streak start reads as a seam. The percentile
    that works depends on how many edges the texture happens to contain, which
    means it is not a criterion, it is a fudge factor.

    The **maximum** has neither problem, and states something meaningful on its
    own: a seam is a discontinuity *bigger than any that legitimately occurs
    inside the image*. It needs no tuning per material and no assumption about
    feature counts. Measured this way the whole set scores 0.0–0.95 and a real
    discontinuity scores 6–12.

    `axes` exists for profile textures, where tiling in one direction is the
    wrong thing to ask for — see `MaterialSpec.tiling_axes`.
    """
    data = np.asarray(image, dtype=np.float64)
    worst = 0.0

    for axis in axes:
        rolled = np.moveaxis(data, axis, 0).reshape(data.shape[axis], -1)
        wrap = float(np.abs(rolled[0] - rolled[-1]).mean())
        interior = np.abs(np.diff(rolled, axis=0)).mean(axis=1)
        worst = max(worst, wrap / max(float(interior.max()), 1e-9))

    return float(worst)


def verify(spec: MaterialSpec, maps: MapSet, normal: np.ndarray, occlusion: np.ndarray,
           gain: float) -> TextureReport:
    """Measures a finished material and records every way it fails the contract."""
    res = maps.albedo.shape[0]
    failures: List[str] = []

    albedo_mean = float(maps.albedo.mean())
    if not ALBEDO_MIN_LINEAR <= albedo_mean <= ALBEDO_MAX_LINEAR:
        failures.append(
            "albedo mean %.4f outside [%.2f, %.2f] linear — the beam would land on it invisibly"
            % (albedo_mean, ALBEDO_MIN_LINEAR, ALBEDO_MAX_LINEAR)
        )

    # Normals must be unit length or the lighting maths is simply wrong: a short
    # normal darkens the surface, which is the exact failure this file exists to
    # undo. Measured after the 8-bit round trip, because that is what ships.
    decoded = np.asarray(to_u8(normal * 0.5 + 0.5), dtype=np.float32) / 255.0 * 2.0 - 1.0
    lengths = np.linalg.norm(decoded, axis=-1)
    unit_error = float(np.abs(lengths - 1.0).max())
    if unit_error > NORMAL_UNIT_TOLERANCE:
        failures.append("normal max unit-length error %.4f > %.4f — not normalised"
                        % (unit_error, NORMAL_UNIT_TOLERANCE))

    # A flat normal map is a silent failure: it imports, it renders, and the
    # surface just stays flat. Require it to actually vary.
    if float(np.abs(decoded[..., 2] - 1.0).mean()) < 1e-4:
        failures.append("normal map is flat — no relief was generated from the height field")

    ratios: List[float] = []
    for label, image in (("albedo", maps.albedo), ("normal", normal), ("roughness", maps.roughness),
                         ("occlusion", occlusion), ("height", maps.height)):
        ratio = seam_ratio(image, spec.tiling_axes)
        ratios.append(ratio)
        if ratio > SEAM_RATIO_LIMIT:
            failures.append("%s seam ratio %.2f > %.2f — a visible join every %.1f m"
                            % (label, ratio, SEAM_RATIO_LIMIT, maps.world_size))

    # Roughness that never varies is the "flat colour" problem wearing a hat: the
    # whole surface answers the beam identically and nothing reads as material.
    roughness_span = float(maps.roughness.max() - maps.roughness.min())
    if roughness_span < 0.12:
        failures.append("roughness span %.3f is too flat to read as a real surface" % roughness_span)

    # An all-white AO map is the quietest failure in the set: it imports, it
    # binds, it renders, and the joints simply never darken. One shipped already
    # because nothing measured it, so it is measured now.
    #
    # The test is deliberately not "is the mean low enough". A smooth plaster
    # wall genuinely has almost no occlusion, and a cracked concrete floor has
    # deep occlusion over one percent of its area — both have a mean near 1.0,
    # and both are correct. What has to hold is the *relationship*: the crevices
    # must come out darker than the high points. That is scale-free, it is what
    # AO means, and a no-op map fails it outright.
    low_mark, high_mark = np.percentile(maps.height, [10.0, 90.0])
    crevice = occlusion[maps.height <= low_mark]
    peak = occlusion[maps.height >= high_mark]
    contrast = float(peak.mean() - crevice.mean()) if crevice.size and peak.size else 0.0

    if contrast < 0.03:
        failures.append(
            "AO contrast %.4f between crevice and peak — the map is not occluding anything"
            % contrast)

    return TextureReport(
        name=spec.name,
        resolution=res,
        world_size=maps.world_size,
        albedo_mean_linear=albedo_mean,
        albedo_min_linear=float(maps.albedo.min()),
        albedo_max_linear=float(maps.albedo.max()),
        calibration_gain=gain,
        roughness_mean=float(maps.roughness.mean()),
        roughness_span=roughness_span,
        normal_unit_error=unit_error,
        normal_relief_mm=float(maps.height.max() - maps.height.min()) * maps.height_scale * 1000.0,
        ao_mean=float(occlusion.mean()),
        ao_contrast=contrast,
        seam_ratio=max(ratios),
        failures=failures,
    )


# ── Generation ──────────────────────────────────────────────────────────────


def generate(spec: MaterialSpec, out_dir: str, res: int) -> TextureReport:
    """Builds, calibrates, writes and measures one material."""
    maps = spec.build(res, spec.seed)
    maps.albedo, gain = finish_albedo(maps.albedo, spec.target_albedo)
    maps.roughness = np.maximum(maps.roughness, MIN_ROUGHNESS).astype(np.float32)

    normal = height_to_normal(maps.height, maps.world_size, maps.height_scale)
    occlusion = ambient_occlusion(maps.height, maps.world_size, maps.height_scale)

    folder = os.path.join(out_dir, spec.name)
    write_png(os.path.join(folder, spec.name + "_albedo.png"),
              to_u8(linear_to_srgb(maps.albedo)))
    write_png(os.path.join(folder, spec.name + "_normal.png"),
              to_u8(normal * 0.5 + 0.5))
    write_png(os.path.join(folder, spec.name + "_rough.png"),
              to_u8(maps.roughness))
    write_png(os.path.join(folder, spec.name + "_ao.png"),
              to_u8(occlusion))

    # URP's Lit shader reads metallic from _MetallicGlossMap.r and smoothness
    # from its alpha, so the two have to travel in one texture. The separate
    # roughness map above stays the authored, inspectable deliverable; this is
    # the packing the shader happens to want.
    mask = np.zeros((res, res, 4), dtype=np.float32)
    mask[..., 0] = maps.metallic
    mask[..., 1] = maps.metallic
    mask[..., 2] = maps.metallic
    mask[..., 3] = 1.0 - maps.roughness
    write_png(os.path.join(folder, spec.name + "_ms.png"), to_u8(mask))

    return verify(spec, maps, normal, occlusion, gain)


def report_table(reports: Sequence[TextureReport]) -> str:
    """The measurement table. Every number here is a thing that can be wrong."""
    header = ("%-26s %6s %6s %8s %8s %6s %7s %7s %8s %6s %6s"
              % ("material", "px", "size", "albedo", "range", "gain", "rough", "seam", "relief",
                 "AO", "AOcon"))
    lines = [header, "-" * len(header)]

    for r in reports:
        lines.append(
            "%-26s %6d %5.1fm %8.4f %3.2f-%3.2f %6.2f %7.2f %7.2f %6.1fmm %6.2f %6.3f%s"
            % (r.name, r.resolution, r.world_size, r.albedo_mean_linear,
               r.albedo_min_linear, r.albedo_max_linear, r.calibration_gain,
               r.roughness_mean, r.seam_ratio, r.normal_relief_mm, r.ao_mean, r.ao_contrast,
               "" if not r.failures else "  FAIL")
        )

    return "\n".join(lines)


def write_manifest(path: str, reports: Sequence[TextureReport], res: int) -> None:
    """A manifest the Unity side reads, so slot binding is data rather than a second list.

    Two copies of "which texture goes on which kit slot" would drift the first
    time a material was renamed, and the failure would be a silently untextured
    wall. One copy, written by the generator, imported by the editor script.
    """
    import json

    by_name = {r.name: r for r in reports}
    payload = {
        "generated_by": "tools/textures/gen_textures.py",
        "resolution": res,
        "albedo_band_linear": [ALBEDO_MIN_LINEAR, ALBEDO_MAX_LINEAR],
        "materials": [
            {
                "name": spec.name,
                "slots": list(spec.slots),
                "note": spec.note,
                "world_size_metres": by_name[spec.name].world_size,
                "albedo_mean_linear": round(by_name[spec.name].albedo_mean_linear, 4),
                "roughness_mean": round(by_name[spec.name].roughness_mean, 4),
                "relief_mm": round(by_name[spec.name].normal_relief_mm, 2),
                "maps": {
                    "albedo": spec.name + "/" + spec.name + "_albedo.png",
                    "normal": spec.name + "/" + spec.name + "_normal.png",
                    "roughness": spec.name + "/" + spec.name + "_rough.png",
                    "occlusion": spec.name + "/" + spec.name + "_ao.png",
                    "metallic_smoothness": spec.name + "/" + spec.name + "_ms.png",
                },
            }
            for spec in MATERIALS
            if spec.name in by_name
        ],
    }

    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2, ensure_ascii=False)
        handle.write("\n")


DEFAULT_OUT = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)),
                 "..", "..", "unity", "HorrorGame", "Assets", "Textures")
)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=DEFAULT_OUT, help="Output directory (Assets/Textures).")
    parser.add_argument("--res", type=int, default=DEFAULT_RESOLUTION, help="Texels per side.")
    parser.add_argument("--only", default=None, help="Substring filter on material name.")
    args = parser.parse_args(argv)

    if args.res & (args.res - 1):
        print("resolution must be a power of two — GPU block compression needs it", file=sys.stderr)
        return 2

    selected = [m for m in MATERIALS if args.only is None or args.only.lower() in m.name.lower()]
    if not selected:
        print("no material matched %r" % args.only, file=sys.stderr)
        return 2

    reports: List[TextureReport] = []
    for spec in selected:
        print("  generating %-26s ..." % spec.name, end="", flush=True)
        report = generate(spec, args.out, args.res)
        reports.append(report)
        print(" ok" if not report.failures else " FAIL")

    print()
    print(report_table(reports))
    print()

    failed = [r for r in reports if r.failures]
    for r in failed:
        for message in r.failures:
            print("FAIL  %-26s %s" % (r.name, message), file=sys.stderr)

    if failed:
        print("\n%d of %d materials failed." % (len(failed), len(reports)), file=sys.stderr)
        return 1

    if len(selected) == len(MATERIALS):
        write_manifest(os.path.join(args.out, "Textures.manifest.json"), reports, args.res)

    means = [r.albedo_mean_linear for r in reports]
    print("all %d materials pass: albedo means %.3f-%.3f (band %.2f-%.2f linear), "
          "worst seam ratio %.2f, worst normal error %.4f"
          % (len(reports), min(means), max(means), ALBEDO_MIN_LINEAR, ALBEDO_MAX_LINEAR,
             max(r.seam_ratio for r in reports), max(r.normal_unit_error for r in reports)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
